### ISSUE TITLE
new entries

### ISSUE THREAD

**Issue by whamola** [Clefspeare13/pornhosts#1]
hi clefspeare13, those i'm going to list are sites i found simply typing "porno" on google with italian localization...13 google pages. :O

http://ipornogratis.xxx/
http://www.pornoitaliano.com/
http://www.pornomexicana.com.mx/
http://srv2.frescoporno.com/
http://www.moglietroia.it/
http://www.pornoorzel.com/
http://www.belloporno.it/
http://pornocaldo.it/
http://www.canalporno.com/
http://www.xitalian.com/
http://youpornhd.co/
http://mogliescopata.com/
http://www.troiaitaliana.com/
http://www.voglioporno.com/
http://www.cagnaporno.com/
http://www.casalingheporno.it/
http://www.tantoporno.com/
http://www.pornoitaliane.it/
http://www.lupoporno.com/
http://www.amaporn.com/
http://xxxvideoporno.it/
http://pornoxxx.it/
http://www.pornokura.it/
http://www.aztecaporno.com/
http://www.pornototale.com/
http://www.sambaporno.com/
http://www.toroporno.com/
http://www.norskporno.xxx/
http://www.pornoinitaliano.it/
http://www.megasesso.com/
https://www.guardalaporno.com/
http://www.coqnu.com/
http://www.badjojo.com/
http://www.streetblowjobs.com/
http://www.pervsonpatrol.com/
http://www.bigmouthfuls.com/
https://www.delhisexchat.com
http://www.livecamfun.com/
http://www.pornication.com/
http://www.privatefeeds.com/
https://www.xlovecam.com
http://playwithme.com/
http://www.totallynsfw.com/
http://www.pornotrio.com/
http://www.serviporno.com/
http://foto-porno.it/
http://www.pornoitaliano.eu/
http://www.hdpornochief.com/
http://www.muycerdas.xxx/
http://www.pornoamateurvip.com/
http://ipornovideos.xxx/
http://www.tukif.com/
http://pendejas.com.ar/
http://www.pornofico.com/
http://www.pornolaan.com/
http://www.potrr2.com/
https://www.torinoerotica.com
http://www.mrvideoscaseros.xxx/
http://www.filmxxx.it/
http://guarrasdelporno.xxx/
http://www.pornocolombia.com.co/
http://www.porno-videot.com/
http://www.valentina-nappi.it/
http://www.pornofica.net/
http://pulpo69.com/
http://www.portablesex.com/
http://www.pornoamatoriali.net/
http://www.pornosvane.com/
http://www.pornokarhu.com/
http://www.mrvideoporno.xxx/

**Comment by whamola** [comment]
my plan is: i wait you to add the new entries, then i make another search with more sexual-specific words. Then i'll change language and localization and so on!

**Comment by whamola** [comment]
other sites:
http://www.tantoporno.com/
http://www.apetube.com/
http://www.tubepleasure.com/
https://www.publicpornhd.com
http://www.tubegals.com/
http://www.lupoporno.com/
http://www.amaporn.com/
http://www.yes.xxx/
http://www.pornktube.com/
http://www.hdpornmobilex.com/
https://www.luciemakesporn.com
http://www.lenaporn.net/
http://www.porn.it/
http://www.youporn.lc/
http://www.tubestack.com/
http://www.youupornhub.com/
http://www.pornoitaliano.eu/
http://www.pornoitaliano.com/
http://www.tiava.com/
http://www.guardalaporno.com/

**Comment by Clefspeare13** [comment]
Updated to this point

**Comment by ColinMaudry** [comment]
Shall I suggest new entries here or create new issue?

**Comment by Imparium** [comment]
Some brazilian porn sites:
videosexoonline.com
videosporno.vlog.br
novinhagostosa10.com
pornohd.blog.br
pornodoido.com
pornonacionais.com
xvideosf.com
filmepornoxxx.net
filme-porno.live
xvideos5.com.br
garotoesperto.com
xvideosamador.com.br
camerahot.com
eonline.com

**Comment by anti-warrior** [comment]
All domains are added to the list.

This issue should be closed now.

**Comment by w8Pk1y** [comment]
desipapa.xxx
dirtypornphotos.com
indiansexphotos.com
indiankinkygirls.com
unseenmms.com
indiangirlsclub.com
hotnakedgirls.net
ooodesi.com
provocationstudio.ru
xbombo.com
the-urbn.com
indiansexvideos.porn
desipornfilm.com
hardindianporn.com
mostdesisex.com
sexyindiantube.com
bestindiansex.com
finaldesitube.com
nicedesiporn.com
