### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by ColinMaudry** [Clefspeare13/pornhosts#10]
Hi,

Are Github issues the best way to contribute?

I was thinking how I could easily add new domains to the hosts files, but since for each domain I need to manually:

1. find where the domains fits alphabetically
2. add it
3. repeat for each of the three files

That's a bit cumbersome.

Do you use a script to easily add a domain to all three files? If so, could you add it to the repo so that one could send clean PRs?

**Comment by Clefspeare13** [comment]
Actually, I just add domains to one of the hosts, and then copy paste the whole lot into the other files and search+replace the 0.0.0.0 and 127.0.0.1. It's not efficient, but it works

**Comment by ColinMaudry** [comment]
Let's say you have 20 domains to add. How do you do to preserve the alphabetical order?

**Comment by Imparium** [comment]
You can put the domains randomly and use notepad++ atom or any other online service to organize them automatically
