### ISSUE TITLE
www.keepersecurity.com

### ISSUE THREAD

**Issue by salevdns** [Clefspeare13/pornhosts#105]
Hey, sorry the link to the CONTRIBUTING.md doesn't work.

I've found a false positive in this List:
www.keepersecurity.com
It's a domain from Keeper Security, Inc. which is used for their password manager service.

**Comment by spirillen** [comment]
Hi @salevdns Thanks for your feedback, but currently the CONTRIBUTING.md is awaiting @Clefspeare13 comments for approval :smiley: But the draft can be found here: https://github.com/Clefspeare13/pornhosts/pull/102/files#diff-6a3371457528722a734f3c51d9238c13R1-R77

And for your FP submission, i'll get back to it a bit later, as I currently is busy in my own project
