### ISSUE TITLE
Add redgifs.com and www.redgifs.com

### ISSUE THREAD

**Issue by lich-tex** [Clefspeare13/pornhosts#110]

**Comment by spirillen** [comment]
First off `redgifs.com` redirects to `www.redgifs.com`

And additional hosts file records vs RPZ

```python
thcf1.redgifs.com
thcf2.redgifs.com
thcf3.redgifs.com
thcf4.redgifs.com
thcf5.redgifs.com
thcf6.redgifs.com
thcf7.redgifs.com
thcf8.redgifs.com
metrics.redgifs.com
weblogin.redgifs.com
```

<details><summary>ScreenShot</summary>

![image](https://user-images.githubusercontent.com/44526987/88474951-a9f26580-cf2b-11ea-9602-bf44dacface6.png)

</details>

**Comment by obeho** [comment]
Hey, @spirillen how did you categorize `px.redgifs.com` as tracking? It is useful in loading the platform ig. Please refer to this link for exact information. `https://www.reddit.com/r/gfycat/comments/1t4f3y/responsiveflexible_gfycat_code/`

**Comment by spirillen** [comment]
> Hey, @spirillen how did you categorize `px.redgifs.com` as tracking? It is useful in loading the platform ig. Please refer to this link for exact information. `https://www.reddit.com/r/gfycat/comments/1t4f3y/responsiveflexible_gfycat_code/`

It's all in the commit message <https://www.mypdns.org/T979> images and all :smiley:

**Comment by obeho** [comment]
Hey, thanks, I already viewed that page before commenting here. Sorry but I don't see anything conclusive there, except its being blocked by 2 differerent blocklists. Could you please explain?

**Comment by spirillen** [comment]
`px.redgifs.com` is for hosting tracking pixels.... `/pix.git?` and `px.gif` those are tracking pixels on YOU and YOUR DEVICE(S), also known as fingerprinting.

| +210 | /pix.gif? | -- | `www.redgifs.com` | 1 | xhr | `https://metrics.redgifs.com/pix.gif?event=adultforce_ad_view&size=300x250&app_id=com.redgifs.website&utc=5c5af616-b492-4665-b068-27a6ef20fdd3&stc=1a445ebf-18ad-46c2-8f15-72f4eb74b3f6&ref=%2Fwatch%2Fancientfriendlyicterinewarbler&device_type=desktop&cache=1595752895207` |

In the future, please take any questions to the relevant source/threads

PS: just noticed `metrics.redgifs.com` is missing, thanks

Locking issue as off topic.
