### ISSUE TITLE
[fastpic.ru] Please remove

### ISSUE THREAD

**Issue by dalisoft** [Clefspeare13/pornhosts#116]
Hi.

Thanks for such a good hosts list.
I found some entry was blocked from this list (fastpic.ru), maybe in this hosting some of peoples hosts useful images.
Can you whitelist and remove from block list?

For [example](https://fastpic.ru/view/112/2020/0626/_88b9ef394576f8f17ead6247ec6b7a6c.png.html?r=1)

_Do not click to any of url if you care about security as on that page has **trackers** and/or **ads**_

**Comment by spirillen** [comment]
Hi thanks for your question, could you please submit a screenshot from your link and post inside of the following code?

```
<details><summary>SchreenShot</summary>

Your uploaded image

</details>
```
And also if you would be so kind king to wrap your link into "`" (back-tics) , that would disable the url...

**Comment by dalisoft** [comment]
<img width="988" alt="08667C57-3A32-46B3-98AC-ABEBAE09A8B7" src="https://user-images.githubusercontent.com/3511344/86521447-53cd5d80-be6a-11ea-8a2c-e5d445e4b713.png">

Link: `https://fastpic.ru/view/112/2020/0626/_88b9ef394576f8f17ead6247ec6b7a6c.png.html?r=1`

**Comment by spirillen** [comment]
Thanks for your quick reply @dalisoft 

That seems rather harmless, but why the domain should have been added in the first place is beyond my knowledge

A blame shows it is somewhat new, but as it is Niclas (@Clefspeare13) who added it, suggest we get a broader number of comments of staying or removing.
```
d95d9009 (Niclas       2019-03-19 18:39:32 +0100 2124) 0.0.0.0 fastpic.ru
```

Is there anybody who have any comments on why this domain should stay or be removed?

**Comment by dalisoft** [comment]
@Clefspeare13 please can you get time and review this issue?
Thanks

**Comment by spirillen** [comment]
I'm moving this one into the `strict_adult` until @Clefspeare13 is back and can do some rulings

depending on PR <https://github.com/Clefspeare13/pornhosts/pull/138>
