### ISSUE TITLE
How often do you update the list?

### ISSUE THREAD

**Issue by Danilopereira82** [Clefspeare13/pornhosts#117]
i wanto to know how often you update the list from the issues
and if this list goes to StevenBlack hosts file

**Comment by spirillen** [comment]
Hi @Danilopereira82 as you might notice @Clefspeare13 isn't here that often, but anytime a valid PR is present (with documentation(Screenshot)) I merge it on his behalf, but all "just a bunch" of domain in a issue is up to @Clefspeare13 to add.

A good submission form would be like this: 

https://github.com/Clefspeare13/pornhosts/blob/bbdba075ea32b6fecd5b6e009c99dea8513dd804/.github/ISSUE_TEMPLATE/default.md

The form is build for keeping a history of why a domain was added and it would also have the explanation (a screenshot can be enough) other times there would obviously requires a bit more convincing arguments as a domain might be on the edge)

If you take this issue https://github.com/Clefspeare13/pornhosts/issues/116 as example, you will notice there are no option for track back why it was added in the past, only by whom :unamused: 

For the question about if it goes into the sb list you would need to ask there, but it have been in the past.

With al this said, in any twist @Clefspeare13 is the judge.

**Comment by Danilopereira82** [comment]
spirillen give me your emails i need to talk to you

**Comment by spirillen** [comment]
You can find me on keybase under the same name :smiley: or you can post a message here <https://gitlab.com/my-privacy-dns/matrix/matrix/-/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D=> and make it private.

and then give me a ping (I don't use e-mail at all, unless absolutely necessary (like in forced to))

**Comment by spirillen** [comment]
Hey @Danilopereira82 is it ok to close this issue?
