### ISSUE TITLE
Remove www.rapidgator.net

### ISSUE THREAD

**Issue by caviidae** [Clefspeare13/pornhosts#120]
`www.rapidgator.net` is just a generic file host with no relation to porn

**Comment by spirillen** [comment]
If I remember right, they at least used to hosts a lot of zipped Adult contents.

I'll follow up on this later.

**Comment by spirillen** [comment]
I have to leave the decision to @Clefspeare13 as I find the domain widely used to share adult material <https://publicwww.com/websites/rapidgator.net/>

This one is from `https://www.pornbb.org/jolee-love-what-a-gape-5on1-gio1481-25-jul-t7814693.html`
![image](https://user-images.githubusercontent.com/44526987/88460861-b204c380-ce9f-11ea-8ca2-43457402de87.png)

<details><summary> screenshot</summary>

![image](https://user-images.githubusercontent.com/44526987/88460844-9ac5d600-ce9f-11ea-8949-0e383a52747b.png)

</details>

**Comment by spirillen** [comment]
Also requested here <https://github.com/Sinfonietta/hostfiles/issues/115>
