### ISSUE TITLE
Issues with the most recent commits

### ISSUE THREAD

**Issue by StevenBlack** [Clefspeare13/pornhosts#121]
The [very last line in 0.0.0.0/hosts](https://github.com/Clefspeare13/pornhosts/blob/master/0.0.0.0/hosts#L9079) for example.  It says 

```
0.0.0.0 www.	# Porn domain from Clefspeare13 list
```

Note that `www.` is not a valid domain, and this IS the Clefspeare13 list.

By the way, at the bottom of this list, there is a heading comment that says `#Porn domain`, then each item repeats `#Porn domain` as a suffix.  It's just, messy?  This is all in a folder with `pornhosts` as one of the parent folders.  

I will hold releasing a new version of my amalgamated list until the last line is fixed, here...

**Comment by spirillen** [comment]
Thanks for the notification.... fixing it right up

**Comment by spirillen** [comment]
A short note for the comments;

These are added there to divide the differenses between the porn and snuff, which will be "rooted" to the `submit_here/lists`, so they are temporary till I'm done rewriting the script.
