### ISSUE TITLE
Adopt license for project

### ISSUE THREAD

**Issue by brarcher** [Clefspeare13/pornhosts#13]
I noticed that there is no license in place for this project. Currently I'm attempting to document the licenses used by various host file projects, including your own. The documentation will be listed in the following project, which is a collection of various host files:

https://github.com/StevenBlack/hosts

Would you consider adding a license for your project? The license would define who you allow to use you host file and in what context. Points to consider when choosing a license include:
- If someone uses the host file must they give attribution?
- Are derivatives of the host file allowed?
- Can the host file be used for commercial purposes?

The simplest license might be the [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). However, the selection is up to you, if you decide on a license at all. Note that if the project does not have a license, it is a gray area if someone is allowed to use the project.

Thanks!

**Comment by Clefspeare13** [comment]
I decided to go with an MIT license, as it seem rather simple and lax. 
Thanks for pointing this out!

**Comment by brarcher** [comment]
Thanks for adding a license!
