### ISSUE TITLE
hentaitube.info

### ISSUE THREAD

**Issue by 3xploiton3** [Clefspeare13/pornhosts#144]
hentaitube.info

**Comment by spirillen** [comment]
Please fill the form for submission if you like us to handle your request in good times.

My time here is subsidies.

I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python

www.
```

## Content sources

(Please see #35)

```python


```


## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>


</details>

## Logger output

## External Info
- 
- 
- 

### All Submissions:
- [ ] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [ ] Added a Screenshot for prove of Adult contents

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)
