### ISSUE TITLE
Additional hosts

### ISSUE THREAD

**Issue by ghost** [Clefspeare13/pornhosts#15]
Some additional websites: [new.1.txt](https://github.com/Clefspeare13/pornhosts/files/1575792/new.1.txt)
Partially taken from: `https://en.wikipedia.org/wiki/MindGeek#Global_Alexa_ranks`

**Comment by IDKwhattoputhere** [comment]
Some more porn sites:
[newporn.txt](https://github.com/Clefspeare13/pornhosts/files/1791035/newporn.txt)
