### ISSUE TITLE
Should www.asian-kitties.com go to hosts or strict_adult?

### ISSUE THREAD

**Issue by DaniV5** [Clefspeare13/pornhosts#189]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python

www.asian-kitties.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![asian-kitties1](https://user-images.githubusercontent.com/20802412/90257159-2686ae80-de1d-11ea-988f-6f80a84cceb4.jpg)
![asian-kitties2](https://user-images.githubusercontent.com/20802412/90257162-271f4500-de1d-11ea-8efd-62fe45707858.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [ ] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [ ] Added a Screenshot for prove of Adult contents

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
This is an open question for this PR <https://github.com/Clefspeare13/pornhosts/pull/188> as neither @DaniV5 or I can determine if this actually should be considered as a adult domain. After I have viewed the page, I would call it SFW.

What do you other think?

**Comment by spirillen** [comment]
Closed in be370b4
