### ISSUE TITLE
NordVPN blocked?

### ISSUE THREAD

**Issue by b2m9** [Clefspeare13/pornhosts#2]
I've seen that your hosts file is used by [Steven Black's consolidated hosts file](https://github.com/StevenBlack/hosts) and ran into the issue that it actually blocks my VPN provider NordVPN.

Any particular reason why `nordvpn.com` is on a porn blacklist? ([Line 3614](https://github.com/StevenBlack/hosts/blob/19f49032e650ed53ad3fb800f9cf4e5ecc448b91/extensions/porn/clefspeare13/hosts#L3614) and [line 4314](https://github.com/StevenBlack/hosts/blob/2a60d78b49f8f479d423179e0aa0a7bd9daa70ee/extensions/porn/sinfonietta/hosts#L4314))

Thanks!

**Comment by b2m9** [comment]
In case it is a mistake, I've opened a PR for you #3 
Cheers 🎉

**Comment by Clefspeare13** [comment]
This was an oversight, thank you for pointing it out, it has been resolved.
