### ISSUE TITLE
Invalid domains

### ISSUE THREAD

**Issue by solibov** [Clefspeare13/pornhosts#24]
https://github.com/Clefspeare13/pornhosts/blob/d9b61aec711f66959b1a6e70879c897b21d03ad7/0.0.0.0/hosts#L1525
https://github.com/Clefspeare13/pornhosts/blob/d9b61aec711f66959b1a6e70879c897b21d03ad7/0.0.0.0/hosts#L1527

**Comment by Clefspeare13** [comment]
Thanks for finding this!
