### ISSUE TITLE
hentai hosts

### ISSUE THREAD

**Issue by ghost** [Clefspeare13/pornhosts#25]
ahegao.online
akuma.moe
dlbooks.to
doujinantena.com
doujinshi.online
mangafap.com
porncomix.site
pururin.io
tabrin.com
tsumino.com
safebooru.org (?)
sukebei.nyaa.si
sukebei.pantsu.cat
www.hakihome.com
www.pornotube.com
www.thedoujin.com
www.voicehentai.com
yande.re

**Comment by solibov** [comment]
safebooru.org is an anime image search engine, and so there may be a tiny bit of hentai there, however most content on there seems fine. I personally wouldn't block sites like these.

**Comment by Clefspeare13** [comment]
Added these, and left safebooru out. However, if there is a forced safe search domain for safebooru that you're aware of, please let me know!
