### ISSUE TITLE
Porn sites

### ISSUE THREAD

**Issue by ghost** [Clefspeare13/pornhosts#29]
Here for you:

0.0.0.0 boysontube.com
0.0.0.0 boywankers.com
0.0.0.0 camboystube.net
0.0.0.0 favgayporn.com
0.0.0.0 gaypornium.com
0.0.0.0 queerdiary.com
0.0.0.0 manporn.xxx
0.0.0.0 milkyvideo.com
0.0.0.0 porkytube.com
0.0.0.0 sharethatboy.com
0.0.0.0 staxus.com
0.0.0.0 surfgayvideo.com
0.0.0.0 tubewankers.com
0.0.0.0 twinkhouse.com
0.0.0.0 twinkybf.com
0.0.0.0 www.19nitten.com
0.0.0.0 www.aaroncute.com
0.0.0.0 www.boyfriendtv.com
0.0.0.0 www.boysontube.com
0.0.0.0 www.boyvid.com
0.0.0.0 www.boyztube.com
0.0.0.0 www.czechhunter.com
0.0.0.0 www.debtdandy.com
0.0.0.0 www.gayboystube.com
0.0.0.0 www.gaybubble.com
0.0.0.0 www.gayhotmovies.com
0.0.0.0 www.gayporno.fm
0.0.0.0 www.gaysuperman.com
0.0.0.0 www.helixstudios.net
0.0.0.0 www.hornygayvideos.com
0.0.0.0 www.hotgaylist.xxx
0.0.0.0 www.hotgaytube.xxx
0.0.0.0 www.kizzboy.com
0.0.0.0 www.manhub.com
0.0.0.0 www.mansurfer.com
0.0.0.0 www.mikecute.com
0.0.0.0 www.surfgayvideo.com
0.0.0.0 www.teenboytwink.com
0.0.0.0 www.twink.xxx
0.0.0.0 www.youporngay.com

**Comment by Gonzo3** [comment]
And:

0.0.0.0 surfgayvideo.com

**Comment by Clefspeare13** [comment]
Added these, thanks!

**Comment by gianmaxfactor** [comment]
https://www.filmatiporno.xxx/bella-mora-sfondata-nella-figa-depilata-dal-fidanzato/&ved=0ahUKEwjLn6DB9vvbAhUBsRQKHSshDugQFggoMAE&usg=AOvVaw1AtmNVvcjse80oMfjamxa3

**Comment by gianmaxfactor** [comment]
http://it.foxtube.com/video/sasha-sala-riceve-una-sborrata-nella-sua-figa-depilata-7688.shtml

**Comment by gianmaxfactor** [comment]
http://it.foxtube.com/video/sasha-sala-riceve-una-sborrata-nella-sua-figa-depilata-7688.shtml

**Comment by gianmaxfactor** [comment]
https://filmatipornohd.com/video/incontri-al-buio-con-una-milf-tettona-arrapata-1058.html

**Comment by gianmaxfactor** [comment]
http://www.pornopizza.it/video/biondina-culona-scopata-al-buio-25353.html

**Comment by gianmaxfactor** [comment]
http://freshasianporn.com/it/secret/figa%20rasata/

**Comment by gianmaxfactor** [comment]
http://www.xtubo.xxx/video/incontro-al-buio/

**Comment by gianmaxfactor** [comment]
http://www.belloporno.com/search/si-Masturba/page1.html

**Comment by gianmaxfactor** [comment]
http://www.solopornoitaliano.xxx/con-la-figa-rasata-aperta-si-fa-sborrare-sul-fregna/
