### ISSUE TITLE
Merge my list into your list

### ISSUE THREAD

**Issue by DaniV5** [Clefspeare13/pornhosts#291]
https://github.com/DaniV5/hosts/blob/master/porn.txt
i made my own list now

**Comment by spirillen** [comment]
I would like to know why you have added your own repo if you like your submission added to either this or @clefspare13 projects??

Why not just take the contents of your PR's and paste the very same stuff as issues either here or at clefspares repo?? it's no joke, it is faster to me and probably you too as we will avoid rebasing

**Comment by DaniV5** [comment]
in the issues?

**Comment by spirillen** [comment]
> in the issues?

Yes as issues

**Comment by DaniV5** [comment]
explain better

**Comment by spirillen** [comment]
> explain better

Take the wonderful text/screen-dumps of you're PR's like https://github.com/DaniV5/hosts/pull/189 then put the vary same information, just as a issue of one of the projects either [here](https://github.com/Clefspeare13/pornhosts/issues/new/choose) or at <https://www.mypdns.org/project/view/10/> corresponding sub projects, the templates for information's input are almost equal each other anyhow.

**Comment by DaniV5** [comment]
ok

**Comment by DaniV5** [comment]
ok you can close that
