### ISSUE TITLE
fappeningbook.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#293]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
fappeningbook.com
www.fappeningbook.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![](https://i.ibb.co/r2tn8SH/Screenshot-Firefox-Beta-20201009-205101.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +36 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxODQxNTkzMTA1LCJ0IjoxNjAyMzQxNzk1fQ%3D%3D--38e44f9ffcd590da68399f2cd7589ae1f8f97b836e8a57d8c7b5577c9653e0ae&shared=true |
| +25 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/favicon-16x16.png` |
| +25 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/apple-touch-icon.png` |
| +24 | ##.pswp__button--share |  | fappeningbook.com |  | dom | `https://fappeningbook.com/jennifer-lawrence-nude/` |
| +24 | ##img[src*="counter.yadro.ru"] |  | fappeningbook.com |  | dom | `https://fappeningbook.com/jennifer-lawrence-nude/` |
| +24 | ##button[title="Share"] |  | fappeningbook.com |  | dom | `https://fappeningbook.com/jennifer-lawrence-nude/` |
| +24 | \|\|mc.yandex.ru^ | -- | fappeningbook.com | 3 | script | `https://mc.yandex.ru/metrika/tag.js` |
| +24 | \|\|yadro.ru^ | -- | fappeningbook.com | 3 | image | `https://counter.yadro.ru/hit?t44.1;rhttps%3A//fappeningbook.com/;s1920*1080*24;uhttps%3A//fappeningbook.com/jennifer-lawrence-nude/;hJennifer%20Lawrence%20Nude%2C%20Fappening%2C%20Sexy%20Photos%2C%20Uncensored%20-%20FappeningBook;0.8641988731349662` |
| +24 | \|\|googleapis.com^$important | -- | fappeningbook.com | 3 | css | `https://fonts.googleapis.com/css?family=Open+Sans` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/l/y/lynn-carlin/avatar.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/200x200/179.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/j/e/jenny-gabrielle/avatar.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/g/i/gina-bellman/avatar.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/l/i/lisa-collings/avatar.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/c/i/cicelys-zelies/avatar.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/a/b/abbey-hoes/avatar.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/200x200/578.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/200x200/334.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/a/n/anna-maria-kagerer/avatar.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/t/e/teresa-mak/avatar.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/c/a/carmen-montes/avatar.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/a/n/annamaria-demara/avatar.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/b/r/brigitte-maier/avatar.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/200x200/637.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/s/h/shane-lynch/avatar.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1496t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1497t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1498t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1499t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1500t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1501t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1502t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1503t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1504t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1505t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1506t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1507t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1508t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1509t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1510t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1511t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/164x164/1455.png` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1512t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1513t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/164x164/416.png` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1514t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1515t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1516t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1517t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/164x164/594.png` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1518t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1519t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1520t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1521t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/164x164/1332.png` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1522t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1523t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1524t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1525t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1526t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/164x164/1288.png` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1527t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1528t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1529t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/164x164/38.png` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1530t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1531t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/164x164/846.png` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1532t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1533t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1534t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1535t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1536t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/164x164/1869.png` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1537t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1538t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1539t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/164x164/265.png` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1540t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1541t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/164x164/1863.png` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1542t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1543t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1544t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/photos/j/e/jennifer-lawrence/2000/1545t.jpg` |
| +24 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/thefappening.png` |
| +24 |  |  | fappeningbook.com | 3 | script | `https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe-ui-default.min.js` |
| +24 |  |  | fappeningbook.com | 3 | script | `https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe.min.js` |
| +24 | \|\|googleapis.com^$important | -- | fappeningbook.com | 3 | css | `https://fonts.googleapis.com/css?family=Open+Sans` |
| +24 |  |  | fappeningbook.com | 1 | script | `https://fappeningbook.com/js/functions.js` |
| +24 |  |  | fappeningbook.com | 1 | script | `https://fappeningbook.com/js/jquery-3.2.1.js` |
| +23 |  |  | fappeningbook.com | 1 | doc | `https://fappeningbook.com/jennifer-lawrence-nude/` |
| +2 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/favicon-16x16.png` |
| +2 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/apple-touch-icon.png` |
| +2 | ##img[src*="counter.yadro.ru"] |  | fappeningbook.com |  | dom | `https://fappeningbook.com/` |
| +2 |  |  | fappeningbook.com | 1 | font | `https://fappeningbook.com/font/fonts/fontawesome-webfont.woff2?v=4.6.1` |
| +2 |  |  | fappeningbook.com | 3 | image | `https://vqcdn.b-cdn.net/images/PornGeek-Favicon.png` |
| +2 |  |  | fappeningbook.com | 3 | image | `https://thefappeningblog.com/wp-content/uploads/2017/09/porndude.png` |
| +2 | \|\|mc.yandex.ru^ | -- | fappeningbook.com | 3 | script | `https://mc.yandex.ru/metrika/tag.js` |
| +2 | \|\|yadro.ru^ | -- | fappeningbook.com | 3 | image | `https://counter.yadro.ru/hit?t44.1;r;s1920*1080*24;uhttps%3A//fappeningbook.com/;hNude%20Celebs%20Photos%20-%20FappeningBook;0.47431088417717515` |
| +1 | \|\|googleapis.com^$important | -- | fappeningbook.com | 3 | css | `https://fonts.googleapis.com/css?family=Open+Sans` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/new_leaks.png` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/l/a/laura-anderson/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/c/h/chloe-ferry/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/p/a/paige-turnah/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/k/a/katie-waissel/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/c/h/chrishell-stause/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/m/o/moran-atias/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/a/l/alexa-reynen/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/m/a/maja-krag/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/k/a/kanako-iioka/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/q/i/qingweiyingjie/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/assets/avatar.png` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/e/l/elizabeth-jolie/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/v/i/victoria-lee/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/s/a/sara-underwood/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/e/m/emma-watson/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/e/m/emily-ratajkowski/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/j/e/jennifer-lopez/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/k/i/kim-kardashian/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/a/r/ariel-winter/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/s/a/salma-hayek/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/b/e/bella-poarch/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/j/e/jennifer-lawrence/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/m/i/miley-cyrus/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/b/e/bella-thorne/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 1 | image | `https://fappeningbook.com/avatars/k/e/kendall-jenner/avatar.jpg` |
| +1 |  |  | fappeningbook.com | 3 | script | `https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe-ui-default.min.js` |
| +1 |  |  | fappeningbook.com | 3 | script | `https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe.min.js` |
| +1 |  |  | fappeningbook.com | 3 | css | `https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/default-skin/default-skin.min.css` |
| +1 |  |  | fappeningbook.com | 3 | css | `https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe.min.css` |
| +1 |  |  | fappeningbook.com | 1 | css | `https://fappeningbook.com/font/css/font-awesome.css` |
| +1 | \|\|googleapis.com^$important | -- | fappeningbook.com | 3 | css | `https://fonts.googleapis.com/css?family=Open+Sans` |
| +1 |  |  | fappeningbook.com | 1 | script | `https://fappeningbook.com/js/functions.js` |
| +1 |  |  | fappeningbook.com | 1 | script | `https://fappeningbook.com/js/jquery-3.2.1.js` |
| +1 |  |  | fappeningbook.com | 1 | css | `https://fappeningbook.com/css/styles.css?1` |
| +0 |  |  | fappeningbook.com | 1 | doc | `https://fappeningbook.com/` |
| +0 |  |  | `www.fappeningbook.com` | 3 | image | `https://lustfilms.imgix.net/gnX91VJftmbMTTrQCj1pZ3qOpMKTiLUhZGZfo0o4.jpeg?lossless=true&auto=enhance%2Ccompress%2Cformat&ar=10:3.75&fit=crop&crop=edges&auto=format&dpr=1&null` |
| +0 |  |  | `www.fappeningbook.com` | 1 | doc | `http://www.fappeningbook.com/` |
</details>
