### ISSUE TITLE
nudogram.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#294]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
nudogram.com
www.nudogram.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![](https://i.ibb.co/WcbQyD7/Screenshot-Firefox-Beta-20201010-061108.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +180 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxNTM2MjgwMjExLCJ0IjoxNjAyMzQxOTUyfQ%3D%3D--a7190232797767b38611165f4c4c3708d4731ff8ef726908dd39d011407a1d2b&shared=true |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/favicon.ico` |
| +156 |  |  | nudogram.com | 3 | script | `https://clerrrep.com/report/?type=push_notification&e=ReferenceError&m=p5KK%20is%20not%20defined&url=https%3A%2F%2Fnudogram.com%2F` |
| +156 | ##img[src*="counter.yadro.ru"] |  | nudogram.com |  | dom | `https://nudogram.com/` |
| +156 | ##.social-bookmarks |  | nudogram.com |  | dom | `https://nudogram.com/` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7431/180x135/1.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7433/180x135/1.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7434/180x135/1.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7435/180x135/1.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7436/180x135/1.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/6000/6948/180x135/1.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/6000/6509/180x135/1.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/3000/3531/180x135/1.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/4000/4612/180x135/1.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/0/896/180x135/1.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/0/688/180x135/2.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7432/180x135/1.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7125/180x135/1.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7360/180x135/1.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/6000/6957/180x135/1.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/3000/3300/180x135/1.jpg` |
| +156 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/4000/4619/180x135/1.jpg` |
| +156 | &action=js_stats& | -- | nudogram.com | 1 | image | `https://nudogram.com/?mode=async&action=js_stats&rand=1602342138092` |
| +155 | \|\|yadro.ru^ | -- | nudogram.com | 3 | image | `https://counter.yadro.ru/hit?t45.4;r;s1920*1080*24;uhttps%3A//nudogram.com/;hLeaked%20Nude%20Celebrities%20Videos%20The%20Fappening%20%7C%20Nudogram%20%uD83E%uDD29;0.6103293992381266` |
| +155 | \|\|mc.yandex.ru^ | -- | nudogram.com | 3 | script | `https://mc.yandex.ru/metrika/tag.js` |
| +155 | \|\|urtirepor.com^$3p | -- | nudogram.com | 3 | script | `https://urtirepor.com/i/npage/1762103/code.js` |
| +155 |  |  | nudogram.com | 1 | script | `https://nudogram.com/js/main.min.js?v=5.0` |
| +155 | \|\|theporndude.com/graphics/tpd-$3p | -- | nudogram.com | 3 | image | `https://theporndude.com/graphics/TPD-Favicon-Small-D-24px.png` |
| +155 | \|\|urtirepor.com^$3p | -- | nudogram.com | 3 | script | `https://urtirepor.com/i/npage/1762103/code.js` |
| +155 |  |  | nudogram.com | 3 | script | `https://douoblelimpup.com/pn21ywqw/z/sc/scssx/1701365/lib.js` |
| +155 | \|\|trawahdh2hd8nbvy09.com^$important | -- | nudogram.com | 3 | script | `https://trawahdh2hd8nbvy09.com/aas/r45d/vki/1723234/tghr.js` |
| +155 | \|\|googletagmanager.com/gtag/$3p | -- | nudogram.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-113981313-1` |
| +155 | ##+js(abort-on-property-read, decodeURI) |  | nudogram.com |  | dom | `https://nudogram.com/` |
| +155 | ##+js(abort-current-inline-script, decodeURI, decodeURIComponent) |  | nudogram.com |  | dom | `https://nudogram.com/` |
| +155 |  |  | nudogram.com | 1 | doc | `https://nudogram.com/` |
| +133 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +120 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxNTM2MjgwMjExLCJ0IjoxNjAyMzQxOTUyfQ%3D%3D--a7190232797767b38611165f4c4c3708d4731ff8ef726908dd39d011407a1d2b&shared=true |
| +115 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/6000/6957/180x135/5.jpg` |
| +115 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/6000/6957/180x135/4.jpg` |
| +114 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/6000/6957/180x135/3.jpg` |
| +112 |  |  | nudogram.com | 1 | image | `https://nudogram.com/contents/videos_screenshots/6000/6957/180x135/2.jpg` |
| +112 |  |  | nudogram.com | 1 | image | `https://nudogram.com/images/ico-later.png` |
| +112 |  |  | nudogram.com | 1 | image | `https://nudogram.com/images/ico-favourite.png` |
| +99 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +82 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +73 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +69 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +67 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +66 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +60 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxNTM2MjgwMjExLCJ0IjoxNjAyMzQxOTUyfQ%3D%3D--a7190232797767b38611165f4c4c3708d4731ff8ef726908dd39d011407a1d2b&shared=true |
| +6 | ##img[src*="counter.yadro.ru"] |  | nudogram.com |  | dom | `https://nudogram.com/` |
| +6 | ##.social-bookmarks |  | nudogram.com |  | dom | `https://nudogram.com/` |
| +5 |  |  | nudogram.com | 3 | script | `https://clerrrep.com/report/?type=push_notification&e=ReferenceError&m=p5KK%20is%20not%20defined&url=https%3A%2F%2Fnudogram.com%2F` |
| +5 | &action=js_stats& | -- | nudogram.com | 1 | image | `https://nudogram.com/?mode=async&action=js_stats&rand=1602341987788` |
| +5 |  |  | nudogram.com | 1 | image | `https://nudogram.com/favicon.ico` |
| +5 | \|\|yadro.ru^ | -- | nudogram.com | 3 | image | `https://counter.yadro.ru/hit?t45.4;r;s1920*1080*24;uhttps%3A//nudogram.com/;hLeaked%20Nude%20Celebrities%20Videos%20The%20Fappening%20%7C%20Nudogram%20%uD83E%uDD29;0.41346585174552086` |
| +5 | \|\|theporndude.com/graphics/tpd-$3p | -- | nudogram.com | 3 | image | `https://theporndude.com/graphics/TPD-Favicon-Small-D-24px.png` |
| +5 | \|\|mc.yandex.ru^ | -- | nudogram.com | 3 | script | `https://mc.yandex.ru/metrika/tag.js` |
| +5 | \|\|urtirepor.com^$3p | -- | nudogram.com | 3 | script | `https://urtirepor.com/i/npage/1762103/code.js` |
| +5 |  |  | nudogram.com | 1 | script | `https://nudogram.com/js/main.min.js?v=5.0` |
| +4 | \|\|theporndude.com/graphics/tpd-$3p | -- | nudogram.com | 3 | image | `https://theporndude.com/graphics/TPD-Favicon-Small-D-24px.png` |
| +4 | \|\|urtirepor.com^$3p | -- | nudogram.com | 3 | script | `https://urtirepor.com/i/npage/1762103/code.js` |
| +4 |  |  | nudogram.com | 3 | script | `https://douoblelimpup.com/pn21ywqw/z/sc/scssx/1701365/lib.js` |
| +4 |  |  | nudogram.com | 3 | script | `https://trawahdh2hd8nbvy09.com/aas/r45d/vki/1723234/tghr.js` |
| +4 |  |  | nudogram.com | 1 | css | `https://nudogram.com/styles/jquery.fancybox-metal.css?v=5.0` |
| +4 |  |  | nudogram.com | 1 | css | `https://nudogram.com/styles/all-responsive-metal.css?v=5.0` |
| +4 | \|\|googletagmanager.com/gtag/$3p | -- | nudogram.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-113981313-1` |
| +4 | ##+js(abort-on-property-read, decodeURI) |  | nudogram.com |  | dom | `https://nudogram.com/` |
| +4 | ##+js(abort-current-inline-script, decodeURI, decodeURIComponent) |  | nudogram.com |  | dom | `https://nudogram.com/` |
| +4 |  |  | nudogram.com | 1 | doc | `https://nudogram.com/` |
| +4 |  |  | nudogram.com | 1 | doc | `http://nudogram.com/` |
| +2 | ##img[src*="counter.yadro.ru"] |  | `www.nudogram.com` |  | dom | `http://www.nudogram.com/` |
| +2 | ##.social-bookmarks |  | `www.nudogram.com` |  | dom | `http://www.nudogram.com/` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7431/180x135/1.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7433/180x135/1.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7434/180x135/1.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7435/180x135/1.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7436/180x135/1.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/6000/6948/180x135/1.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/6000/6509/180x135/1.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/3000/3531/180x135/1.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/4000/4612/180x135/1.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/0/896/180x135/1.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/0/688/180x135/2.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7432/180x135/1.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7125/180x135/1.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/7000/7360/180x135/1.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/6000/6957/180x135/1.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/3000/3300/180x135/1.jpg` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/contents/videos_screenshots/4000/4619/180x135/1.jpg` |
| +2 | &action=js_stats& | -- | `www.nudogram.com` | 1 | image | `http://www.nudogram.com/?mode=async&action=js_stats&rand=1602341984872` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `http://www.nudogram.com/favicon.ico` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/images/ico-copy.png` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/images/ico-sort.png` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/images/ico-rating-negative.png` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/images/ico-rating-positive.png` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/images/bg-grey.gif` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/images/bg-nav.gif` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/images/btn-search.png` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/images/logo.png` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/images/bullet.png` |
| +2 | \|\|yadro.ru^ | -- | `www.nudogram.com` | 3 | image | `http://counter.yadro.ru/hit?t45.4;r;s1920*1080*24;uhttp%3A//www.nudogram.com/;hLeaked%20Nude%20Celebrities%20Videos%20The%20Fappening%20%7C%20Nudogram%20%uD83E%uDD29;0.922556809883078` |
| +2 | \|\|theporndude.com/graphics/tpd-$3p | -- | `www.nudogram.com` | 3 | image | `https://theporndude.com/graphics/TPD-Favicon-Small-D-24px.png` |
| +2 | \|\|mc.yandex.ru^ | -- | `www.nudogram.com` | 3 | script | `https://mc.yandex.ru/metrika/tag.js` |
| +2 |  |  | `www.nudogram.com` | 1 | image | `https://nudogram.com/images/pattern.gif` |
| +2 | \|\|urtirepor.com^$3p | -- | `www.nudogram.com` | 3 | script | `http://urtirepor.com/i/npage/1762103/code.js` |
| +2 |  |  | `www.nudogram.com` | 3 | script | `http://douoblelimpup.com/pn21ywqw/z/sc/scssx/1701365/lib.js` |
| +2 |  |  | `www.nudogram.com` | 3 | script | `http://trawahdh2hd8nbvy09.com/aas/r45d/vki/1723234/tghr.js` |
| +1 |  |  | `www.nudogram.com` | 1 | script | `https://nudogram.com/js/main.min.js?v=5.0` |
| +1 | \|\|theporndude.com/graphics/tpd-$3p | -- | `www.nudogram.com` | 3 | image | `https://theporndude.com/graphics/TPD-Favicon-Small-D-24px.png` |
| +1 | \|\|urtirepor.com^$3p | -- | `www.nudogram.com` | 3 | script | `http://urtirepor.com/i/npage/1762103/code.js` |
| +1 |  |  | `www.nudogram.com` | 3 | script | `http://douoblelimpup.com/pn21ywqw/z/sc/scssx/1701365/lib.js` |
| +1 |  |  | `www.nudogram.com` | 3 | script | `http://trawahdh2hd8nbvy09.com/aas/r45d/vki/1723234/tghr.js` |
| +1 |  |  | `www.nudogram.com` | 1 | css | `https://nudogram.com/styles/jquery.fancybox-metal.css?v=5.0` |
| +1 |  |  | `www.nudogram.com` | 1 | css | `https://nudogram.com/styles/all-responsive-metal.css?v=5.0` |
| +1 | \|\|googletagmanager.com/gtag/$3p | -- | `www.nudogram.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-113981313-1` |
| +1 | ##+js(abort-on-property-read, decodeURI) |  | `www.nudogram.com` |  | dom | `http://www.nudogram.com/` |
| +1 | ##+js(abort-current-inline-script, decodeURI, decodeURIComponent) |  | `www.nudogram.com` |  | dom | `http://www.nudogram.com/` |
| +1 |  |  | `www.nudogram.com` | 1 | doc | `http://www.nudogram.com/` |
| +0 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxNTM2MjgwMjExLCJ0IjoxNjAyMzQxOTUyfQ%3D%3D--a7190232797767b38611165f4c4c3708d4731ff8ef726908dd39d011407a1d2b&shared=true |
</details>
