### ISSUE TITLE
thefappening.plus

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#295]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
thefappening.plus
www.thefappening.plus
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![](https://i.ibb.co/551KRqx/Screenshot-Firefox-Beta-20201010-064659.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
You need to work a bit on the `www.` many of your submission this far are only using the `www.$domain` or the `$doamin`

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +110 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +93 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +84 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +80 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +80 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMTE4MTczODY2LCJ0IjoxNjAyMzQyMzA1fQ%3D%3D--4cb7268d4b8408ecd404ee6e3c1b0df5efb3c3169c522a98aa7f21fa7473e488&shared=true |
| +78 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +77 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +20 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMTE4MTczODY2LCJ0IjoxNjAyMzQyMzA1fQ%3D%3D--4cb7268d4b8408ecd404ee6e3c1b0df5efb3c3169c522a98aa7f21fa7473e488&shared=true |
| +3 |  |  | thefappening.plus | 1 | image | `https://thefappening.plus/wp-content/uploads/2020/09/Suranne-Jones-Nude-The-Fappening-2020-TheFappening.plus-1-669x272.jpg` |
| +3 | ##.fusion-social-network-icon |  | thefappening.plus |  | dom | `https://thefappening.plus/` |
| +2 | ##img[src*="counter.yadro.ru"] |  | thefappening.plus |  | dom | `https://thefappening.plus/` |
| +2 | `##[href^="https://www.facebook.com"]` |  | thefappening.plus |  | dom | `https://thefappening.plus/` |
| +2 |  |  | thefappening.plus | 1 | image | `https://thefappening.plus/wp-content/uploads/2020/09/Tone-Damli-Nude-The-Fappening-2020-TheFappening.plus-1-669x272.jpg` |
| +2 |  |  | thefappening.plus | 1 | image | `https://thefappening.plus/favicon.ico` |
| +2 | /avada-to-top. | -- | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/general/avada-to-top.js?ver=5.7.1` |
| +2 |  |  | thefappening.plus | 1 | font | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/fonts/icomoon/icomoon.woff` |
| +2 | \|\|fonts.gstatic.com^$important | -- | thefappening.plus | 3 | font | `https://fonts.gstatic.com/s/ptsans/v12/jizfRExUiTo99u79B_mh0O6tKA.ttf` |
| +2 | \|\|fonts.gstatic.com^$important | -- | thefappening.plus | 3 | font | `https://fonts.gstatic.com/s/anticslab/v9/bWt97fPFfRzkCa9Jlp6IacVcWQ.ttf` |
| +2 | \|\|fonts.gstatic.com^$important | -- | thefappening.plus | 3 | font | `https://fonts.gstatic.com/s/ptsans/v12/jizaRExUiTo99u79D0KEwA.ttf` |
| +2 |  |  | thefappening.plus | 3 | image | `https://avada.theme-fusion.com/wp-content/uploads/2014/12/ptb_bkgd.png` |
| +2 | \|\|yadro.ru^ | -- | thefappening.plus | 3 | image | `https://counter.yadro.ru/hit?t44.1;r;s1920*1080*24;uhttps%3A//thefappening.plus/;hThe%20Fappening%20Plus%20%u2013%20Nude%20Celebrity%20Photos;0.5098141472065384` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-includes/js/wp-embed.min.js?ver=5.4.2` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/lazy-loading-responsive-images/js/lazysizes.min.js?ver=5.4.2` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-core/js/min/avada-fusion-slider.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/general/avada-elastic-slider.js?ver=5.7.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/library/jquery.elasticslider.js?ver=5.7.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/general/avada-fade.js?ver=5.7.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/general/avada-drop-down.js?ver=5.7.1` |
| +1 | /avada-to-top. | -- | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/general/avada-to-top.js?ver=5.7.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/library/jquery.toTop.js?ver=1.2` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/general/avada-tabs-widget.js?ver=5.7.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/library/jquery.sticky-kit.js?ver=5.7.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/general/avada-sidebars.js?ver=5.7.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/general/avada-select.js?ver=5.7.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/general/avada-scrollspy.js?ver=5.7.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/general/avada-quantity.js?ver=5.7.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/general/avada-general-footer.js?ver=5.7.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/general/avada-comments.js?ver=5.7.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/library/bootstrap.scrollspy.js?ver=3.3.2` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-responsive-typography.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-scroll-to-anchor.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/general/avada-menu.js?ver=5.7.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/general/avada-header.js?ver=5.7.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-ie1011.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-general-global.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-button.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-blog.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-sharing-box.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-tooltip.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-popover.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-flexslider.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-carousel.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-alert.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.touchSwipe.js?ver=1.6.6` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.placeholder.js?ver=2.0.7` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.hoverflow.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.flexslider.js?ver=2.2.2` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.easing.js?ver=1.3` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.carouFredSel.js?ver=6.2.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/bootstrap.popover.js?ver=3.3.5` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/bootstrap.tooltip.js?ver=3.3.5` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/assets/min/js/general/avada-vertical-menu-widget.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.hoverintent.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-video.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/vimeoPlayer.js?ver=2.2.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-container.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/fusion-video-bg.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/fusion-parallax.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.requestAnimationFrame.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.fade.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-counters-box.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-chart.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/library/Chart.js?ver=2.7.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-tabs.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/bootstrap.tab.js?ver=3.1.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/bootstrap.transition.js?ver=3.3.6` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-countdown.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/library/jquery.countdown.js?ver=1.0` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-toggles.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/bootstrap.collapse.js?ver=3.1.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-title.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-syntax-highlighter.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-content-boxes.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-google-map.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.fusion_maps.js?ver=2.2.2` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-events.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-counters-circle.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.easyPieChart.js?ver=2.1.7` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/library/jquery.countTo.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-column.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-equal-heights.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-column-bg-image.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-testimonials.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.cycle.js?ver=3.0.3` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-gallery.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-image-before-after.js?ver=1.0` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/library/jquery.event.move.js?ver=2.0` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-flip-boxes.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-animations.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/cssua.js?ver=2.1.28` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-recent-posts.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-modal.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/bootstrap.modal.js?ver=3.1.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-builder/assets/js/min/general/fusion-progress.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.appear.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-waypoints.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.waypoints.js?ver=2.0.3` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-core/js/min/avada-portfolio.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/packery.js?ver=2.0.0` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/imagesLoaded.js?ver=3.1.8` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion-lightbox.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.mousewheel.js?ver=3.0.6` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.ilightbox.js?ver=2.2.3` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/fusion-video-general.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.fitvids.js?ver=1.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/modernizr.js?ver=3.3.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/plugins/fusion-core/js/min/avada-faqs.js?ver=1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.infinitescroll.js?ver=2.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-content/themes/Avada/includes/lib/assets/min/js/library/isotope.js?ver=3.0.4` |
| +1 |  |  | thefappening.plus | 1 | image | `https://thefappening.plus/wp-content/uploads/2018/11/thefappening_logo.png` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp` |
| +1 |  |  | thefappening.plus | 1 | css | `https://thefappening.plus/wp-content/uploads/fusion-styles/2c6264f8a7d0d7c4881a018e3a7cd880.min.css?ver=5.4.2` |
| +1 |  |  | thefappening.plus | 1 | css | `https://thefappening.plus/wp-content/themes/Avada/assets/css/style.min.css?ver=5.7.1` |
| +1 |  |  | thefappening.plus | 1 | css | `https://thefappening.plus/wp-includes/css/dist/block-library/style.min.css?ver=5.4.2` |
| +1 |  |  | thefappening.plus | 1 | script | `https://thefappening.plus/wp-includes/js/wp-emoji-release.min.js?ver=5.4.2` |
| +1 |  |  | thefappening.plus | 1 | doc | `https://thefappening.plus/` |
| +0 |  |  | `www.thefappening.plus` | 1 | doc | `http://www.thefappening.plus/` |
</details>
