### ISSUE TITLE
thefappeningnews.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#297]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
thefappeningnews.com
www.thefappeningnews.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![](https://i.ibb.co/BrmYDrk/Screenshot-Firefox-Beta-20201010-082051.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +3 | ##img[src*="counter.yadro.ru"] |  | thefappeningnews.com |  | dom | `https://thefappeningnews.com/` |
| +3 | `##a[href^="https://www.linkedin.com/shareArticle?"]` |  | thefappeningnews.com |  | dom | `https://thefappeningnews.com/` |
| +3 | `##a[href^="https://www.facebook.com/sharer.php?"]` |  | thefappeningnews.com |  | dom | `https://thefappeningnews.com/` |
| +3 | `##a[href^="https://twitter.com/share?"]` |  | thefappeningnews.com |  | dom | `https://thefappeningnews.com/` |
| +3 | `##a[href^="https://pinterest.com/pin/create/"]` |  | thefappeningnews.com |  | dom | `https://thefappeningnews.com/` |
| +3 | `##[href^="https://www.facebook.com"]` |  | thefappeningnews.com |  | dom | `https://thefappeningnews.com/` |
| +3 | `##[href^="https://twitter.com"]` |  | thefappeningnews.com |  | dom | `https://thefappeningnews.com/` |
| +3 | ##.socials |  | thefappeningnews.com |  | dom | `https://thefappeningnews.com/` |
| +3 | ##.social-icon |  | thefappeningnews.com |  | dom | `https://thefappeningnews.com/` |
| +2 |  |  | thefappeningnews.com | 1 | image | `https://thefappeningnews.com/favicon-16x16.png` |
| +2 |  |  | thefappeningnews.com | 1 | image | `https://thefappeningnews.com/apple-touch-icon.png` |
| +1 |  |  | thefappeningnews.com | 1 | font | `https://thefappeningnews.com/wp-content/themes/olsen-light/fonts/fontawesome-webfont.woff2?v=4.7.0` |
| +1 | \|\|yadro.ru^ | -- | thefappeningnews.com | 3 | image | `https://counter.yadro.ru/hit?t44.1;r;s1920*1080*24;uhttps%3A//thefappeningnews.com/;hTheFappening%20News%20%u2013%20Leaked%20iCloud%20Nude%20Celebrity%20Photos;0.7387308584152315` |
| +1 | \|\|googleapis.com^$important | -- | thefappeningnews.com | 3 | css | `https://fonts.googleapis.com/css?family=Lora%3A400%2C700%2C400italic%2C700italic%7CLato%3A400%2C400italic%2C700%2C700italic&ver=5.4.2` |
| +1 |  |  | thefappeningnews.com | 1 | script | `https://thefappeningnews.com/wp-includes/js/wp-emoji-release.min.js?ver=5.4.2` |
| +1 |  |  | thefappeningnews.com | 1 | script | `https://thefappeningnews.com/wp-includes/js/wp-embed.min.js?ver=5.4.2` |
| +1 |  |  | thefappeningnews.com | 1 | script | `https://thefappeningnews.com/wp-content/themes/olsen-light/js/scripts.js?ver=1.3.1` |
| +1 |  |  | thefappeningnews.com | 1 | script | `https://thefappeningnews.com/wp-content/themes/olsen-light/js/jquery.magnific-popup.js?ver=1.0.0` |
| +1 |  |  | thefappeningnews.com | 1 | script | `https://thefappeningnews.com/wp-content/themes/olsen-light/js/jquery.fitvids.js?ver=1.1` |
| +1 |  |  | thefappeningnews.com | 1 | script | `https://thefappeningnews.com/wp-content/themes/olsen-light/js/jquery.mmenu.autoheight.js?ver=5.2.0` |
| +1 |  |  | thefappeningnews.com | 1 | script | `https://thefappeningnews.com/wp-content/themes/olsen-light/js/jquery.mmenu.navbars.js?ver=5.2.0` |
| +1 |  |  | thefappeningnews.com | 1 | script | `https://thefappeningnews.com/wp-content/themes/olsen-light/js/jquery.mmenu.offcanvas.js?ver=5.2.0` |
| +1 |  |  | thefappeningnews.com | 1 | script | `https://thefappeningnews.com/wp-content/themes/olsen-light/js/jquery.mmenu.oncanvas.js?ver=5.2.0` |
| +1 |  |  | thefappeningnews.com | 1 | script | `https://thefappeningnews.com/wp-content/themes/olsen-light/js/slick.js?ver=1.5.7` |
| +1 |  |  | thefappeningnews.com | 1 | script | `https://thefappeningnews.com/wp-content/themes/olsen-light/js/jquery.matchHeight.js?ver=1.3.1` |
| +1 |  |  | thefappeningnews.com | 1 | script | `https://thefappeningnews.com/wp-content/themes/olsen-light/js/superfish.js?ver=1.7.5` |
| +1 |  |  | thefappeningnews.com | 1 | image | `https://thefappeningnews.com/wp-content/uploads/2020/09/Amber-Heard-Naked-TheFappening-2020-TheFappeningNews.com-6-665x435.jpg` |
| +1 |  |  | thefappeningnews.com | 1 | image | `https://thefappeningnews.com/wp-content/uploads/2020/09/Bella-Thorne-Naked-TheFappening-2020-TheFappeningNews.com-2-665x435.jpg` |
| +1 |  |  | thefappeningnews.com | 1 | image | `https://thefappeningnews.com/wp-content/uploads/2020/09/Celeste-Bouchard-Naked-TheFappening-2020-TheFappeningNews.com-3-665x435.jpg` |
| +1 |  |  | thefappeningnews.com | 1 | image | `https://thefappeningnews.com/wp-content/uploads/2020/09/Chantel-Jeffries-Naked-TheFappening-2020-TheFappeningNews.com-5-665x435.jpg` |
| +1 |  |  | thefappeningnews.com | 1 | image | `https://thefappeningnews.com/wp-content/uploads/2020/10/Catherine-Tyldesley-Naked-TheFappening-2020-TheFappeningNews.com-2-665x435.jpg` |
| +1 |  |  | thefappeningnews.com | 1 | image | `https://thefappeningnews.com/wp-content/uploads/2020/10/Amber-Heard-Naked-TheFappening-2020-TheFappeningNews.com-8-665x435.jpg` |
| +1 |  |  | thefappeningnews.com | 1 | image | `https://thefappeningnews.com/wp-content/uploads/2020/10/Bella-Thorne-Naked-TheFappening-2020-TheFappeningNews.com-1-665x435.jpg` |
| +1 |  |  | thefappeningnews.com | 1 | image | `https://thefappeningnews.com/wp-content/uploads/2020/10/Aiza-Dolmatova-Naked-TheFappening-2020-TheFappeningNews.com-1-665x435.jpg` |
| +1 |  |  | thefappeningnews.com | 1 | image | `https://thefappeningnews.com/wp-content/uploads/2020/10/Jackie-Figueroa-Naked-TheFappening-2020-TheFappeningNews.com-3-665x435.jpg` |
| +1 |  |  | thefappeningnews.com | 1 | script | `https://thefappeningnews.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1` |
| +1 |  |  | thefappeningnews.com | 1 | script | `https://thefappeningnews.com/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp` |
| +1 |  |  | thefappeningnews.com | 1 | css | `https://thefappeningnews.com/wp-content/themes/olsen-light/style.css?ver=1.3.1` |
| +1 |  |  | thefappeningnews.com | 1 | css | `https://thefappeningnews.com/wp-content/themes/olsen-light/css/mmenu.css?ver=5.2.0` |
| +1 |  |  | thefappeningnews.com | 1 | css | `https://thefappeningnews.com/wp-content/themes/olsen-light/css/slick.css?ver=1.5.7` |
| +1 |  |  | thefappeningnews.com | 1 | css | `https://thefappeningnews.com/wp-content/themes/olsen-light/css/magnific.css?ver=1.0.0` |
| +1 |  |  | thefappeningnews.com | 1 | css | `https://thefappeningnews.com/wp-content/themes/olsen-light/css/font-awesome.css?ver=4.7.0` |
| +1 |  |  | thefappeningnews.com | 1 | css | `https://thefappeningnews.com/wp-content/themes/olsen-light/common/css/global.css?ver=1.3.1` |
| +1 |  |  | thefappeningnews.com | 1 | css | `https://thefappeningnews.com/wp-content/themes/olsen-light/css/base.css?ver=1.3.1` |
| +1 | \|\|googleapis.com^$important | -- | thefappeningnews.com | 3 | css | `https://fonts.googleapis.com/css?family=Lora%3A400%2C700%2C400italic%2C700italic%7CLato%3A400%2C400italic%2C700%2C700italic&ver=5.4.2` |
| +1 |  |  | thefappeningnews.com | 1 | css | `https://thefappeningnews.com/wp-includes/css/dist/block-library/style.min.css?ver=5.4.2` |
| +1 |  |  | thefappeningnews.com | 1 | doc | `https://thefappeningnews.com/` |
| +0 |  |  | `www.thefappeningnews.com` | 1 | doc | `https://www.thefappeningnews.com/` |
| +0 |  |  | `www.thefappeningnews.com` | 1 | doc | `http://www.thefappeningnews.com/` |
</details>
