### ISSUE TITLE
fapopedia.net

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#298]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
fapopedia.net
www.fapopedia.net
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![](https://i.ibb.co/N96kWSm/Screenshot-Firefox-Beta-20201010-082634.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +202 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/favicon-16x16.png` |
| +202 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/apple-touch-icon.png` |
| +201 | ##img[src*="counter.yadro.ru"] |  | fapopedia.net |  | dom | `https://fapopedia.net/augusttaylorxxx-nude-leaks/` |
| +201 | \|\|chaturbate.com/in/?track=$subdocument,3p | -- | fapopedia.net | 3 | frame | `https://chaturbate.com/in/?track=fapo&tour=x1Rd&campaign=jmmW7&c=6&p=1&gender=x` |
| +201 | \|\|yadro.ru^ | -- | fapopedia.net | 3 | image | `https://counter.yadro.ru/hit?t44.6;rhttps%3A//fapopedia.net/;s1920*1080*24;uhttps%3A//fapopedia.net/augusttaylorxxx-nude-leaks/;hAugusttaylorxxx%20Nude%20OnlyFans%20Leaks%202020%20-%20Fapopedia;0.11331213276523155` |
| +201 | \|\|googleapis.com^$important | -- | fapopedia.net | 3 | css | `https://fonts.googleapis.com/css2?family=Saira+Condensed&display=swap` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/avatars/o/l/olivia_brower/avatar.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/avatars/j/u/justyna/avatar.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/avatars/n/i/nicole_harrison/avatar.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/avatars/c/h/chloe_baldwin/avatar.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/avatars/o/l/olesya_parvatova/avatar.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/avatars/n/i/nina_josephine/avatar.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/avatars/n/e/neldoll/avatar.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/avatars/p/r/princesspineappletv/avatar.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/avatars/k/a/katarina_vesna/avatar.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/avatars/w/i/wifeluvsposing1/avatar.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0051.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0052.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0053.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0054.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0055.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0056.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0057.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0058.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0059.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0060.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0061.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0062.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0063.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0064.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0065.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0066.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0067.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0068.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0069.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0070.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0071.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0072.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0073.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0074.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0075.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0076.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0077.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0078.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0079.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0080.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0081.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0082.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0083.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0084.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0085.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0086.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0087.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0088.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0089.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0090.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0091.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0092.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0093.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0094.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0095.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0096.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0097.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0098.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0099.jpg` |
| +201 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/photos/a/u/augusttaylorxxx/1000//t_0100.jpg` |
| +201 |  |  | fapopedia.net | 3 | script | `https://cdn18685953.ahacdn.me/tag/20200909/tag.src.js` |
| +201 |  |  | fapopedia.net | 3 | script | `https://cdn18685953.ahacdn.me/tag/20200909/settings.src.js` |
| +201 |  |  | fapopedia.net | 1 | script | `https://fapopedia.net/js/functions.js` |
| +201 |  |  | fapopedia.net | 1 | script | `https://fapopedia.net/js/jquery.min.js` |
| +201 |  |  | fapopedia.net | 1 | css | `https://fapopedia.net/css/import.css` |
| +201 |  |  | fapopedia.net | 1 | doc | `https://fapopedia.net/augusttaylorxxx-nude-leaks/` |
| +190 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyNDQzNjAyMjk3LCJ0IjoxNjAyMzQ0MDQ3fQ%3D%3D--d79abd101d508167bf07ed099b33a9c43d6e94cb39427ae3383abaf013ff5b74&shared=true |
| +178 | \|\|chaturbate.com/in/?track=$subdocument,3p | -- | fapopedia.net | 3 | frame | `https://chaturbate.com/in/?track=fapo&tour=x1Rd&campaign=jmmW7&c=6&p=1&gender=x` |
| +175 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/favicon-16x16.png` |
| +175 |  |  | fapopedia.net | 1 | image | `https://fapopedia.net/apple-touch-icon.png` |
| +175 | ##img[src*="counter.yadro.ru"] |  | fapopedia.net |  | dom | `https://fapopedia.net/` |
| +175 |  |  | fapopedia.net | 1 | font | `https://fapopedia.net/font/fonts/la-solid-900.woff2` |
| +175 |  |  | fapopedia.net | 1 | font | `https://fapopedia.net/font/fonts/la-regular-400.woff2` |
| +175 | \|\|yadro.ru^ | -- | fapopedia.net | 3 | image | `https://counter.yadro.ru/hit?t44.6;r;s1920*1080*24;uhttps%3A//fapopedia.net/;hLeaked%20Onlyfans%2C%20Patreon%2C%20MYMfans%2C%20Private%20Snapchat%20Models%20-%20Fapopedia;0.32663375359935753` |
| +175 |  |  | fapopedia.net | 1 | css | `https://fapopedia.net/font/css/line-awesome.min.css` |
| +175 | \|\|googleapis.com^$important | -- | fapopedia.net | 3 | css | `https://fonts.googleapis.com/css2?family=Saira+Condensed&display=swap` |
| +175 |  |  | fapopedia.net | 3 | script | `https://cdn18685953.ahacdn.me/tag/20200909/tag.src.js` |
| +175 |  |  | fapopedia.net | 3 | script | `https://cdn18685953.ahacdn.me/tag/20200909/settings.src.js` |
| +175 |  |  | fapopedia.net | 1 | script | `https://fapopedia.net/js/functions.js` |
| +175 |  |  | fapopedia.net | 1 | script | `https://fapopedia.net/js/jquery.min.js` |
| +175 |  |  | fapopedia.net | 1 | css | `https://fapopedia.net/css/import.css` |
| +175 |  |  | fapopedia.net | 1 | css | `https://fapopedia.net/css/styles.css` |
| +175 |  |  | fapopedia.net | 1 | doc | `https://fapopedia.net/` |
| +175 |  |  | fapopedia.net | 1 | doc | `http://fapopedia.net/` |
| +174 |  |  | `www.fapopedia.net` | 1 | image | `https://www.fapopedia.net/favicon-16x16.png` |
| +174 |  |  | `www.fapopedia.net` | 1 | image | `https://www.fapopedia.net/apple-touch-icon.png` |
| +174 |  |  | `www.fapopedia.net` | 1 | font | `https://fapopedia.net/font/fonts/la-solid-900.ttf` |
| +173 |  |  | `www.fapopedia.net` | 1 | font | `https://fapopedia.net/font/fonts/la-regular-400.ttf` |
| +173 |  |  | `www.fapopedia.net` | 1 | font | `https://fapopedia.net/font/fonts/la-solid-900.woff` |
| +173 |  |  | `www.fapopedia.net` | 1 | font | `https://fapopedia.net/font/fonts/la-regular-400.woff` |
| +173 | ##img[src*="counter.yadro.ru"] |  | `www.fapopedia.net` |  | dom | `https://www.fapopedia.net/` |
| +173 |  |  | `www.fapopedia.net` | 1 | font | `https://fapopedia.net/font/fonts/la-solid-900.woff2` |
| +173 |  |  | `www.fapopedia.net` | 1 | font | `https://fapopedia.net/font/fonts/la-regular-400.woff2` |
| +173 | \|\|yadro.ru^ | -- | `www.fapopedia.net` | 3 | image | `https://counter.yadro.ru/hit?t44.6;r;s1920*1080*24;uhttps%3A//www.fapopedia.net/;hLeaked%20Onlyfans%2C%20Patreon%2C%20MYMfans%2C%20Private%20Snapchat%20Models%20-%20Fapopedia;0.09609673485073378` |
| +173 |  |  | `www.fapopedia.net` | 1 | css | `https://fapopedia.net/font/css/line-awesome.min.css` |
| +173 | \|\|googleapis.com^$important | -- | `www.fapopedia.net` | 3 | css | `https://fonts.googleapis.com/css2?family=Saira+Condensed&display=swap` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/v/i/vicky_stark/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/o/c/octokuro/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/s/o/solazola/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/d/a/darshelle_stevens/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/m/a/marisa_papen/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/l/u/luna-lotton/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/s/a/sara_jean_underwood/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/b/e/bella-thorne/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/a/m/amouranth/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/m/a/mackzjones/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/r/u/ruhhvxo/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/c/h/chelsea_fergo/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/a/n/angie_griffin/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/a/s/ashley-barbie/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/m/i/miyamelody/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/j/i/jinx_asmr/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/a/b/abigale_mandler/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/p/r/princess_kidaa/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/d/e/demi_rose/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/n/i/nicole-young/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/m/a/maitland_ward/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/s/a/sarah_hyland/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/e/m/emira_kowalska/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/m/e/meg_turney/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/m/i/miley_cyrus/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/k/a/kat_wonders/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/j/e/jenny_scordamaglia/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/l/e/lety_does_stuff/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/c/h/christina_khalil/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/d/e/demi_lovato/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/b/e/belle_delphine/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/r/o/rose_mcgowan/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/j/o/joey_fisher/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/j/a/jadeteen/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/d/e/delilah_parillo/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/f/i/fiamurrph/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/v/i/viviana_robba/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/e/m/emily_ratajkowski/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/l/a/lauren_summer/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/v/y/vyvan_le/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/n/i/ninapinkxo/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/b/a/barbiesinsxxx/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/j/a/jaraka-mitchell/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/assets/avatar.png` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/h/a/hailey-queen/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/a/s/asiansquatgirl/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/b/l/blue-dreams/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/i/a/iamanissa/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/m/a/mamielia/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 1 | image | `https://fapopedia.net/avatars/a/u/augusttaylorxxx/avatar.jpg` |
| +172 |  |  | `www.fapopedia.net` | 3 | script | `https://cdn18685953.ahacdn.me/tag/20200909/tag.src.js` |
| +172 |  |  | `www.fapopedia.net` | 3 | script | `https://cdn18685953.ahacdn.me/tag/20200909/settings.src.js` |
| +172 |  |  | `www.fapopedia.net` | 1 | script | `https://fapopedia.net/js/functions.js` |
| +172 |  |  | `www.fapopedia.net` | 1 | script | `https://fapopedia.net/js/jquery.min.js` |
| +172 |  |  | `www.fapopedia.net` | 1 | css | `https://fapopedia.net/css/import.css` |
| +172 |  |  | `www.fapopedia.net` | 1 | css | `https://fapopedia.net/css/styles.css` |
| +172 |  |  | `www.fapopedia.net` | 1 | doc | `https://www.fapopedia.net/` |
| +171 |  |  | `www.fapopedia.net` | 1 | doc | `http://www.fapopedia.net/` |
| +155 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +154 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +151 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +151 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +135 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +135 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +130 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMDMxMTA4MzI3LCJ0IjoxNjAyMzQ0MDIwfQ%3D%3D--f946cfc979684bce1dd9e47e27b6e7548c82cadc01a64d9df92eb38846e15607&shared=true |
| +128 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +128 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +92 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +69 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMjQ0MDU3OTMyLCJ0IjoxNjAyMzQzNzY3fQ%3D%3D--f30eeed04496097aa87d08ee271e06e5cb95f92724bf91483c693712e99a1824&shared=true |
| +32 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +9 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMjQ0MDU3OTMyLCJ0IjoxNjAyMzQzNzY3fQ%3D%3D--f30eeed04496097aa87d08ee271e06e5cb95f92724bf91483c693712e99a1824&shared=true |
| +0 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
</details>
