### ISSUE TITLE
fappeninggram.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#299]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
fappeninggram.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![](https://i.ibb.co/0jkh63c/Screenshot-Firefox-Beta-20201010-083012.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/hosts.txt)?
- [X] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +21 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozODI3NDQ4NDcwLCJ0IjoxNjAyMzQ0MjQ0fQ%3D%3D--0cd6f21961ef6b59d2692bf1d53ba0ea8473fce532c510373d9d5b4080f600f5&shared=true |
| +17 |  |  | fappeninggram.com | 1 | image | `https://fappeninggram.com/favicon-16x16.png` |
| +17 |  |  | fappeninggram.com | 1 | image | `https://fappeninggram.com/apple-touch-icon.png` |
| +17 | ##img[src*="counter.yadro.ru"] |  | fappeninggram.com |  | dom | `https://fappeninggram.com/` |
| +16 |  |  | fappeninggram.com | 1 | font | `https://fappeninggram.com/font/fonts/la-brands-400.woff2` |
| +16 |  |  | fappeninggram.com | 1 | font | `https://fappeninggram.com/font/fonts/la-solid-900.woff2` |
| +16 | \|\|yadro.ru^ | -- | fappeninggram.com | 3 | image | `https://counter.yadro.ru/hit?t44.1;r;s1920*1080*24;uhttps%3A//fappeninggram.com/;hNude%20Leaked%20Celebs%20-%20FappeningGram;0.8784433335456537` |
| +16 |  |  | fappeninggram.com | 1 | css | `https://fappeninggram.com/font/css/line-awesome.min.css` |
| +16 | \|\|googleapis.com^$important | -- | fappeninggram.com | 3 | css | `https://fonts.googleapis.com/css?family=Barlow+Condensed:400,700&display=swap` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/sarah-hyland/sarah-hyland-nude35_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/bella-thorne/bella-thorne-nude3_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/katie-cassidy/katie-cassidy-nude1_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/alexa-bliss/alexa-bliss-nude11_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/rihanna/rihanna-nude16_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/anna-kendrick/anna-kendrick-nude63_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/nicole-scherzinger/nicole-scherzinger-nude8_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/elizabeth-olsen/elizabeth-olsen-nude9_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/cara-delevingne/cara-delevingne-nude1_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/ellie-goulding/ellie-goulding-nude59_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/victoria-justice/victoria-justice-nude21_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/sophie-turner/sophie-turner-nude4_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/kaley-cuoco/kaley-cuoco-nude21_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/margot-robbie/margot-robbie-nude4_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/laura-bach/laura-bach-nude31_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/hayden-panettiere/hayden-panettiere-nude22_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/lili-reinhart/lili-reinhart-nude2_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/emily-ratajkowski/emily-ratajkowski-nude100_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/alison-brie/alison-brie-nude18_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/miley-cyrus/miley-cyrus-nude64_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/demi-lovato/demi-lovato-nude21_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/megan-fox/megan-fox-nude5_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/reese-witherspoon/reese-witherspoon-nude45_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/taylor-swift/taylor-swift-nude1_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/kate-upton/kate-upton-nude59_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/vanessa-hudgens/vanessa-hudgens-nude6_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/katy-perry/katy-perry-nude3_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/emma-watson/emma-watson-nude68_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/paige-spiranac/paige-spiranac-nude5_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | image | `https://cdn.fappeninggram.com/photos/jennifer-lawrence/jennifer-lawrence-nude84_m.jpg` |
| +16 |  |  | fappeninggram.com | 1 | script | `https://fappeninggram.com/js/functions.js` |
| +16 |  |  | fappeninggram.com | 1 | script | `https://fappeninggram.com/js/jquery.min.js` |
| +16 |  |  | fappeninggram.com | 1 | css | `https://fappeninggram.com/css/import.css` |
| +16 |  |  | fappeninggram.com | 1 | css | `https://fappeninggram.com/css/styles.css` |
| +15 |  |  | fappeninggram.com | 1 | doc | `https://fappeninggram.com/` |
| +14 |  |  | `www.fappeninggram.com` | 1 | doc | `https://www.fappeninggram.com/` |
| +13 |  |  | `www.fappeninggram.com` | 1 | doc | `http://www.fappeninggram.com/` |
| +4 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +4 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +0 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +0 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
</details>
