### ISSUE TITLE
thefappeningstars.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#300]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
thefappeningstars.com
www.thefappeningstars.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-113054](https://user-images.githubusercontent.com/38778536/95641131-3ef90980-0aec-11eb-8fbf-2d227b201e2b.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +17 |  |  | thefappeningstars.com | 1 | image | `https://thefappeningstars.com/favicon-16x16.png` |
| +17 |  |  | thefappeningstars.com | 1 | image | `https://thefappeningstars.com/apple-touch-icon.png` |
| +17 | ##img[src*="counter.yadro.ru"] |  | thefappeningstars.com |  | dom | `https://thefappeningstars.com/` |
| +17 |  |  | thefappeningstars.com | 1 | font | `https://thefappeningstars.com/wp-content/themes/tortuga/assets/fonts/open-sans-v15-latin-ext_latin-700.woff2` |
| +17 |  |  | thefappeningstars.com | 1 | font | `https://thefappeningstars.com/wp-content/themes/tortuga/assets/fonts/titillium-web-v6-latin-ext_latin-regular.woff2` |
| +17 |  |  | thefappeningstars.com | 1 | font | `https://thefappeningstars.com/wp-content/themes/tortuga/assets/fonts/open-sans-v15-latin-ext_latin-regular.woff2` |
| +17 | \|\|yadro.ru^ | -- | thefappeningstars.com | 3 | image | `https://counter.yadro.ru/hit?t44.1;r;s1920*1080*24;uhttps%3A//thefappeningstars.com/;hThe%20Fappening%20Stars%20%u2013%20Nude%20Celebs%20Leaks%20Sex%20Tapes;0.5528472851541429` |
| +16 |  |  | thefappeningstars.com | 1 | script | `https://thefappeningstars.com/wp-includes/js/wp-embed.min.js?ver=5.4.2` |
| +16 |  |  | thefappeningstars.com | 1 | image | `https://thefappeningstars.com/wp-content/uploads/2020/09/ln1.jpg` |
| +16 |  |  | thefappeningstars.com | 1 | image | `https://thefappeningstars.com/wp-content/uploads/2020/09/Catherine-Tyldesley-Nude-Leaks-TheFappening-2020-TheFappeningStars.com-1-900x400.jpg` |
| +16 |  |  | thefappeningstars.com | 1 | image | `https://thefappeningstars.com/wp-content/uploads/2020/09/Jessamyn-Duke-Nude-Leaks-TheFappening-2020-TheFappeningStars.com-1-900x400.jpg` |
| +16 |  |  | thefappeningstars.com | 1 | image | `https://thefappeningstars.com/wp-content/uploads/2020/09/Suki-Waterhouse-Nude-Leaks-TheFappening-2020-TheFappeningStars.com-1-900x400.jpg` |
| +16 |  |  | thefappeningstars.com | 1 | image | `https://thefappeningstars.com/wp-content/uploads/2020/10/Stacey-Dooley-Nude-Leaks-TheFappening-2020-TheFappeningStars.com-1-900x400.jpg` |
| +16 |  |  | thefappeningstars.com | 1 | image | `https://thefappeningstars.com/wp-content/uploads/2020/10/Jackie-Figueroa-Nude-Leaks-TheFappening-2020-TheFappeningStars.com-2-900x400.jpg` |
| +16 |  |  | thefappeningstars.com | 1 | image | `https://thefappeningstars.com/wp-content/uploads/2020/10/Aiza-Dolmatova-Nude-Leaks-TheFappening-2020-TheFappeningStars.com-1-900x400.jpg` |
| +16 |  |  | thefappeningstars.com | 1 | image | `https://thefappeningstars.com/wp-content/uploads/2020/10/Lily-Mo-Sheen-Nude-Leaks-TheFappening-2020-TheFappeningStars.com-1-900x400.jpg` |
| +16 |  |  | thefappeningstars.com | 1 | image | `https://thefappeningstars.com/wp-content/uploads/2020/10/Tone-Damli-Nude-Leaks-TheFappening-2020-TheFappeningStars.com-3-900x400.jpg` |
| +16 |  |  | thefappeningstars.com | 1 | image | `https://thefappeningstars.com/wp-content/uploads/2020/10/Jennifer-Lauret-Nude-Leaks-TheFappening-2020-TheFappeningStars.com-5-900x400.jpg` |
| +16 |  |  | thefappeningstars.com | 1 | script | `https://thefappeningstars.com/wp-content/themes/tortuga/assets/js/navigation.js?ver=20160719` |
| +16 |  |  | thefappeningstars.com | 1 | script | `https://thefappeningstars.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1` |
| +16 |  |  | thefappeningstars.com | 1 | script | `https://thefappeningstars.com/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp` |
| +16 |  |  | thefappeningstars.com | 1 | css | `https://thefappeningstars.com/wp-content/themes/tortuga/assets/genericons/genericons.css?ver=3.4.1` |
| +16 |  |  | thefappeningstars.com | 1 | css | `https://thefappeningstars.com/wp-content/themes/tortuga/style.css?ver=1.8.4` |
| +16 |  |  | thefappeningstars.com | 1 | css | `https://thefappeningstars.com/wp-includes/css/dist/block-library/style.min.css?ver=5.4.2` |
| +16 |  |  | thefappeningstars.com | 1 | css | `https://thefappeningstars.com/wp-content/themes/tortuga/assets/css/custom-fonts.css?ver=20180413` |
| +16 |  |  | thefappeningstars.com | 1 | script | `https://thefappeningstars.com/wp-includes/js/wp-emoji-release.min.js?ver=5.4.2` |
| +16 |  |  | thefappeningstars.com | 1 | doc | `https://thefappeningstars.com/` |
| +16 |  |  | `www.thefappeningstars.com` | 1 | doc | `https://www.thefappeningstars.com/` |
| +16 |  |  | `www.thefappeningstars.com` | 1 | doc | `http://www.thefappeningstars.com/` |
| +3 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +2 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +1 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +0 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
</details>
