### ISSUE TITLE
watchmyexgf.net

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#301]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
www.watchmyexgf.net
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![](https://i.ibb.co/dQ74Nr4/Screenshot-Firefox-Beta-20201010-084541.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/hosts.txt)?
- [X] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +26 | ##.go-to-top |  | `www.watchmyexgf.net` |  | dom | `https://www.watchmyexgf.net/` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/65000/65015/290x170/1.jpg` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/64000/64970/290x170/3.jpg` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/64000/64955/290x170/3.jpg` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/65000/65017/290x170/4.jpg` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/65000/65098/290x170/1.jpg` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/64000/64948/290x170/1.jpg` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/65000/65070/290x170/2.jpg` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/64000/64973/290x170/1.jpg` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/65000/65105/290x170/1.jpg` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/65000/65021/290x170/2.jpg` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/65000/65038/290x170/4.jpg` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/65000/65064/290x170/1.jpg` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/65000/65051/290x170/4.jpg` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/65000/65046/290x170/8.jpg` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/65000/65005/290x170/3.jpg` |
| +26 |  |  | `www.watchmyexgf.net` | 3 | image | `https://watchmyexgf.good-cdn.com/contents/videos_screenshots/65000/65056/290x170/1.jpg` |
| +26 | &action=js_stats& | -- | `www.watchmyexgf.net` | 1 | image | `https://www.watchmyexgf.net/?mode=async&action=js_stats&rand=1602344332466` |
| +26 |  |  | `www.watchmyexgf.net` | 1 | image | `https://www.watchmyexgf.net/favicon.ico` |
| +25 | google-analytics.com/analytics.js | << | `www.watchmyexgf.net` |  | script | `https://www.google-analytics.com/analytics.js` |
| +25 | \|\|google-analytics.com^ | -- | `www.watchmyexgf.net` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +25 |  |  | `www.watchmyexgf.net` | 1 | script | `https://www.watchmyexgf.net/js/z123.js` |
| +25 |  |  | `www.watchmyexgf.net` | 3 | script | `https://watchmyexgf.good-cdn.com/js/scripts.min.js` |
| +25 | \|\|exosrv.com^ | -- | `www.watchmyexgf.net` | 3 | script | `https://ads.exosrv.com/ads.js` |
| +25 | \|\|watchmyexgf.net/*.gif$image | -- | `www.watchmyexgf.net` | 1 | image | `https://watchmyexgf.net/images/load.gif` |
| +25 | \|\|exoprsdds.com^ | -- | `www.watchmyexgf.net` | 3 | script | `https://exoprsdds.com/pn07uscr/f/tr/zavbn/1572777/lib.js` |
| +25 | ##+js(window.open-defuser) |  | `www.watchmyexgf.net` |  | dom | `https://www.watchmyexgf.net/` |
| +25 | ##+js(abort-on-property-read, prPuShown) |  | `www.watchmyexgf.net` |  | dom | `https://www.watchmyexgf.net/` |
| +24 |  |  | `www.watchmyexgf.net` | 1 | doc | `https://www.watchmyexgf.net/` |
| +24 | ##.go-to-top |  | `www.watchmyexgf.net` |  | dom | `https://www.watchmyexgf.net/` |
| +23 |  |  | watchmyexgf.net | 1 | doc | `http://watchmyexgf.net/` |
| +21 |  |  | `www.watchmyexgf.net` | 1 | font | `https://www.watchmyexgf.net/webfonts/fa-brands-400.woff2` |
| +21 |  |  | `www.watchmyexgf.net` | 1 | script | `https://www.watchmyexgf.net/js/z123.js` |
| +21 |  |  | `www.watchmyexgf.net` | 3 | script | `https://watchmyexgf.good-cdn.com/js/scripts.min.js` |
| +21 |  |  | `www.watchmyexgf.net` | 1 | image | `https://www.watchmyexgf.net/images/88x31_RTA-5042-1996-1400-1577-RTA-G-VERIFIED.png` |
| +21 |  |  | `www.watchmyexgf.net` | 1 | image | `https://www.watchmyexgf.net/z/gf.jpg` |
| +21 | \|\|exosrv.com^ | -- | `www.watchmyexgf.net` | 3 | script | `https://ads.exosrv.com/ads.js` |
| +21 | \|\|watchmyexgf.net/*.gif$image | -- | `www.watchmyexgf.net` | 1 | image | `https://watchmyexgf.net/images/load.gif` |
| +21 |  |  | `www.watchmyexgf.net` | 1 | font | `https://www.watchmyexgf.net/webfonts/fa-regular-400.woff2` |
| +21 |  |  | `www.watchmyexgf.net` | 1 | font | `https://www.watchmyexgf.net/webfonts/fa-solid-900.woff2` |
| +21 | google-analytics.com/analytics.js | << | `www.watchmyexgf.net` |  | script | `https://www.google-analytics.com/analytics.js` |
| +21 | \|\|google-analytics.com^ | -- | `www.watchmyexgf.net` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +21 |  |  | `www.watchmyexgf.net` | 1 | image | `https://www.watchmyexgf.net/images/logo.png?3` |
| +21 | \|\|exoprsdds.com^ | -- | `www.watchmyexgf.net` | 3 | script | `https://exoprsdds.com/pn07uscr/f/tr/zavbn/1572777/lib.js` |
| +21 | ##+js(window.open-defuser) |  | `www.watchmyexgf.net` |  | dom | `https://www.watchmyexgf.net/` |
| +21 | ##+js(abort-on-property-read, prPuShown) |  | `www.watchmyexgf.net` |  | dom | `https://www.watchmyexgf.net/` |
| +19 |  |  | `www.watchmyexgf.net` | 1 | doc | `https://www.watchmyexgf.net/` |
| +17 |  |  | `www.watchmyexgf.net` | 1 | doc | `http://www.watchmyexgf.net/` |
| +16 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozNTE4MjEwNjM2LCJ0IjoxNjAyMzQ0MzA5fQ%3D%3D--44087d8a3c63c1c680e9b4204d75eabf922efea33ea4b35c0a8f160434057ad4&shared=true |
| +4 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +3 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +1 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +0 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
</details>
