### ISSUE TITLE
fappenism.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#302]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
fappenism.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![](https://i.ibb.co/SyhWq3R/Screenshot-Firefox-Beta-20201010-085331.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/hosts.txt)?
- [X] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +62 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozOTc5Nzg3Mjg3LCJ0IjoxNjAyMzQ0MTY4fQ%3D%3D--81ec98141667bc1c3015f664c2d8a9b25a043629a16c9b985022c96af43abc97&shared=true |
| +39 |  |  | fappenism.com | 1 | image | `https://fappenism.com/wp-content/uploads/2020/10/Stacey-Dooley-Nude-TheFappening-2020-Fappenism.com-1-624x468.jpg` |
| +39 |  |  | fappenism.com | 1 | image | `https://fappenism.com/favicon-16x16.png` |
| +39 |  |  | fappenism.com | 1 | image | `https://fappenism.com/apple-touch-icon.png` |
| +39 |  |  | fappenism.com | 1 | image | `https://fappenism.com/wp-content/plugins/a3-lazy-load/assets/css/loading.gif` |
| +38 |  |  | fappenism.com | 1 | script | `https://fappenism.com/wp-includes/js/wp-embed.min.js?ver=5.4.2` |
| +38 |  |  | fappenism.com | 1 | script | `https://fappenism.com/wp-content/plugins/a3-lazy-load/assets/js/jquery.lazyloadxt.extend.js?ver=2.3.3` |
| +38 |  |  | fappenism.com | 1 | script | `https://fappenism.com/wp-content/plugins/a3-lazy-load/assets/js/jquery.lazyloadxt.srcset.min.js?ver=2.3.3` |
| +38 |  |  | fappenism.com | 1 | script | `https://fappenism.com/wp-content/plugins/a3-lazy-load/assets/js/jquery.lazyloadxt.extra.min.js?ver=2.3.3` |
| +38 |  |  | fappenism.com | 1 | script | `https://fappenism.com/wp-content/themes/twentytwelve/js/navigation.js?ver=20140711` |
| +38 |  |  | fappenism.com | 1 | image | `https://fappenism.com/wp-content/plugins/a3-lazy-load/assets/images/lazy_placeholder.gif` |
| +38 |  |  | fappenism.com | 1 | script | `https://fappenism.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1` |
| +38 |  |  | fappenism.com | 1 | script | `https://fappenism.com/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp` |
| +38 |  |  | fappenism.com | 1 | css | `https://fappenism.com/wp-content/plugins/a3-lazy-load/assets/css/jquery.lazyloadxt.spinner.css?ver=5.4.2` |
| +38 |  |  | fappenism.com | 1 | css | `https://fappenism.com/wp-content/themes/twentytwelve/css/blocks.css?ver=20181230` |
| +38 |  |  | fappenism.com | 1 | css | `https://fappenism.com/wp-content/themes/twentytwelve/style.css?ver=5.4.2` |
| +38 | \|\|googleapis.com^$important | -- | fappenism.com | 3 | css | `https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700&subset=latin,latin-ext` |
| +38 |  |  | fappenism.com | 1 | css | `https://fappenism.com/wp-includes/css/dist/block-library/theme.min.css?ver=5.4.2` |
| +38 |  |  | fappenism.com | 1 | css | `https://fappenism.com/wp-includes/css/dist/block-library/style.min.css?ver=5.4.2` |
| +38 |  |  | fappenism.com | 1 | script | `https://fappenism.com/wp-includes/js/wp-emoji-release.min.js?ver=5.4.2` |
| +38 |  |  | fappenism.com | 1 | doc | `https://fappenism.com/` |
| +37 |  |  | `www.fappenism.com` | 1 | doc | `https://www.fappenism.com/` |
| +36 |  |  | `www.fappenism.com` | 1 | doc | `http://www.fappenism.com/` |
| +29 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +29 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +25 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +25 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +16 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +7 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +3 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +2 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyNDQzNjAyMjk3LCJ0IjoxNjAyMzQ0MDQ3fQ%3D%3D--d79abd101d508167bf07ed099b33a9c43d6e94cb39427ae3383abaf013ff5b74&shared=true |
| +1 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +0 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
</details>
