### ISSUE TITLE
thefappening.in

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#303]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
thefappening.in
www.thefappening.in
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![](https://i.ibb.co/svgtV76/Screenshot-Firefox-Beta-20201010-090234.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +19 |  |  | thefappening.in | 1 | image | `https://thefappening.in/wp-content/uploads/2020/10/Nathalie-Cassegrain-Nude-The-Fappening-Blog-4-1024x1536-1.jpg` |
| +17 |  |  | thefappening.in | 1 | image | `https://thefappening.in/sprojectnew2/icons.png` |
| +16 | ##img[src*="counter.yadro.ru"] |  | thefappening.in |  | dom | `https://thefappening.in/` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/wp-content/uploads/2020/10/Carlotta-Champagne-Nude-The-Fappening-Blog-3-1024x1536-1.jpg` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/wp-content/uploads/2019/05/new_leaked.png` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/favicon.ico` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/sprojectnew2/thumbs/p89.png` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/sprojectnew2/thumbs/jenny-mccarthy/name.png` |
| +16 |  |  | thefappening.in | 3 | image | `https://thefappeningcelebs.com/sprojectnew2/thumbs/jenny-mccarthy/jenny-mccarthy-2.jpg` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/sprojectnew2/thumbs/p91.png` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/sprojectnew2/thumbs/nadya-suleman/name.png` |
| +16 |  |  | thefappening.in | 3 | image | `https://thefappeningcelebs.com/sprojectnew2/thumbs/nadya-suleman/nadya-suleman-5.jpg` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/sprojectnew2/thumbs/p74.png` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/sprojectnew2/thumbs/laura-ramsey/name.png` |
| +16 |  |  | thefappening.in | 3 | image | `https://thefappeningcelebs.com/sprojectnew2/thumbs/laura-ramsey/laura-ramsey-5.jpg` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/sprojectnew2/thumbs/p70.png` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/sprojectnew2/thumbs/leighton-meester/name.png` |
| +16 |  |  | thefappening.in | 3 | image | `https://thefappeningcelebs.com/sprojectnew2/thumbs/leighton-meester/leighton-meester-5.jpg` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/sprojectnew2/thumbs/p79.png` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/sprojectnew2/thumbs/elizabeth-ruiz/name.png` |
| +16 |  |  | thefappening.in | 3 | image | `https://thefappeningcelebs.com/sprojectnew2/thumbs/elizabeth-ruiz/elizabeth-ruiz-2.jpg` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/sprojectnew2/thumbs/p84.png` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/sprojectnew2/thumbs/emily-browning/name.png` |
| +16 |  |  | thefappening.in | 3 | image | `https://thefappeningcelebs.com/sprojectnew2/thumbs/emily-browning/emily-browning-3.jpg` |
| +16 |  |  | thefappening.in | 1 | script | `https://thefappening.in/sprojectnew2/thumbchange.js` |
| +16 | \|\|googleapis.com^$important | -- | thefappening.in | 3 | script | `https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js` |
| +16 |  |  | thefappening.in | 1 | css | `https://thefappening.in/sprojectnew2/all.css` |
| +16 | \|\|googleapis.com^$important | -- | thefappening.in | 3 | css | `https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700` |
| +16 | \|\|googleapis.com^$important | -- | thefappening.in | 3 | css | `https://fonts.googleapis.com/css?family=Asap:700` |
| +16 |  |  | thefappening.in | 1 | image | `https://thefappening.in/icloudhack9.png` |
| +16 |  |  | thefappening.in | 3 | image | `https://fappeningbook.com/assets/favicon-16x16.png` |
| +16 |  |  | thefappening.in | 3 | image | `https://vqcdn.b-cdn.net/images/PornGeek-Favicon.png` |
| +16 |  |  | thefappening.in | 3 | image | `https://thefappeningblog.com/wp-content/uploads/2017/09/porndude.png` |
| +16 | \|\|mc.yandex.ru^ | -- | thefappening.in | 3 | script | `https://mc.yandex.ru/metrika/tag.js` |
| +16 | \|\|yadro.ru^ | -- | thefappening.in | 3 | image | `https://counter.yadro.ru/hit?t44.1;r;s1920*1080*24;uhttps%3A//thefappening.in/;hTheFappening%20Celebs%20%7C%20Celebrity%20Leaked%20Nude%20Photos%20Videos;0.6377800581637789` |
| +16 |  |  | thefappening.in | 1 | frame | `https://thefappening.in/sprojectnew2/footer_multi.php` |
| +16 |  |  | thefappening.in | 1 | frame | `https://thefappening.in/icloud9.html` |
| +16 |  |  | thefappening.in | 1 | script | `https://thefappening.in/wp-includes/js/wp-embed.min.js?ver=5.4.2` |
| +16 |  |  | thefappening.in | 1 | script | `https://thefappening.in/wp-content/plugins/lazy-loading-responsive-images/js/lazysizes.min.js?ver=5.4.2` |
| +16 |  |  | thefappening.in | 1 | script | `https://thefappening.in/wp-content/themes/twentytwelve/js/navigation.js?ver=20140711` |
| +16 |  |  | thefappening.in | 1 | script | `https://thefappening.in/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1` |
| +16 |  |  | thefappening.in | 1 | script | `https://thefappening.in/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp` |
| +16 |  |  | thefappening.in | 1 | css | `https://thefappening.in/wp-content/themes/twentytwelve/style.css?ver=5.4.2` |
| +16 | \|\|googleapis.com^$important | -- | thefappening.in | 3 | css | `https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700&subset=latin,latin-ext` |
| +16 |  |  | thefappening.in | 1 | css | `https://thefappening.in/wp-includes/css/dist/block-library/style.min.css?ver=5.4.2` |
| +16 |  |  | thefappening.in | 1 | script | `https://thefappening.in/wp-includes/js/wp-emoji-release.min.js?ver=5.4.2` |
| +15 |  |  | thefappening.in | 1 | doc | `https://thefappening.in/` |
| +15 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMjQ0MDU3OTMyLCJ0IjoxNjAyMzQzNzY3fQ%3D%3D--f30eeed04496097aa87d08ee271e06e5cb95f92724bf91483c693712e99a1824&shared=true |
| +15 |  |  | `www.thefappening.in` | 1 | doc | `https://www.thefappening.in/` |
| +15 |  |  | `www.thefappening.in` | 1 | doc | `http://www.thefappening.in/` |
| +0 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +0 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
</details>
