### ISSUE TITLE
thefappenist.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#304]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
thefappening.com
www.thefappening.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot-Firefox-Beta-20201010-091955](https://user-images.githubusercontent.com/38778536/95639330-c2fac380-0ae3-11eb-8ba3-6cfe1944196b.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
Dead domain, hijacked by [parklogic.com](https://www.mypdns.org/T181)

whois thefappening.com
   Domain Name: THEFAPPENING.COM
   Registry Domain ID: 2335262004_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.namebright.com
   Registrar URL: http://www.NameBright.com
   Updated Date: 2020-01-26T00:37:01Z
   Creation Date: 2018-11-21T19:29:23Z
   Registry Expiry Date: 2020-11-21T19:29:23Z
   Registrar: DropCatch.com 805 LLC
   Registrar IANA ID: 2564
   Registrar Abuse Contact Email:
   Registrar Abuse Contact Phone:
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Name Server: NS1.PARKLOGIC.COM
   Name Server: NS2.PARKLOGIC.COM
   Name Server: NS3.PARKLOGIC.COM
