### ISSUE TITLE
thecamdude.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#305]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
thecamdude.com
www.thecamdude.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-102011](https://user-images.githubusercontent.com/38778536/95639143-233d3580-0ae3-11eb-9c92-b973d039ba34.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +36 | `##[href^="https://twitter.com"]` |  | thecamdude.com |  | dom | `https://thecamdude.com/` |
| +36 | ##.twtr |  | thecamdude.com |  | dom | `https://thecamdude.com/` |
| +36 | ##.backtop |  | thecamdude.com |  | dom | `https://thecamdude.com/` |
| +35 |  |  | thecamdude.com | 1 | image | `https://thecamdude.com/favicon-16x16.png` |
| +35 |  |  | thecamdude.com | 1 | image | `https://thecamdude.com/android-icon-192x192.png` |
| +35 | \|\|cloudflareinsights.com^$3p | -- | thecamdude.com | 3 | script | `https://static.cloudflareinsights.com/beacon.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +35 | google-analytics.com/analytics.js | << | thecamdude.com |  | script | `https://www.google-analytics.com/analytics.js` |
| +35 | \|\|google-analytics.com^ | -- | thecamdude.com | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +35 | \|\|cloudflareinsights.com^$3p | -- | thecamdude.com | 3 | script | `https://static.cloudflareinsights.com/beacon.min.js` |
| +35 |  |  | thecamdude.com | 1 | script | `https://thecamdude.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js` |
| +35 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +34 |  |  | thecamdude.com | 1 | doc | `https://thecamdude.com/` |
| +34 |  |  | `www.thecamdude.com` | 1 | doc | `https://www.thecamdude.com/` |
| +34 |  |  | `www.thecamdude.com` | 1 | doc | `http://www.thecamdude.com/` |
| +11 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozNTQ0ODUxOTUwLCJ0IjoxNjAyMzQzNjM4fQ%3D%3D--94d03b82844e68d811a39dd55399538db391657bcc9b6377a418c712358ad04a&shared=true |
| +3 | ##.backtop |  | thecamdude.com |  | dom | `https://thecamdude.com/` |
| +3 | ##.twtr |  | thecamdude.com |  | dom | `https://thecamdude.com/` |
| +2 | `##[href^="https://twitter.com"]` |  | thecamdude.com |  | dom | `https://thecamdude.com/` |
| +2 |  |  | thecamdude.com | 1 | image | `https://thecamdude.com/favicon-16x16.png` |
| +2 |  |  | thecamdude.com | 1 | image | `https://thecamdude.com/android-icon-192x192.png` |
| +2 | \|\|cloudflareinsights.com^$3p | -- | thecamdude.com | 3 | script | `https://static.cloudflareinsights.com/beacon.min.js` |
| +2 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +1 | \|\|cloudflareinsights.com^$3p | -- | thecamdude.com | 3 | script | `https://static.cloudflareinsights.com/beacon.min.js` |
| +1 |  |  | thecamdude.com | 1 | script | `https://thecamdude.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js` |
| +1 |  |  | thecamdude.com | 1 | image | `https://thecamdude.com/wp-content/themes/camdude-wp/assets/images/bg-desc.png` |
| +1 |  |  | thecamdude.com | 1 | image | `https://thecamdude.com/wp-content/themes/camdude-wp/assets/images/bg-mainc.png` |
| +1 |  |  | thecamdude.com | 1 | image | `https://thecamdude.com/wp-content/themes/camdude-wp/assets/images/src-btn.png` |
| +1 |  |  | thecamdude.com | 1 | image | `https://thecamdude.com/wp-content/themes/camdude-wp/assets/images/bg-hdr-btm.png` |
| +1 |  |  | thecamdude.com | 1 | image | `https://thecamdude.com/wp-content/themes/camdude-wp/assets/images/bg-hdr-top.png` |
| +1 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +1 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +1 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +1 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +1 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +1 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +1 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +1 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +1 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +1 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +1 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +1 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +1 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +1 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +1 | google-analytics.com/analytics.js | << | thecamdude.com |  | script | `https://www.google-analytics.com/analytics.js` |
| +1 | \|\|google-analytics.com^ | -- | thecamdude.com | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +1 | \|\|cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket-loader.min.js$script,important | -- | thecamdude.com | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +0 |  |  | thecamdude.com | 1 | doc | `https://thecamdude.com/` |
| +0 |  |  | thecamdude.com | 1 | doc | `http://thecamdude.com/` |
</details>
