### ISSUE TITLE
fusker.xxx

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#306]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
fusker.xxx
www.fusker.xxx
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-114253](https://user-images.githubusercontent.com/38778536/95641420-f0e50580-0aed-11eb-8386-6c3426bda2cb.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
Confirmation by URI `https://www.fusker.xxx/en/?lid=2692886`

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +441 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +437 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +435 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +434 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +398 |  |  | `www.fusker.xxx` | 1 | xhr | `https://www.fusker.xxx/en/ajax` |
| +398 | google-analytics.com/analytics.js | << | `www.fusker.xxx` |  | script | `https://www.google-analytics.com/analytics.js` |
| +398 | \|\|google-analytics.com^ | -- | `www.fusker.xxx` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +397 | \|\|mc.yandex.ru^ | -- | `www.fusker.xxx` | 3 | script | `https://mc.yandex.ru/metrika/tag.js` |
| +397 | \|\|jads.co^$3p | -- | `www.fusker.xxx` | 3 | script | `https://poweredby.jads.co/js/jads.js` |
| +397 | \|\|jads.co^$3p | -- | `www.fusker.xxx` | 3 | script | `https://poweredby.jads.co/js/jfc.js` |
| +397 | \|\|jads.co^$3p | -- | `www.fusker.xxx` | 3 | script | `https://poweredby.jads.co/js/jads.js` |
| +397 |  |  | `www.fusker.xxx` | 3 | image | `https://www.sensual-x.be/wp-content/uploads/2020/10/DSC_4665.jpg` |
| +397 | \|\|jads.co^$3p | -- | `www.fusker.xxx` | 3 | script | `https://poweredby.jads.co/js/jfc.js` |
| +397 | \|\|jads.co^$3p | -- | `www.fusker.xxx` | 3 | script | `https://poweredby.jads.co/js/jads.js` |
| +397 |  |  | `www.fusker.xxx` | 1 | script | `https://www.fusker.xxx/js/main.js?v=1596975168` |
| +397 |  |  | `www.fusker.xxx` | 1 | doc | `https://www.fusker.xxx/en/?lid=2692886` |
| +388 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxNDIxNTQ4NjcxLCJ0IjoxNjAyMzQzNDk0fQ%3D%3D--eb00a886ff2aed08627d0e4968d6a24e7d59b86f53ff81c1061e555426f8dc25&shared=true |
| +358 |  |  | `www.fusker.xxx` | 1 | xhr | `https://www.fusker.xxx/en/ajax` |
| +358 | google-analytics.com/analytics.js | << | `www.fusker.xxx` |  | script | `https://www.google-analytics.com/analytics.js` |
| +358 | \|\|google-analytics.com^ | -- | `www.fusker.xxx` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +358 | \|\|mc.yandex.ru^ | -- | `www.fusker.xxx` | 3 | script | `https://mc.yandex.ru/metrika/tag.js` |
| +358 | \|\|jads.co^$3p | -- | `www.fusker.xxx` | 3 | script | `https://poweredby.jads.co/js/jads.js` |
| +358 | \|\|jads.co^$3p | -- | `www.fusker.xxx` | 3 | script | `https://poweredby.jads.co/js/jfc.js` |
| +358 | \|\|jads.co^$3p | -- | `www.fusker.xxx` | 3 | script | `https://poweredby.jads.co/js/jads.js` |
| +358 | \|\|jads.co^$3p | -- | `www.fusker.xxx` | 3 | script | `https://poweredby.jads.co/js/jfc.js` |
| +358 | \|\|jads.co^$3p | -- | `www.fusker.xxx` | 3 | script | `https://poweredby.jads.co/js/jads.js` |
| +358 |  |  | `www.fusker.xxx` | 1 | script | `https://www.fusker.xxx/js/main.js?v=1596975168` |
| +358 |  |  | `www.fusker.xxx` | 1 | doc | `https://www.fusker.xxx/en/` |
| +358 |  |  | fusker.xxx | 1 | doc | `http://fusker.xxx/en/` |
| +357 |  |  | fusker.xxx | 1 | doc | `http://fusker.xxx/` |
| +353 |  |  | `www.fusker.xxx` | 1 | xhr | `https://www.fusker.xxx/en/ajax` |
| +353 | google-analytics.com/analytics.js | << | `www.fusker.xxx` |  | script | `https://www.google-analytics.com/analytics.js` |
| +353 | \|\|google-analytics.com^ | -- | `www.fusker.xxx` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +353 |  |  | `www.fusker.xxx` | 1 | image | `https://fusker.xxx/images/lupa1.gif` |
| +353 |  |  | `www.fusker.xxx` | 1 | image | `https://fusker.xxx/images/Warning.gif` |
| +353 | \|\|mc.yandex.ru^ | -- | `www.fusker.xxx` | 3 | script | `https://mc.yandex.ru/metrika/tag.js` |
| +353 | \|\|jads.co^$3p | -- | `www.fusker.xxx` | 3 | script | `https://poweredby.jads.co/js/jads.js` |
| +353 | \|\|jads.co^$3p | -- | `www.fusker.xxx` | 3 | script | `https://poweredby.jads.co/js/jfc.js` |
| +353 | \|\|jads.co^$3p | -- | `www.fusker.xxx` | 3 | script | `https://poweredby.jads.co/js/jads.js` |
| +353 |  |  | `www.fusker.xxx` | 1 | image | `https://www.fusker.xxx/themes/fusker/images/logo.gif` |
| +353 | \|\|jads.co^$3p | -- | `www.fusker.xxx` | 3 | script | `https://poweredby.jads.co/js/jfc.js` |
| +353 | \|\|jads.co^$3p | -- | `www.fusker.xxx` | 3 | script | `https://poweredby.jads.co/js/jads.js` |
| +353 |  |  | `www.fusker.xxx` | 1 | css | `https://www.fusker.xxx/css/styles.css?v=1596975168` |
| +353 |  |  | `www.fusker.xxx` | 1 | script | `https://www.fusker.xxx/js/main.js?v=1596975168` |
| +352 |  |  | `www.fusker.xxx` | 1 | doc | `https://www.fusker.xxx/en/` |
| +351 |  |  | `www.fusker.xxx` | 1 | doc | `http://www.fusker.xxx/en/` |
| +351 |  |  | `www.fusker.xxx` | 1 | doc | `http://www.fusker.xxx/` |
| +341 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +340 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +328 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozMzc3NzY4Njc4LCJ0IjoxNjAyMzQzMTU0fQ%3D%3D--4f0f4ee1474f41f1c071ed0119675dbc3da532aeb583c96855ba47e5a4767a7b&shared=true |
| +280 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +268 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozMzc3NzY4Njc4LCJ0IjoxNjAyMzQzMTU0fQ%3D%3D--4f0f4ee1474f41f1c071ed0119675dbc3da532aeb583c96855ba47e5a4767a7b&shared=true |
| +220 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +208 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozMzc3NzY4Njc4LCJ0IjoxNjAyMzQzMTU0fQ%3D%3D--4f0f4ee1474f41f1c071ed0119675dbc3da532aeb583c96855ba47e5a4767a7b&shared=true |
| +160 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +148 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozMzc3NzY4Njc4LCJ0IjoxNjAyMzQzMTU0fQ%3D%3D--4f0f4ee1474f41f1c071ed0119675dbc3da532aeb583c96855ba47e5a4767a7b&shared=true |
| +126 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +109 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +100 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +96 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +94 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +93 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +88 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozMzc3NzY4Njc4LCJ0IjoxNjAyMzQzMTU0fQ%3D%3D--4f0f4ee1474f41f1c071ed0119675dbc3da532aeb583c96855ba47e5a4767a7b&shared=true |
| +28 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozMzc3NzY4Njc4LCJ0IjoxNjAyMzQzMTU0fQ%3D%3D--4f0f4ee1474f41f1c071ed0119675dbc3da532aeb583c96855ba47e5a4767a7b&shared=true |
| +0 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +0 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
</details>
