### ISSUE TITLE
theporndude.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#307]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
theporndude.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-114748](https://user-images.githubusercontent.com/38778536/95641510-8b454900-0aee-11eb-9df3-84204c8c9875.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +47 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMjYwOTA3NzU3LCJ0IjoxNjAyMzQyODM0fQ%3D%3D--28f2e8794f42d51300a50c50d5ea9ab4bc57f8855e64d9b288a024538b897cf2&shared=true |
| +37 | ##.socials |  | theporndude.com |  | dom | `https://theporndude.com/` |
| +37 | ##.go_up |  | theporndude.com |  | dom | `https://theporndude.com/` |
| +36 | `##[href^="https://twitter.com"]` |  | theporndude.com |  | dom | `https://theporndude.com/` |
| +36 |  |  | theporndude.com | 1 | image | `https://theporndude.com/favicon-16x16.png` |
| +36 |  |  | theporndude.com | 1 | image | `https://theporndude.com/apple-touch-icon.png` |
| +36 | \|\|onesignal.com^$3p | -- | theporndude.com | 3 | script | `https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=150602` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/theporndudebottom.png` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/circle-down.svg` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/vr-friendly.png` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/default_favicon.png?t=1601647871` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/icon_review_smaller.png` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/fcons_lang/5177d0f7_custom-favicon-spritesheet-en.png?t=1601647886` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/9d186940_custom-favicon-spritesheet.png?t=1601647876` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/e36f1759_favicon-spritesheet.png?t=1601647871` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/homepage_icons.png` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/search.png` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/flags_new.png` |
| +34 | /socialicons. | -- | theporndude.com | 1 | image | `https://theporndude.com/includes/images/socialicons.png` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/tinyloader.svg` |
| +34 | googletagmanager.com/gtm.js | << | theporndude.com |  | script | `https://www.googletagmanager.com/gtm.js?id=GTM-PCC295W` |
| +34 | \|\|googletagmanager.com/gtm.js$script | -- | theporndude.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-PCC295W` |
| +34 | google-analytics.com/ga.js | << | theporndude.com |  | script | `https://ssl.google-analytics.com/ga.js` |
| +34 | \|\|google-analytics.com^ | -- | theporndude.com | 3 | script | `https://ssl.google-analytics.com/ga.js` |
| +34 |  |  | theporndude.com | 1 | script | `https://theporndude.com/includes/js/lazysizes.min.js` |
| +34 |  |  | theporndude.com | 3 | script | `https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.10/vue.min.js` |
| +34 |  |  | theporndude.com | 3 | script | `https://cdnjs.cloudflare.com/ajax/libs/algoliasearch/3.35.1/algoliasearch.min.js` |
| +34 |  |  | theporndude.com | 1 | script | `https://theporndude.com/includes/js/main.min.js?t=1601548122` |
| +34 |  |  | theporndude.com | 3 | script | `https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/dude/72/tpd-half-heart.png` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/favicon-bottom.png` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/searchingdude.png` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/new_icon.png` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/bookme.png` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/icon_rating_on.png` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/theporndude.png` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/theporndudelogo.png` |
| +34 |  |  | theporndude.com | 1 | image | `https://theporndude.com/includes/images/newmobilelogo.png` |
| +34 |  |  | theporndude.com | 1 | css | `https://theporndude.com/includes/css/mobile_categories.css` |
| +34 |  |  | theporndude.com | 1 | css | `https://theporndude.com/includes/css/fcons_lang/3d6fbabc0ddd0f052ea7cd09317d323e_custom-sprite-en.css?t=1601548289` |
| +34 |  |  | theporndude.com | 1 | css | `https://theporndude.com/includes/css/688d1e2.fcons.min.css?t=1601548289` |
| +34 |  |  | theporndude.com | 1 | css | `https://theporndude.com/includes/css/main.min.css?t=1601548289` |
| +33 |  |  | theporndude.com | 1 | doc | `https://theporndude.com/` |
| +33 |  |  | `www.theporndude.com` | 1 | doc | `https://www.theporndude.com/` |
| +33 |  |  | `www.theporndude.com` | 1 | doc | `http://www.theporndude.com/` |
| +0 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +0 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
</details>
