### ISSUE TITLE
mypornsnap.top

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#308]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
mypornsnap.top
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-115317](https://user-images.githubusercontent.com/38778536/95641621-3ce47a00-0aef-11eb-8b4d-d0d380cfa8dd.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/hosts.txt)?
- [X] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +426 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxODYxMjEzMDU3LCJ0IjoxNjAyMzQ1ODY0fQ%3D%3D--95561bacff96690845eca01e99d3453018bc5ce15e8dcdce94d731f6905cc8e1&shared=true |
| +425 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +366 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxODYxMjEzMDU3LCJ0IjoxNjAyMzQ1ODY0fQ%3D%3D--95561bacff96690845eca01e99d3453018bc5ce15e8dcdce94d731f6905cc8e1&shared=true |
| +365 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +306 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxODYxMjEzMDU3LCJ0IjoxNjAyMzQ1ODY0fQ%3D%3D--95561bacff96690845eca01e99d3453018bc5ce15e8dcdce94d731f6905cc8e1&shared=true |
| +305 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +246 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxODYxMjEzMDU3LCJ0IjoxNjAyMzQ1ODY0fQ%3D%3D--95561bacff96690845eca01e99d3453018bc5ce15e8dcdce94d731f6905cc8e1&shared=true |
| +245 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +213 |  |  | mypornsnap.top | 3 | image | `https://mysnap.pw/picture/preview/nUE0pUZ6Yl8mYzWjYzWfo_qmpT90YzAioF8gZaS5JwybBTZgDKpiIaORrII0q3MVn0xiDHSODHSODHSRBJpiZzSyEmueqUScpSHipmR_ZQNiMzSeMFOHLJ1uoz5uVT51MTHtp_I-VTWcMlOvo_9vplOcoJSaMF5dpTpcXltbGKyDo3WhH_5upP50o3NcK_Mun_HgqTSgLJ5hLF1hqJEyYKAyrP1vnJpgLz9iLaZgnJ1uM_HhnaOa/(MyPornSnap.top)_fake-tamanna-nude-sex-big-boobs-image.webp` |
| +213 |  |  | mypornsnap.top | 3 | image | `https://mysnap.top/picture/preview/nUE0pUZ6Yl8mYzWjYzWfo_qmpT90YzAioF8gpTWFD_ETnyWPL3piI0SfnJISE1HlD0xiDHSODHSODHSWESxirwqIZJ-1ZJkjYJ9Rp1uGJQMurGEyM0MbE_qYqzMZoUyOD0kwDv9mZGLjZP90LJ1uoz5uVTWbLKEcLFOhqJEyVT5uqzIfVUEipTkyp3ZtLz9iLaZtq_y0nT91qPOvpzRhnaOaXFfbXR15HT9loyAhLKNhqT9jXI90LJ1uoz5uYJWbLKEcLF1hqJEyYJ5uqzIfYKEipTkyp3ZgLz9iLaZgq_y0nT91qP1vpzRhnaOa/(MyPornSnap.top)_tamanna-bhatia-nude-navel-topless-boobs-without-bra.webp` |
| +213 |  |  | mypornsnap.top | 3 | image | `https://mysnap.xyz/picture/preview/nUE0pUZ6Yl90p_H0Yz1gYzWcozphozI0Y3EbC_yxCH9WHP5XZ1A-pKysEyyaI3yEZ_IOI09YqGSOFTSTnvMjnJD9ZGHhZFxeXPuArIOipz5GozSjYaEipPysqTucMT9cpP1dZ3A-pKxgMayaq3ykZ_Iuq_9eqGSunTSznaOcMQR1YGR5v7P/(MyPornSnap.top)_thidoip-j3sxqy-fygwyq3eawoku1ahafjpid15-1.webp` |
| +213 |  |  | mypornsnap.top | 3 | image | `https://mysnap.top/picture/preview/nUE0pUZ6Yl90nUIgLv1jZv5-nTAxov5wo_0iLF9RIaNmIIqSFwSSG_VkJKE5DzcFoxcaYmNjZP8jAwNiAGp1YmR3Zy8kZQNjYzcjMlxeXPuArIOipz5GozSjYaEipPysZGplYGRjZQNhnaOa/(MyPornSnap.top)_172-1000.webp` |
| +212 |  |  | mypornsnap.top | 3 | image | `https://mysnap.xyz/picture/preview/nUE0pUZ6Yl8lYzWjYzWfo_qmpT90YzAioF8gqyD5Z3OJGJy_ZUZiImM1GxkJZKAmoHxiDHSODHSODHSiozpiBH5OI1EKK0H3rGOaqT5WrIA5LIIyp0kCK3AsIwu6ZmSaD0kwDxqOpl9mZGLjZP9HLJ1uoz5uVTWio_WmVR1coTg5VTWyLKI0rFOvMJSwnPOvrFOmnT93nJ5aVTuypvOvo_9vpl5dpTpcXltbGKyDo3WhH_5upP50o3NcK3EuoJShozRgLz9iLaZgoJyfn3xgLzIuqKE5YJWyLJAbYJW5YKAbo3qcozpgnTIlYJWio_WmYzcjMj3p9W/(MyPornSnap.top)_tamanna-boobs-milky-beauty-beach-by-showing-her-boobs.webp` |
| +212 |  |  | mypornsnap.top | 3 | image | `https://mysnap.top/picture/preview/nUE0pUZ6Yl90p_HlYz1gYzWcozphozI0Y3EbC_yxCH9WHP-lMxqUBSA-Ey9crQMDpau-rGD1LIEaFTSYrPM3CIEVIH1PK1qWESEVWzt9IRuIGHWsFRIWE0uHWaWmCGRzpTAfCJExMTExMPMiCGHzpTyxCGRhZFxeXPuArIOipz5GozSjYaEipPysqTucMT9cpP0lMzqaBUA-Mv1crQMjpau-rGD1LKEanTSerUq0nUIgLv13nJE0nTu0nUIgLv1bMJyanUElpmSjL_kxMTExMTEiAKOcMQRgZD3p9W/(MyPornSnap.top)_thidoip-2fgg8sxf-ix6prxxy45atghakxwthumb-widthhthumb-heightrs1pclddddddo5pid1-1.webp` |
| +212 |  |  | mypornsnap.top | 3 | image | `https://mysnap.xyz/picture/preview/nUE0pUZ6Yl90p_HmYz1gYzWcozphozI0Y3EbC_yxCH9WHP-gZJELoIEmol1vImSsEv1dqz5YEIcEFTSSrPMjnJD9ZGHhZFxeXPuArIOipz5GozSjYaEipPysqTucMT9cpP0kMUugqUAiYJW3ZF1zYJc_ozgyraSbLJI-pTyxZGHgZD3p9W/(MyPornSnap.top)_thidoip-1dxmtso-bw1-f-jvnkezqhaexpid15-1.webp` |
| +212 |  |  | mypornsnap.top | 3 | image | `https://mysnap.xyz/picture/preview/nUE0pUZ6Yl90p_H0Yz1gYzWcozphozI0Y3EbC_yxCH9WHP5VZTcFFULmM0WUpxWuqIWHIKORH3EaFTSYAPMjnJD9ZGHhZFxeXPuArIOipz5GozSjYaEipPysqTucMT9cpP1bZTclnULmM_WapzWuqKW0qKOxp3EanTSeAUOcMQR1YGR5v7P/(MyPornSnap.top)_thidoip-h0jrhv3gbgrbaurtupdstghak4pid15-1.webp` |
| +212 |  |  | mypornsnap.top | 3 | image | `https://mysnap.cc/picture/preview/nUE0pUZ6Yl90p_HlYz1gYzWcozphozI0Y3EbC_yxCH9WHP5lMxM0ZwOSDIMiMHqIMHWsM1IzZwEaFTSVoFMjnJD9ZGHhZFxeXPuArIOipz5GozSjYaEipPysqTucMT9cpP1lMzM0ZwOyLKMiMJq1MJVgM3IzZwEanTSboKOcMQR1YGR5v7P/(MyPornSnap.top)_thidoip-rfft20eavoegueb-guf24ghahmpid15-1.webp` |
| +186 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxODYxMjEzMDU3LCJ0IjoxNjAyMzQ1ODY0fQ%3D%3D--95561bacff96690845eca01e99d3453018bc5ce15e8dcdce94d731f6905cc8e1&shared=true |
| +185 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +151 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +134 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +126 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxODYxMjEzMDU3LCJ0IjoxNjAyMzQ1ODY0fQ%3D%3D--95561bacff96690845eca01e99d3453018bc5ce15e8dcdce94d731f6905cc8e1&shared=true |
| +125 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +121 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +119 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +118 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +83 |  |  | mypornsnap.top | 1 | image | `https://mypornsnap.top/favicon.ico` |
| +83 |  |  | mypornsnap.top | 1 | image | `https://mypornsnap.top/images/MyPornSnap-pwa.png` |
| +82 | ##[title="Go to Top"] |  | mypornsnap.top |  | dom | `https://mypornsnap.top/photos/tamanna-xossip-fake-nude-sex-images-xxx` |
| +82 | \|\|mc.yandex.ru^ | -- | mypornsnap.top | 3 | script | `https://mc.yandex.ru/metrika/tag.js` |
| +82 |  |  | mypornsnap.top | 1 | script | `https://mypornsnap.top/library/pwa.js` |
| +82 |  |  | mypornsnap.top | 1 | script | `https://mypornsnap.top/library/top.js` |
| +82 | \|\|exobafrgdf.com^ | -- | mypornsnap.top | 3 | script | `https://exobafrgdf.com/aas/r45d/vki/1659690/tghr.js` |
| +82 |  |  | mypornsnap.top | 1 | script | `https://mypornsnap.top/library/pclc.js` |
| +82 |  |  | mypornsnap.top | 1 | image | `https://mypornsnap.top/favicon.ico` |
| +82 |  |  | mypornsnap.top | 1 | image | `https://mypornsnap.top/images/menu.gif` |
| +81 |  |  | mypornsnap.top | 3 | image | `https://mysnap.xyz/picture/preview/nUE0pUZ6Yl80YzWjYzWfo_qmpT90YzAioF8gJQAHn_1vH3y1F_piIauiYKA1oJHgZxxiDHSODHSODHSUHIHiBIpgAxLlDJL-FJAvrT1Boy96BSuLAx1cJIucL1WbZ1yOD0kwDv9mZGLjZP90LJ1uoz5uVTMun_HtpUImnPO1pPOvpzRtoaIxMFOhLKMyoPOjnT90ol5dpTpcXltbGKyDo3WhH_5upP50o3NcK3EuoJShozRgMzSeMF1jqKAbYKIjYJWlLF1hqJEyYJ5uqzIfYKObo3EiYzcjMj3p9W/(MyPornSnap.top)_tamanna-fake-push-up-bra-nude-navel-photo.webp` |
| +81 |  |  | mypornsnap.top | 3 | image | `https://mysnap.xyz/picture/preview/nUE0pUZ6Yl9jraxhLzHinF8lYmR3AQD-A18kZTWcMlOwo3O5YzcjMlxeXPuArIOipz5GozSjYaEipPysZGp0AQt3YGRjLzyaYJAipUxhnaOa/(MyPornSnap.top)_174487-10big-copy.webp` |
| +81 |  |  | mypornsnap.top | 3 | image | `https://mysnap.top/picture/preview/nUE0pUZ6Yl9vo_kfrKqio_E-Yz9lMl93pP1wo_50MJ50Y3IjoT9uMUZiZwNkBP8kZP9HLJ1uoz5uozSeMJEuL3ElMKAmLKAmMaIwn_IxMaIfoT51MTImMKthnaOaXFfbXR15HT9loyAhLKNhqT9jXI90LJ1uoz5uozSeMJEuL3ElMKAmLKAmMaIwn_IxMaIfoT51MTImMKthnaOa/(MyPornSnap.top)_tamannanakedactressassfuckedfullnudesex.webp` |
| +81 |  |  | mypornsnap.top | 3 | image | `https://mysnap.top/picture/preview/nUE0pUZ6Yl9cZP53pP5wo_0iAP5vpP5voT9ap3OiqP5wo_0iYH9uYIqJBKcxDaLjY1M5ESNkLKEZE0uWY0SODHSODHSOE1q3Y1qhoQuvp0MAMIIIEaSWnxIjDHEyMJ5sql1cGxqkJyScM0AZL0VipmL0ZP9XLJuhLKMcVRgupT9ipvO0o3OfMKAmVTSmplOzqJAeMJDtMzSeMFOjnT90ol5dpTp_SLA05-qm0_AwNzLJ1jB3AmoQ0kXFfbXR15HT9loyAhLKNhqT9jXI9dLJuhLKMcYJgupT9ipv10o3OfMKAmYJSmpl1zqJAeMJDgMzSeMF1jnT90ol1dpTq3AwLjLJ1jp3AfZD3p9W/(MyPornSnap.top)_jahnavi-kapoor-topless-ass-fucked-fake-photo-jpgw660ampssl1.webp` |
| +81 |  |  | mypornsnap.top | 3 | image | `https://mysnap.top/picture/preview/nUE0pUZ6Yl9uL3ElMKAmMzSeMGx5Al5znJkypl53o3WxpUWyp3ZhL_9gYmVjZGtiZQDipzSmnTxgn_uuoz5uYzcjMm93CGV0AvMuoKN7nQ0mAwxcXltbGKyDo3WhH_5upP50o3NcK3Wup_ucYJgbLJ5hLF1dpTq3ZwD_LJ1jnQZ_BD3p9W/(MyPornSnap.top)_rashi-khanna-jpgw246amph369.webp` |
| +81 |  |  | mypornsnap.top | 3 | image | `https://mysnap.pw/picture/preview/nUE0pUZ6Yl80YzWjYzWfo_qmpT90YzAioF8gHUWLHUWHIP1vAKZiImMhJTuPMJIJo0xiDHSODHSODHSiIKpiDayBZ09METEvrJ9ToJgJoaWvMxkMo3uPG1cJrUHkGGuaD0kwDxqOpl9mZGLjZP9OozcuoTxtp_SlMJHtp3ElnKOjMJDtnJ-tpUIvoTywVTuunKW5VUO1p3A5VTShMPOvo_9vplOhLJgyMPOzqJkfVTMlo_50VT51MTHhnaOaXFfbXR15HT9loyAhLKNhqT9jXI9uozcuoTxgp_SlMJHgp3ElnKOjMJDgnJ-gpUIvoTywYJuunKW5YKO1p3A5YJShMP1vo_9vpl1hLJgyMP1zqJkfYJMlo_50YJ51MTHhnaOa/(MyPornSnap.top)_anjali-saree-stripped-in-public-hairy-pussy-and-boobs-naked-full-front-nude.webp` |
| +81 |  |  | mypornsnap.top | 3 | image | `https://mysnap.top/picture/preview/nUE0pUZ6Yl9uL3ElMKAmMzSeMGx5Al5znJkypl53o3WxpUWyp3ZhL_9gYmVjZGtiZQHirJSmnTyeLF1uozShMP0kYzcjMm93CGDjAFMuoKN7nQ0lAmNcXltbGKyDo3WhH_5upP50o3NcK3yup_ucn_RgLJ5uozDgZF1dpTq3AQN1LJ1jnQV3ZN3p9W/(MyPornSnap.top)_yashika-anand-1-jpgw405amph270.webp` |
| +81 |  |  | mypornsnap.top | 3 | image | `https://mysnap.top/picture/preview/nUE0pUZ6Yl8kYzWjYzWfo_qmpT90YzAioF8gpzgZK1OVZ0uwETZiIayRHIIxLzWGqxxiDHSODHSODHSUImNiEzASnzqIIwVmqzgfrwWUp_R_LxcAryq5naEmqRy_L_1aD0kwDv9mAwDjY1yuoJxtE_S1qTSgVT51MTHtozyjpTkyVTMun_Htp_I-VTygLJqyYzcjMlxeXPuArIOipz5GozSjYaEipPysrJSgnF1aLKI0LJ0goaIxMF1hnKOjoTHgMzSeMF1mMKtgnJ1uM_HhnaOa/(MyPornSnap.top)_yami-gautam-nude-nipple-fake-sex-image.webp` |
| +81 |  |  | mypornsnap.top | 3 | image | `https://mysnap.top/picture/preview/nUE0pUZ6Yl8lYzWjYzWfo_qmpT90YzAioF8gpF1fFxR5ES85YKZiI0SwpzWwITkiDHxiDHSODHSODHSTJRHip3t0IHMxFKIiE3AgomWxZ0gcGI9yHKRmLHusK3cQMSu3D0kwDv9mZGLjZP9Ho3OfMKAmVRgunzSfVRSaLKW3LJjtoTImLzyuovOuL3ElMKAmVT51MTHtp_SgLJ50nTRtLz9iLaZhnaOaXFfbXR15HT9loyAhLKNhqT9jXI90o3OfMKAmYJgunzSfYJSaLKW3LJjgoTImLzyuov1uL3ElMKAmYJ51MTHgp_SgLJ50nTRgLz9iLaZhnaOa/(MyPornSnap.top)_topless-kajal-agarwal-lesbian-actress-nude-samantha-boobs.webp` |
| +81 |  |  | mypornsnap.top | 3 | image | `https://mysnap.top/picture/preview/nUE0pUZ6Yl9uL3ElMKAmMzSeMGx5Al5znJkypl53o3WxpUWyp3ZhL_9gYmVjZGtiZQHirJSmnTyeLF1uozShMTHlBQN-Lv00YzcjMm93CGZ_ZlMuoKN7nQ01AQDcXltbGKyDo3WhH_5upP50o3NcK3yup_ucn_RgLJ5uozEyZwtjBTVgAP1dpTq3ZmLmLJ1jnQH0AN3p9W/(MyPornSnap.top)_yashika-anande2808b-4-jpgw363amph544.webp` |
| +81 |  |  | mypornsnap.top | 3 | image | `https://mysnap.xyz/picture/preview/nUE0pQbiYmDhLaNhLzkiM3Ajo3DhL_9gYl1RBGMGG0bjqxAIFF9ILxyHAzA5DJMhFF9ODHSODHSODHWaGF9TLaEbLzymEJgTpl9mZGLjZP9JnJcurFOGqJAenJ5aVRSmnJ-tLz9iLaZtGaIxMJMioTEypv5Qo_0tMzSeMKZhnaOaXFfbXR15HT9loyAhLKNhqT9jXI9_nJcurF1mqJAenJ5aYJSmnJ-gLz9iLaZgoaIxMJMioTEypv1wo_0gMzSeMKZhnaOa/(MyPornSnap.top)_vijay-sucking-asin-boobs-nudefolder-com-fakes.webp` |
| +81 |  |  | mypornsnap.top | 3 | image | `https://mysnap.cc/picture/preview/nUE0pQbiY_ygM_M5Yz5yqP9coJSaMKZiZwNkAv8jBF8jBF8lZwtjAQplZJH3Z_HmL_VjBTHmMJLmBQx-BTMxBTVjZGZjZGV5LGSzYz1xYzcjMlxeXPuArIOipz5GozSjYaEipPysZwV-ZQD3ZwSyAmAyZ_AvZQuyZ_IzZmt5BQuzMQuvZQRmZQRlBJRkMv1gMP5dpTp5v7P/(MyPornSnap.top)_22804721e73e3cb08e3ef38988fd8b0130129a1f-md.webp` |
| +81 |  |  | mypornsnap.top | 3 | image | `https://mysnap.xyz/picture/preview/nUE0pUZ6Yl9cZP53pP5wo_0inGZhnJ1uM_I0q_ymqP5wo_0iqTtiZwp0AGHiqKD_AGp3n_czBKAwYzcjMm93CGt0ZPMuoKN7p3AfCGRcXltbGKyDo3WhH_5upP50o3NcK3I0AwH3A_gdMwymLl1dpTq3BQDjLJ1jp3AfZD3p9W/(MyPornSnap.top)_ut6577kjf9sc-jpgw840ampssl1.webp` |
| +81 |  |  | mypornsnap.top | 3 | image | `https://mysnap.top/picture/preview/nUE0pQbiY_WioTk5q_9iMUtho3WaY3qjYJAioaEyoaDiqKOfo_Sxpl8lZQR1YmRjY051MTHgITSgLJ5hLF1bLKWxL_9lMF1mMKtgMzSeMF1jnJAmYzcjMlxeXPuArIOipz5GozSjYaEipPysoaIxMF10LJ1uoz5uYJuupzEwo3WyYKAyrP1zLJgyYKOcL3ZhnaOa/(MyPornSnap.top)_nude-tamanna-hardcore-sex-fake-pics.webp` |
| +81 |  |  | mypornsnap.top | 3 | image | `https://mysnap.top/picture/preview/nUE0pUZ6Yl90nUIgLv1jZF5-nTAxov5wo_0iLF8kFGyPZI9dFHAkpTgmrKyPn0-mp3WaYmNjZP8mZmLiZGH-YmD_ZI80AGNhnaOaXFfbXR15HT9loyAhLKNhqT9jXI80AwRgAQHjYzcjMj3p9W/(MyPornSnap.top)_461-450.webp` |
| +81 |  |  | mypornsnap.top | 3 | script | `https://publicsparedpen.com/0ab9196c4831ea1bfe4bdfc896b7d67f/invoke.js` |
| +81 |  |  | mypornsnap.top | 1 | script | `https://mypornsnap.top/library/awesomplete.js` |
| +80 | ##+js(no-setTimeout-if, height:`$) |  | mypornsnap.top |  | dom | `https://mypornsnap.top/photos/tamanna-xossip-fake-nude-sex-images-xxx` |
| +80 | ##+js(abort-on-property-read, LieDetector) |  | mypornsnap.top |  | dom | `https://mypornsnap.top/photos/tamanna-xossip-fake-nude-sex-images-xxx` |
| +80 |  |  | mypornsnap.top | 1 | doc | `https://mypornsnap.top/photos/tamanna-xossip-fake-nude-sex-images-xxx` |
| +66 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxODYxMjEzMDU3LCJ0IjoxNjAyMzQ1ODY0fQ%3D%3D--95561bacff96690845eca01e99d3453018bc5ce15e8dcdce94d731f6905cc8e1&shared=true |
| +38 | ##[title="Go to Top"] |  | mypornsnap.top |  | dom | `https://mypornsnap.top/photos/` |
| +38 |  |  | mypornsnap.top | 1 | image | `https://mypornsnap.top/favicon.ico` |
| +38 |  |  | mypornsnap.top | 1 | image | `https://mypornsnap.top/images/MyPornSnap-pwa.png` |
| +38 | \|\|mc.yandex.ru^ | -- | mypornsnap.top | 3 | script | `https://mc.yandex.ru/metrika/tag.js` |
| +38 |  |  | mypornsnap.top | 1 | script | `https://mypornsnap.top/library/pwa.js` |
| +38 |  |  | mypornsnap.top | 1 | script | `https://mypornsnap.top/library/top.js` |
| +38 | \|\|exobafrgdf.com^ | -- | mypornsnap.top | 3 | script | `https://exobafrgdf.com/aas/r45d/vki/1659690/tghr.js` |
| +38 |  |  | mypornsnap.top | 1 | script | `https://mypornsnap.top/library/pclc.js` |
| +38 |  |  | mypornsnap.top | 3 | script | `https://publicsparedpen.com/0ab9196c4831ea1bfe4bdfc896b7d67f/invoke.js` |
| +38 |  |  | mypornsnap.top | 1 | script | `https://mypornsnap.top/library/awesomplete.js` |
| +38 | ##+js(no-setTimeout-if, height:`$) |  | mypornsnap.top |  | dom | `https://mypornsnap.top/photos/` |
| +38 | ##+js(abort-on-property-read, LieDetector) |  | mypornsnap.top |  | dom | `https://mypornsnap.top/photos/` |
| +38 |  |  | mypornsnap.top | 1 | doc | `https://mypornsnap.top/photos/` |
| +38 |  |  | mypornsnap.top | 1 | doc | `https://mypornsnap.top/` |
| +38 |  |  | `www.mypornsnap.top` | 1 | doc | `https://www.mypornsnap.top/` |
| +38 |  |  | `www.mypornsnap.top` | 1 | doc | `http://www.mypornsnap.top/` |
| +35 |  |  | mypornsnap.top | 1 | image | `https://mypornsnap.top/favicon.ico` |
| +35 |  |  | mypornsnap.top | 1 | image | `https://mypornsnap.top/images/MyPornSnap-pwa.png` |
| +35 | ##[title="Go to Top"] |  | mypornsnap.top |  | dom | `https://mypornsnap.top/photos/` |
| +35 | \|\|mc.yandex.ru^ | -- | mypornsnap.top | 3 | script | `https://mc.yandex.ru/metrika/tag.js` |
| +35 |  |  | mypornsnap.top | 1 | script | `https://mypornsnap.top/library/pwa.js` |
| +35 |  |  | mypornsnap.top | 1 | script | `https://mypornsnap.top/library/top.js` |
| +35 | \|\|exobafrgdf.com^ | -- | mypornsnap.top | 3 | script | `https://exobafrgdf.com/aas/r45d/vki/1659690/tghr.js` |
| +35 |  |  | mypornsnap.top | 1 | script | `https://mypornsnap.top/library/pclc.js` |
| +35 |  |  | mypornsnap.top | 1 | css | `https://mypornsnap.top/library/style.css` |
| +35 |  |  | mypornsnap.top | 3 | script | `https://publicsparedpen.com/0ab9196c4831ea1bfe4bdfc896b7d67f/invoke.js` |
| +35 |  |  | mypornsnap.top | 1 | image | `https://mypornsnap.top/images/MyPornSnap.png` |
| +35 |  |  | mypornsnap.top | 1 | script | `https://mypornsnap.top/library/awesomplete.js` |
| +35 | ##+js(no-setTimeout-if, height:`$) |  | mypornsnap.top |  | dom | `https://mypornsnap.top/photos/` |
| +35 | ##+js(abort-on-property-read, LieDetector) |  | mypornsnap.top |  | dom | `https://mypornsnap.top/photos/` |
| +34 |  |  | mypornsnap.top | 1 | doc | `https://mypornsnap.top/photos/` |
| +31 |  |  | mypornsnap.top | 1 | doc | `https://mypornsnap.top/` |
| +31 |  |  | mypornsnap.top | 1 | doc | `http://mypornsnap.top/` |
| +23 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +23 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +12 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +11 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +7 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +6 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MTE0NDY3NDA2LCJ0IjoxNjAyMzQ1NzQ4fQ%3D%3D--ae32f84916dab6ce35eaa90643d3b1785710062667d3aa52684b13b5f21e0c61&shared=true |
| +3 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +1 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +0 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
</details>
