### ISSUE TITLE
pornsites.xxx

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#309]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
pornsites.xxx
cdn.pornsites.xxx
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-115825](https://user-images.githubusercontent.com/38778536/95641791-0fe49700-0af0-11eb-871c-f6b2831cfb70.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/hosts.txt)?
- [X] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +262 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +230 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +213 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +205 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +201 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +199 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +198 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +198 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MDM4ODMxMjU3LCJ0IjoxNjAyMzQ2NTE1fQ%3D%3D--9ba6a2266f5af15a19da3d31d4af64843e54d767335431d31a6f5bc8acbef8b5&shared=true |
| +163 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MDM4ODMxMjU3LCJ0IjoxNjAyMzQ2NTE1fQ%3D%3D--9ba6a2266f5af15a19da3d31d4af64843e54d767335431d31a6f5bc8acbef8b5&shared=true |
| +153 | `##a[href^="https://chaturbate.com/affiliates/"]` |  | pornsites.xxx |  | dom | `https://pornsites.xxx/` |
| +153 | ##a[href*="//bongacams.com/track?"] |  | pornsites.xxx |  | dom | `https://pornsites.xxx/` |
| +153 | `##[href^="https://twitter.com"]` |  | pornsites.xxx |  | dom | `https://pornsites.xxx/` |
| +153 | ##.icon-twitter |  | pornsites.xxx |  | dom | `https://pornsites.xxx/` |
| +153 | ###return-to-top |  | pornsites.xxx |  | dom | `https://pornsites.xxx/` |
| +152 |  |  | pornsites.xxx | 1 | image | `https://pornsites.xxx/favicon-16x16.png` |
| +152 |  |  | pornsites.xxx | 1 | image | `https://pornsites.xxx/apple-touch-icon-152x152.png` |
| +152 | \|\|googletagmanager.com/gtag/$3p | -- | pornsites.xxx | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-109322799-2` |
| +152 |  |  | pornsites.xxx | 1 | image | `https://cdn.pornsites.xxx/img/!icons_sites.png?t=1601928868` |
| +152 |  |  | pornsites.xxx | 1 | image | `https://cdn.pornsites.xxx/img/!icons_cat_big.png?t=1601928868` |
| +152 | /img/twitter_ | -- | pornsites.xxx | 1 | image | `https://cdn.pornsites.xxx/img/Twitter_Logo_Blue.svg` |
| +152 |  |  | pornsites.xxx | 1 | image | `https://cdn.pornsites.xxx/img/!flags.png` |
| +152 |  |  | pornsites.xxx | 1 | css | `https://cdn.pornsites.xxx/css/pornsites.css?t=1602238640` |
| +152 | \|\|googletagmanager.com/gtag/$3p | -- | pornsites.xxx | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-109322799-2` |
| +152 |  |  | pornsites.xxx | 1 | script | `https://cdn.pornsites.xxx/js/scripts.js?1602324737` |
| +152 |  |  | pornsites.xxx | 1 | css | `https://cdn.pornsites.xxx/css/favicons_psxxx.css?t=1601928875` |
| +152 | \|\|googleapis.com^$important | -- | pornsites.xxx | 3 | script | `https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js` |
| +152 |  |  | pornsites.xxx | 1 | image | `https://cdn.pornsites.xxx/img/pornsites-logo.svg` |
| +152 |  |  | pornsites.xxx | 1 | image | `https://cdn.pornsites.xxx/img/vampire.png` |
| +152 |  |  | pornsites.xxx | 1 | doc | `https://pornsites.xxx/` |
| +150 |  |  | `www.pornsites.xxx` | 1 | doc | `https://www.pornsites.xxx/` |
| +149 |  |  | `www.pornsites.xxx` | 1 | doc | `http://www.pornsites.xxx/` |
| +147 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MDM4ODMxMjU3LCJ0IjoxNjAyMzQ2NTE1fQ%3D%3D--9ba6a2266f5af15a19da3d31d4af64843e54d767335431d31a6f5bc8acbef8b5&shared=true |
| +139 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MDM4ODMxMjU3LCJ0IjoxNjAyMzQ2NTE1fQ%3D%3D--9ba6a2266f5af15a19da3d31d4af64843e54d767335431d31a6f5bc8acbef8b5&shared=true |
| +135 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MDM4ODMxMjU3LCJ0IjoxNjAyMzQ2NTE1fQ%3D%3D--9ba6a2266f5af15a19da3d31d4af64843e54d767335431d31a6f5bc8acbef8b5&shared=true |
| +132 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MDM4ODMxMjU3LCJ0IjoxNjAyMzQ2NTE1fQ%3D%3D--9ba6a2266f5af15a19da3d31d4af64843e54d767335431d31a6f5bc8acbef8b5&shared=true |
| +130 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MDM4ODMxMjU3LCJ0IjoxNjAyMzQ2NTE1fQ%3D%3D--9ba6a2266f5af15a19da3d31d4af64843e54d767335431d31a6f5bc8acbef8b5&shared=true |
| +130 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +129 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +126 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0ODMzMjM3NzksInQiOjE2MDIzNDY0OTV9--296796e16c7e814bd44c8d29baf2f13151be58074aca75270152dc528fe1cd16&shared=true |
| +117 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0ODMzMjM3NzksInQiOjE2MDIzNDY0OTV9--296796e16c7e814bd44c8d29baf2f13151be58074aca75270152dc528fe1cd16&shared=true |
| +113 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0ODMzMjM3NzksInQiOjE2MDIzNDY0OTV9--296796e16c7e814bd44c8d29baf2f13151be58074aca75270152dc528fe1cd16&shared=true |
| +111 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0ODMzMjM3NzksInQiOjE2MDIzNDY0OTV9--296796e16c7e814bd44c8d29baf2f13151be58074aca75270152dc528fe1cd16&shared=true |
| +110 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0ODMzMjM3NzksInQiOjE2MDIzNDY0OTV9--296796e16c7e814bd44c8d29baf2f13151be58074aca75270152dc528fe1cd16&shared=true |
| +110 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +109 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +60 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +0 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
</details>
