### ISSUE TITLE
landing.jerkmate.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#310]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
jerkmate.com
landing.jerkmate.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-120147](https://user-images.githubusercontent.com/38778536/95641980-68686400-0af1-11eb-8ff5-82277c33fb0b.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
+ 
```python
api.jerkmate.com
gateway.jerkmate.com
```

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +165 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +165 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +162 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +162 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +159 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +159 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +156 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +156 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +153 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +153 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +150 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +150 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +147 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +147 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +144 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +144 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +141 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +141 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +138 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +138 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +136 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +135 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +135 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +132 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +132 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +129 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +129 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +126 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +126 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +123 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +123 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +120 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +120 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +117 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +117 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +114 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +114 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +111 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +111 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +108 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +108 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +105 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +105 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +104 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +102 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +102 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +99 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +99 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +95 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +95 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +92 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +92 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +89 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +89 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +88 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +86 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +86 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +83 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +83 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +80 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +80 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +80 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +77 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +77 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +75 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +74 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +74 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +73 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +72 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +72 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyNjkzMTA4NTYyLCJ0IjoxNjAyMzQ2Njk4fQ%3D%3D--5845593d869bc5831558f606cf7c302ee9997a04eba45d21ab63dd2c0a3ee461&shared=true |
| +71 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +71 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +68 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +68 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +65 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +65 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +62 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +62 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +59 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +59 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +56 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +56 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +53 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +53 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +50 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +50 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +47 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +47 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +44 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +44 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +44 |  |  | jerkmate.com | 1 | image | `https://gateway.jerkmate.com/cmscloud/dA/3e417d45-a103-4ca2-8777-04974000cb20/image/enhence-male-small.jpg` |
| +44 |  |  | jerkmate.com | 1 | image | `https://gateway.jerkmate.com/cmscloud/dA/3e417d45-a103-4ca2-8777-04974000cb20/image/enhence-male-small.jpg` |
| +43 |  |  | jerkmate.com | 1 | image | `https://gateway.jerkmate.com/cmscloud/dA/c69d993d-b55b-42d4-92fc-bc3987d88cbf/featuredimageWebp/eva_elfie.webp` |
| +43 |  |  | jerkmate.com | 1 | image | `https://gateway.jerkmate.com/cmscloud/dA/c69d993d-b55b-42d4-92fc-bc3987d88cbf/bannerImage/eva_elfie.png` |
| +43 |  |  | jerkmate.com | 1 | image | `https://gateway.jerkmate.com/cmscloud/dA/989ad2de-75db-4eb3-b0b1-8464577ad46a/image/Design-182_JerkmateBlog_RP_RolePlay_360x248_.jpg` |
| +43 |  |  | jerkmate.com | 1 | image | `https://gateway.jerkmate.com/cmscloud/dA/989ad2de-75db-4eb3-b0b1-8464577ad46a/image/Design-182_JerkmateBlog_RP_RolePlay_360x248_.jpg` |
| +41 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +41 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +38 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +38 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +38 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyNjkzMTA4NTYyLCJ0IjoxNjAyMzQ2Njk4fQ%3D%3D--5845593d869bc5831558f606cf7c302ee9997a04eba45d21ab63dd2c0a3ee461&shared=true |
| +35 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +35 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +34 |  |  | jerkmate.com | 1 | script | `https://jerkmate.com/_next/static/chunks/pages/%5B...dynamic%5D-ef86e3989da47a94b9d8.js` |
| +32 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +32 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +29 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +29 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +26 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +26 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +22 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +22 |  |  | jerkmate.com | 1 | xhr | `https://api.jerkmate.com/api/models/live-status` |
| +22 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyNjkzMTA4NTYyLCJ0IjoxNjAyMzQ2Njk4fQ%3D%3D--5845593d869bc5831558f606cf7c302ee9997a04eba45d21ab63dd2c0a3ee461&shared=true |
| +21 |  |  | jerkmate.com | 1 | xhr | `https://gateway.jerkmate.com/session-api/session?referer=` |
| +21 |  |  | jerkmate.com | 1 | xhr | `https://gateway.jerkmate.com/session-api/session?referer=` |
| +19 |  |  | jerkmate.com | 3 | image | `https://cdn.camshq.info/streamate/10502648/profile.webp` |
| +19 |  |  | jerkmate.com | 3 | image | `https://cdn.camshq.info/streamate/47402264/profile.webp` |
| +19 |  |  | jerkmate.com | 3 | image | `https://cdn.camshq.info/streamate/91873792/profile.webp` |
| +19 |  |  | jerkmate.com | 3 | image | `https://cdn.camshq.info/streamate/51143188/profile.webp` |
| +19 |  |  | jerkmate.com | 3 | frame | `https://hybridclient.naiadsystems.com/purecam?performer=YELINAMOUNTAIN&performerid=78954882&volumelevel=0&widescreen=true&lang=en` |
| +19 |  |  | jerkmate.com | 3 | image | `https://cdn.camshq.info/streamate/10502648/profile.jpeg` |
| +19 |  |  | jerkmate.com | 3 | image | `https://cdn.camshq.info/streamate/47402264/profile.jpeg` |
| +19 |  |  | jerkmate.com | 3 | image | `https://cdn.camshq.info/streamate/91873792/profile.jpeg` |
| +19 |  |  | jerkmate.com | 3 | image | `https://cdn.camshq.info/streamate/51143188/profile.jpeg` |
| +19 | googletagmanager.com/gtm.js | << | jerkmate.com |  | script | `https://www.googletagmanager.com/gtm.js?id=GTM-W8XR2C2&gtm_auth=&gtm_preview=&gtm_cookies_win=x` |
| +19 | \|\|googletagmanager.com/gtm.js$script | -- | jerkmate.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-W8XR2C2&gtm_auth=&gtm_preview=&gtm_cookies_win=x` |
| +19 |  |  | jerkmate.com | 1 | script | `https://gateway.jerkmate.com/widgets/session-widget/latest/session-widget.min.js` |
| +19 |  |  | jerkmate.com | 1 | image | `https://jerkmate.com/static/icons/favicon-16x16.png` |
| +19 |  |  | jerkmate.com | 1 | image | `https://jerkmate.com/static/icons/apple-touch-icon.png` |
| +18 |  |  | jerkmate.com | 1 | script | `https://jerkmate.com/_next/static/CM6fXXAWmKX1b1f-fn3Wc/_ssgManifest.js` |
| +18 |  |  | jerkmate.com | 1 | script | `https://jerkmate.com/_next/static/CM6fXXAWmKX1b1f-fn3Wc/_buildManifest.js` |
| +18 |  |  | jerkmate.com | 1 | script | `https://jerkmate.com/_next/static/chunks/pages/index-5106d880b132bcbc6f79.js` |
| +18 |  |  | jerkmate.com | 1 | script | `https://jerkmate.com/_next/static/chunks/9d1c64aac3dc2b9bb5a21213c95f1ac66268a442.60da943605e1a0acbd34.js` |
| +18 |  |  | jerkmate.com | 1 | script | `https://jerkmate.com/_next/static/chunks/93b2d5152e07e271343c846382788379f6ba4864.d54eb0c7f3768d47b7bf.js` |
| +18 |  |  | jerkmate.com | 1 | script | `https://jerkmate.com/_next/static/chunks/ac7a69d6bfccb08d9cab12f905189999fb399b6b.2b93aa463e74b1c0fd51.js` |
| +18 |  |  | jerkmate.com | 1 | script | `https://jerkmate.com/_next/static/chunks/9429b27b2130a950d92f9767fd3c9028579cd8b7.518bbd83419923d0e691.js` |
| +18 |  |  | jerkmate.com | 1 | script | `https://jerkmate.com/_next/static/chunks/pages/_app-34066a9ca74aec966db7.js` |
| +18 |  |  | jerkmate.com | 1 | script | `https://jerkmate.com/_next/static/chunks/10d07d410722c9a45d1c05944e877cdc42272bf2.2b21b40aa168a896468f.js` |
| +18 |  |  | jerkmate.com | 1 | script | `https://jerkmate.com/_next/static/chunks/commons.ba11d06de4438d456ea2.js` |
| +18 |  |  | jerkmate.com | 1 | script | `https://jerkmate.com/_next/static/chunks/4c88a880.f5747a7dfc10eea71907.js` |
| +18 |  |  | jerkmate.com | 1 | script | `https://jerkmate.com/_next/static/chunks/framework.5e03480598ad1120f007.js` |
| +18 |  |  | jerkmate.com | 1 | script | `https://jerkmate.com/_next/static/chunks/webpack-ab7c2842be1a098dd7aa.js` |
| +18 |  |  | jerkmate.com | 1 | script | `https://jerkmate.com/_next/static/chunks/main-ef0cbea8e4b4e3ca4106.js` |
| +18 |  |  | jerkmate.com | 1 | font | `https://jerkmate.com/static/fonts/icomoon.ttf?eo5bm3` |
| +18 |  |  | jerkmate.com | 1 | font | `https://jerkmate.com/static/fonts/ProximaNova-Bold.woff2` |
| +18 |  |  | jerkmate.com | 1 | font | `https://jerkmate.com/static/fonts/ProximaNova-ExtraBold.woff2` |
| +18 |  |  | jerkmate.com | 1 | image | `https://jerkmate.com/static/images/ASACP.svg` |
| +18 |  |  | jerkmate.com | 1 | image | `https://jerkmate.com/static/images/RTA.svg` |
| +18 |  |  | jerkmate.com | 1 | image | `https://jerkmate.com/static/images/placeholder.jpg` |
| +18 |  |  | jerkmate.com | 3 | image | `https://cdn.camshq.info/streamate/10502648/profile_mini.jpeg` |
| +18 |  |  | jerkmate.com | 3 | image | `https://cdn.camshq.info/streamate/47402264/profile_mini.jpeg` |
| +18 |  |  | jerkmate.com | 3 | image | `https://cdn.camshq.info/streamate/91873792/profile_mini.jpeg` |
| +18 |  |  | jerkmate.com | 3 | image | `https://cdn.camshq.info/streamate/51143188/profile_mini.jpeg` |
| +18 |  |  | jerkmate.com | 1 | image | `https://jerkmate.com/static/images/jerky/jerky-love.svg` |
| +18 |  |  | jerkmate.com | 1 | image | `https://jerkmate.com/static/images/model.svg` |
| +18 |  |  | jerkmate.com | 1 | image | `https://gateway.jerkmate.com/cmscloud/dA/a2101b10-28b1-4df1-8cc9-a80b70a68b36/image/JERKY_blink-2.svg` |
| +18 |  |  | jerkmate.com | 1 | image | `https://jerkmate.com/static/images/ASACP-white.svg` |
| +18 |  |  | jerkmate.com | 1 | image | `https://jerkmate.com/static/images/RTA-white.svg` |
| +16 |  |  | jerkmate.com | 1 | doc | `https://jerkmate.com/` |
| +15 |  |  | jerkmate.com | 1 | doc | `http://jerkmate.com/` |
| +13 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyNjkzMTA4NTYyLCJ0IjoxNjAyMzQ2Njk4fQ%3D%3D--5845593d869bc5831558f606cf7c302ee9997a04eba45d21ab63dd2c0a3ee461&shared=true |
| +9 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyNjkzMTA4NTYyLCJ0IjoxNjAyMzQ2Njk4fQ%3D%3D--5845593d869bc5831558f606cf7c302ee9997a04eba45d21ab63dd2c0a3ee461&shared=true |
| +7 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyNjkzMTA4NTYyLCJ0IjoxNjAyMzQ2Njk4fQ%3D%3D--5845593d869bc5831558f606cf7c302ee9997a04eba45d21ab63dd2c0a3ee461&shared=true |
| +6 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyNjkzMTA4NTYyLCJ0IjoxNjAyMzQ2Njk4fQ%3D%3D--5845593d869bc5831558f606cf7c302ee9997a04eba45d21ab63dd2c0a3ee461&shared=true |
| +5 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +5 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +4 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MTQ2MjU1MjA4LCJ0IjoxNjAyMzQ2NjkyfQ%3D%3D--2bb21e00c7b3f0ab900590ed3cdc23ef457ba3f4be273f644cc6774f37828403&shared=true |
| +1 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MTQ2MjU1MjA4LCJ0IjoxNjAyMzQ2NjkyfQ%3D%3D--2bb21e00c7b3f0ab900590ed3cdc23ef457ba3f4be273f644cc6774f37828403&shared=true |
| +0 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MTQ2MjU1MjA4LCJ0IjoxNjAyMzQ2NjkyfQ%3D%3D--2bb21e00c7b3f0ab900590ed3cdc23ef457ba3f4be273f644cc6774f37828403&shared=true |
| +0 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +0 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
</details>
