### ISSUE TITLE
jerkmatelive.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#311]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
jerkmatelive.com
www.jerkmatelive.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-121659](https://user-images.githubusercontent.com/38778536/95642194-9e5a1800-0af2-11eb-9121-7108bdb39d86.png)

</details>

## External Info
- <https://www.mypdns.org/T904> (cambuilder.com)
- <https://www.mypdns.org/T1689> (nsimg.net)
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/hosts.txt)?
- [X] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
Related to <https://www.mypdns.org/T904> as it is a tracking domain as well, which means this site would already have been blocked by using RPZ :stuck_out_tongue: 

```shell
jerkmatelive.com.       172800  IN      NS      ns1.cambuilder.com.
jerkmatelive.com.       172800  IN      NS      ns2.cambuilder.com.
jerkmatelive.com.       3600    IN      A       207.246.147.249
jerkmatelive.com.       3600    IN      A       207.246.147.189
jerkmatelive.com.       3600    IN      A       207.246.147.190
jerkmatelive.com.       3600    IN      A       207.246.147.250

drill jerkmatelive.com   
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 33221
```
