### ISSUE TITLE
stripchat.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#312]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
stripchat.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-122118](https://user-images.githubusercontent.com/38778536/95642761-3b6a8000-0af6-11eb-923e-4fa0723a1eed.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/hosts.txt)?
- [X] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +84 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +76 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +72 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +70 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +69 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +46 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyNjMyODQyOTUzLCJ0IjoxNjAyMzUxOTk3fQ%3D%3D--8d43fb029055123ccc3e9043b568b8535e2f34619e4a310a6841f391a8a19cc9&shared=true |
| +14 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyNjMyODQyOTUzLCJ0IjoxNjAyMzUxOTk3fQ%3D%3D--8d43fb029055123ccc3e9043b568b8535e2f34619e4a310a6841f391a8a19cc9&shared=true |
| +8 | ##.cookies-reminder |  | stripchat.com |  | dom | `https://stripchat.com/` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu1/thumbs/1602351908/35415103_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu5/thumbs/1602351714/4555946_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu6/thumbs/1602351230/32460891_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu12/thumbs/1602351062/23819236_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu9/thumbs/1602351104/27286709_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu1/thumbs/1602351908/26591539_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu10/thumbs/1602351439/28277354_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu9/thumbs/1602351244/31134373_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu8/thumbs/1602351162/34915967_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu2/thumbs/1602351178/39624384_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu3/thumbs/1602351357/40181461_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu7/thumbs/1602351540/40575423_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu7/thumbs/1602351390/40517712_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us8/thumbs/1602351130/40839498_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us2/thumbs/1602351695/40137252_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us1/thumbs/1602351690/40370081_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us10/thumbs/1602351085/40945300_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu12/thumbs/1602351509/40587895_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us11/thumbs/1602351523/40333607_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/cdn/previews/6/9/6/6966c64477e4322b9da2b4e2bef7bad2-thumb-small` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us5/thumbs/1602351922/14258770_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us7/thumbs/1602351599/39997668_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu11/thumbs/1602351247/23752471_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us8/thumbs/1602351353/9238417_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us11/thumbs/1602351415/39037114_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu5/thumbs/1602351237/28236856_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us4/thumbs/1602351536/40269589_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us15/thumbs/1602351814/38183141_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us9/thumbs/1602351336/18007416_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us9/thumbs/1602351262/38686945_webp` |
| +7 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu2/thumbs/1602351743/29894276_webp` |
| +7 |  |  | stripchat.com | 1 | xhr | `https://stripchat.com/api/front/v2/models?limit=24&topLimit=60&favoritesLimit=24&primaryTag=girls&uniq=hls60tzkdngwj1bi` |
| +7 | google-analytics.com/analytics.js | << | stripchat.com |  | script | `https://www.google-analytics.com/analytics.js` |
| +7 | \|\|google-analytics.com^ | -- | stripchat.com | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +5 |  |  | stripchat.com | 3 | script | `https://creative.cmrdr.com/widgets/stripchat/init/index.js` |
| +5 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us1/thumbs/1602351801/11610524_webp` |
| +5 |  |  | stripchat.com | 3 | script | `https://cdn.stripst.com/assets/perfect-scrollbar.20201009130237.js` |
| +4 |  |  | stripchat.com | 3 | websocket | wss://cometmaster.com/comet2?auth=51294ef68859694c7525a2e016efef11bebd7b3bee2d40b22c344fddefff&host=stripchat.com |
| +4 |  |  | stripchat.com | 1 | xhr | `https://stripchat.com/api/front/purchase/digest/promo?uniq=07ih91mgvyd4raxz` |
| +4 | \|\|trafficjunky.net^$3p | -- | stripchat.com | 3 | image | `https://ctrack.trafficjunky.net/ctrack?action=list&type=add&id=0&context=stripcash&cookiename=vzt&maxcookiecount=10` |
| +4 | \|\|main.exoclick.com/tag.php | -- | stripchat.com | 3 | image | `https://main.exoclick.com/tag.php?goal=044b09dc771f0762cab84943b121d46b` |
| +4 | \|\|tsyndicate.com^$3p | -- | stripchat.com | 3 | image | `https://tsyndicate.com/api/v1/retargeting/set/769e3c28-7ed6-47d4-a575-9d2c513403c0?visit=1` |
| +4 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/icons/favicon-16x16.png` |
| +4 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/icons/favicon-196x196.png` |
| +4 | ##.footer-social-link |  | stripchat.com |  | dom | `https://stripchat.com/` |
| +3 | `##[href^="https://twitter.com"]` |  | stripchat.com |  | dom | `https://stripchat.com/` |
| +2 |  |  | stripchat.com | 3 | script | `https://cdn.stripst.com/assets/main.20201009130237.js` |
| +2 |  |  | stripchat.com | 3 | script | `https://cdn.stripst.com/assets/shared.20201009130237.js` |
| +2 |  |  | stripchat.com | 3 | script | `https://cdn.stripst.com/assets/runtime.20201009130237.js` |
| +2 |  |  | stripchat.com | 3 | script | `https://cdn.stripst.com/assets/vendors.20201009130237.js` |
| +2 |  |  | stripchat.com | 3 | script | `https://cdn.stripst.com/assets/translations_en.20201009133539.js` |
| +2 |  |  | stripchat.com | 3 | script | `https://cdn.stripst.com/assets/seo_translations_en.20201009133539.js` |
| +2 | \|\|amplitude.com^$3p | -- | stripchat.com | 3 | script | `https://cdn.amplitude.com/libs/amplitude-4.5.2-min.gz.js` |
| +2 |  |  | stripchat.com | 1 | image | `https://stripchat.com/pixel/agreement/display` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/icons/footerlogo.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu10/thumbs/1602351531/23273298_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/components/ui/CountryFlag/images/in.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu10/thumbs/1602351899/23031339_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu7/thumbs/1602351153/4740134_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us12/thumbs/1602351202/27195786_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu2/thumbs/1602351091/5210528_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu11/thumbs/1602351440/5761807_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us10/thumbs/1602351503/7434026_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu10/thumbs/1602351162/29505582_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu4/thumbs/1602351065/11106527_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu11/thumbs/1602351440/7184688_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu7/thumbs/1602351675/23620137_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us17/thumbs/1602351284/40863334_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu9/thumbs/1602351689/23574348_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu12/thumbs/1602351546/31274986_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu12/thumbs/1602351102/15594244_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu7/thumbs/1602351322/31310288_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu8/thumbs/1602351410/2052104_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu2/thumbs/1602351253/3097060_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us17/thumbs/1602351207/13322293_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us9/thumbs/1602351628/36877830_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu8/thumbs/1602351162/40720489_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu2/thumbs/1602351741/36433974_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu3/thumbs/1602351787/32259175_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu3/thumbs/1602351831/40857059_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu6/thumbs/1602351838/24119274_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us16/thumbs/1602351634/35199429_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us1/thumbs/1602351690/33510745_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu11/thumbs/1602351440/26932085_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu10/thumbs/1602351292/30550559_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu5/thumbs/1602351671/32033054_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu10/thumbs/1602351439/22940775_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/components/ui/CountryFlag/images/de.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu8/thumbs/1602351671/330079_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu4/thumbs/1602351065/32780701_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu3/thumbs/1602351573/15360692_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu3/thumbs/1602351530/40182672_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu12/thumbs/1602351250/39618326_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu2/thumbs/1602351178/32779120_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu12/thumbs/1602351658/32054846_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu11/thumbs/1602351824/35821237_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu5/thumbs/1602351074/22946361_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu12/thumbs/1602351658/40578496_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu1/thumbs/1602351130/5195378_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu11/thumbs/1602351440/4838136_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu12/thumbs/1602351250/17520390_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu4/thumbs/1602351458/21392282_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us12/thumbs/1602351332/40752456_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us19/thumbs/1602351398/40540029_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu11/thumbs/1602351700/35388796_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu6/thumbs/1602351500/40768501_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu3/thumbs/1602351787/40454377_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us21/thumbs/1602351569/38683552_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu11/thumbs/1602351440/40888610_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu2/thumbs/1602351668/40460502_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu4/thumbs/1602351237/19309468_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu1/thumbs/1602351606/40279883_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/components/ui/CountryFlag/images/ua.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu6/thumbs/1602351230/40828639_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu6/thumbs/1602351500/32329493_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us2/thumbs/1602351844/34531827_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu11/thumbs/1602351700/22301571_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu2/thumbs/1602351825/5414111_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/components/ui/CountryFlag/images/ru.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu7/thumbs/1602351390/18261895_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us9/thumbs/1602351079/35197189_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/components/ui/CountryFlag/images/co.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us14/thumbs/1602351527/23944385_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/components/ui/CountryFlag/images/ve.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us18/thumbs/1602351445/16973129_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu10/thumbs/1602351439/25542947_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us2/thumbs/1602351094/23253425_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/components/ui/CountryFlag/images/us.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us9/thumbs/1602351262/37882473_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu4/thumbs/1602351311/15529109_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu2/thumbs/1602351253/37826607_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu6/thumbs/1602351500/11705132_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu5/thumbs/1602351346/30773540_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/components/ui/CountryFlag/images/th.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu1/thumbs/1602351260/29559103_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us17/thumbs/1602351207/26019093_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu2/thumbs/1602351327/40256559_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu9/thumbs/1602351615/20900693_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us7/thumbs/1602351148/13971979_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/components/ui/CountryFlag/images/ro.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/eu6/thumbs/1602351500/23022125_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us7/thumbs/1602351715/2935682_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us18/thumbs/1602351097/30986000_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://img.stripst.com/us18/thumbs/1602351445/22879085_webp` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/components/ui/CountryFlag/images/scan.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/images/sc-ultimate-modifier.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/images/sc-gold-modifier.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/images/sc-logo-trans.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/images/sc-logo-guys.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/images/sc-logo-original.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/images/asacp.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/images/safe-labeling.svg` |
| +2 |  |  | stripchat.com | 3 | image | `https://cdn.stripst.com/assets/common/images/rta-logo.svg` |
| +1 |  |  | stripchat.com | 3 | script | `https://cdn.stripst.com/assets/svg-injector-icons.33591750a4b8c03365f6761c3aea743c4211cfb5.js` |
| +1 |  |  | stripchat.com | 3 | css | `https://cdn.stripst.com/assets/styles.20201009130237.css` |
| +1 |  |  | stripchat.com | 1 | doc | `https://stripchat.com/` |
| +0 |  |  | `www.stripchat.com` | 1 | doc | `https://www.stripchat.com/` |
| +0 |  |  | `www.stripchat.com` | 1 | doc | `http://www.stripchat.com/` |
</details>
