### ISSUE TITLE
xxxselected.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#313]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
xxxselected.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-125438](https://user-images.githubusercontent.com/38778536/95642980-eb8cb880-0af7-11eb-81ef-827e599d2509.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/hosts.txt)?
- [X] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
```python
static.xxxselected.com
```

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +105 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +88 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +80 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +76 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +74 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +73 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +72 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxMjY0NDU2MDQ2LCJ0IjoxNjAyMzUzOTM5fQ%3D%3D--103b15c79c64c2c312ff50bc32a30a287f8a347212e1c84a105be511e1436f35&shared=true |
| +44 | ##.js-notify-cookie |  | xxxselected.com |  | dom | `https://xxxselected.com/` |
| +44 | \|\|wpush.org^$3p | -- | xxxselected.com | 3 | script | `https://sw.wpush.org/script/main.js?promo=26533&tcid=4942&src=1127398955` |
| +44 |  |  | xxxselected.com | 1 | image | `https://xxxselected.com/images/xxxselected/favicon.png` |
| +44 |  |  | xxxselected.com | 1 | xhr | `https://xxxselected.com/api/countryCode` |
| +44 |  |  | xxxselected.com | 1 | font | `https://static.xxxselected.com/fonts/PT_Sans-Web-Italic.ttf` |
| +44 |  |  | xxxselected.com | 1 | font | `https://static.xxxselected.com/fonts/PT_Sans-Web-Bold.ttf` |
| +44 |  |  | xxxselected.com | 1 | font | `https://static.xxxselected.com/fonts/PT_Sans-Web-Regular.ttf` |
| +44 | google-analytics.com/analytics.js | << | xxxselected.com |  | script | `https://www.google-analytics.com/analytics.js` |
| +44 | \|\|google-analytics.com^ | -- | xxxselected.com | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +44 |  |  | xxxselected.com | 1 | script | `https://static.xxxselected.com/dist/js/secondary.js?hash=1587641059` |
| +44 |  |  | xxxselected.com | 1 | script | `https://static.xxxselected.com/dist/js/floater.js?hash=1587641059` |
| +44 |  |  | xxxselected.com | 1 | script | `https://static.xxxselected.com/dist/js/bought.js?hash=1587641059` |
| +44 |  |  | xxxselected.com | 1 | script | `https://static.xxxselected.com/dist/js/primary.js?hash=1587641059` |
| +43 |  |  | xxxselected.com | 1 | doc | `https://xxxselected.com/` |
| +43 |  |  | `www.xxxselected.com` | 1 | doc | `http://www.xxxselected.com/` |
| +39 |  |  | xxxselected.com | 1 | image | `https://xxxselected.com/images/xxxselected/favicon.png` |
| +39 |  |  | xxxselected.com | 1 | image | `https://xxxselected.com/favicon.ico` |
| +39 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxMjY0NDU2MDQ2LCJ0IjoxNjAyMzUzOTM5fQ%3D%3D--103b15c79c64c2c312ff50bc32a30a287f8a347212e1c84a105be511e1436f35&shared=true |
| +38 | ##img[width="88"][height="31"] |  | `www.hdpornos.net` |  | dom | `https://www.hdpornos.net/` |
| +38 | ##.fa-rss |  | `www.hdpornos.net` |  | dom | `https://www.hdpornos.net/` |
| +38 | ###advertise |  | `www.hdpornos.net` |  | dom | `https://www.hdpornos.net/` |
| +38 | \|\|fabrouter.com^ | -- | `www.hdpornos.net` | 3 | xhr | `https://delivery.fabrouter.com/cpanel/f.php?t=MTI3Mzs2NTc5O3NxdWFyZS5tZWRpdW1fcmVjdGFuZ2xl&index=1&nf=1&sid=&rand=804186&dv=87b9f_3&cf=0` |
| +38 | \|\|fabrouter.com^ | -- | `www.hdpornos.net` | 3 | xhr | `https://delivery.fabrouter.com/cpanel/f.php?t=MTI3Mzs2NTc4O3NxdWFyZS5tZWRpdW1fcmVjdGFuZ2xl&index=1&nf=1&sid=&rand=383106&dv=87b9f_2&cf=0` |
| +38 | \|\|fabrouter.com^ | -- | `www.hdpornos.net` | 3 | xhr | `https://delivery.fabrouter.com/cpanel/f.php?t=MTI3Mzs2NTc3O3NxdWFyZS5tZWRpdW1fcmVjdGFuZ2xl&index=1&nf=1&sid=&rand=421088&dv=87b9f_1&cf=0` |
| +38 |  |  | `www.hdpornos.net` | 1 | image | `https://www.hdpornos.net/favicon.ico` |
| +38 |  |  | `www.hdpornos.net` | 1 | image | `https://static.hdpornos.net/img/icons/apple-touch-icon-180x180.png` |
| +38 | \|\|chatintr.com/widget?affiliateid=1$subdocument | -- | `www.hdpornos.net` | 3 | frame | `https://chatintr.com/widget?affiliateId=1` |
| +38 | \|\|pushpad.xyz^$3p | -- | `www.hdpornos.net` | 3 | script | `https://pushpad.xyz/pushpad.js` |
| +38 |  |  | `www.hdpornos.net` | 3 | script | `https://static2.twincdn.com/special/special_script.js` |
| +38 | google-analytics.com/analytics.js | << | `www.hdpornos.net` |  | script | `https://www.google-analytics.com/analytics.js` |
| +38 | \|\|google-analytics.com^ | -- | `www.hdpornos.net` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +37 |  |  | `www.hdpornos.net` | 1 | doc | `https://www.hdpornos.net/` |
| +21 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxMjY0NDU2MDQ2LCJ0IjoxNjAyMzUzOTM5fQ%3D%3D--103b15c79c64c2c312ff50bc32a30a287f8a347212e1c84a105be511e1436f35&shared=true |
| +21 | ##.js-notify-cookie |  | xxxselected.com |  | dom | `https://xxxselected.com/` |
| +21 | \|\|wpush.org^$3p | -- | xxxselected.com | 3 | script | `https://sw.wpush.org/script/main.js?promo=26533&tcid=4942&src=1127398955` |
| +21 |  |  | xxxselected.com | 1 | image | `https://xxxselected.com/images/xxxselected/favicon.png` |
| +21 |  |  | xxxselected.com | 1 | xhr | `https://xxxselected.com/api/countryCode` |
| +21 |  |  | xxxselected.com | 1 | font | `https://static.xxxselected.com/fonts/PT_Sans-Web-Italic.ttf` |
| +21 |  |  | xxxselected.com | 1 | font | `https://static.xxxselected.com/fonts/PT_Sans-Web-Bold.ttf` |
| +21 |  |  | xxxselected.com | 1 | font | `https://static.xxxselected.com/fonts/PT_Sans-Web-Regular.ttf` |
| +21 | google-analytics.com/analytics.js | << | xxxselected.com |  | script | `https://www.google-analytics.com/analytics.js` |
| +21 | \|\|google-analytics.com^ | -- | xxxselected.com | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +21 |  |  | xxxselected.com | 1 | script | `https://static.xxxselected.com/dist/js/secondary.js?hash=1587641059` |
| +21 |  |  | xxxselected.com | 1 | script | `https://static.xxxselected.com/dist/js/floater.js?hash=1587641059` |
| +21 |  |  | xxxselected.com | 1 | script | `https://static.xxxselected.com/dist/js/bought.js?hash=1587641059` |
| +21 |  |  | xxxselected.com | 1 | script | `https://static.xxxselected.com/dist/js/primary.js?hash=1587641059` |
| +20 |  |  | xxxselected.com | 1 | doc | `https://xxxselected.com/` |
| +20 |  |  | `www.xxxselected.com` | 1 | doc | `http://www.xxxselected.com/` |
| +13 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxMjY0NDU2MDQ2LCJ0IjoxNjAyMzUzOTM5fQ%3D%3D--103b15c79c64c2c312ff50bc32a30a287f8a347212e1c84a105be511e1436f35&shared=true |
| +13 | \|\|wpush.org^$3p | -- | xxxselected.com | 3 | script | `https://sw.wpush.org/script/main.js?promo=26533&tcid=4942&src=1127398955` |
| +13 | ##.js-notify-cookie |  | xxxselected.com |  | dom | `https://xxxselected.com/` |
| +13 |  |  | xxxselected.com | 1 | image | `https://xxxselected.com/images/xxxselected/favicon.png` |
| +12 |  |  | xxxselected.com | 1 | xhr | `https://xxxselected.com/api/countryCode` |
| +12 |  |  | xxxselected.com | 1 | font | `https://static.xxxselected.com/fonts/PT_Sans-Web-Italic.ttf` |
| +12 |  |  | xxxselected.com | 1 | font | `https://static.xxxselected.com/fonts/PT_Sans-Web-Bold.ttf` |
| +12 |  |  | xxxselected.com | 1 | font | `https://static.xxxselected.com/fonts/PT_Sans-Web-Regular.ttf` |
| +12 | google-analytics.com/analytics.js | << | xxxselected.com |  | script | `https://www.google-analytics.com/analytics.js` |
| +12 | \|\|google-analytics.com^ | -- | xxxselected.com | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +12 |  |  | xxxselected.com | 1 | image | `https://static.xxxselected.com/images/xxxselected/down_chew.svg` |
| +12 |  |  | xxxselected.com | 1 | image | `https://static.xxxselected.com/images/xxxselected/sort_ico.svg` |
| +12 |  |  | xxxselected.com | 1 | image | `https://static.xxxselected.com/images/cancel.svg` |
| +12 |  |  | xxxselected.com | 1 | image | `https://static.xxxselected.com/images/xxxselected/search.svg` |
| +12 |  |  | xxxselected.com | 1 | image | `https://static.xxxselected.com/images/xxxselected/logo.png?hash=1` |
| +12 |  |  | xxxselected.com | 1 | script | `https://static.xxxselected.com/dist/js/secondary.js?hash=1587641059` |
| +12 |  |  | xxxselected.com | 1 | css | `https://static.xxxselected.com/dist/css/secondary.css?hash=1587641059` |
| +12 |  |  | xxxselected.com | 1 | script | `https://static.xxxselected.com/dist/js/floater.js?hash=1587641059` |
| +12 |  |  | xxxselected.com | 1 | script | `https://static.xxxselected.com/dist/js/bought.js?hash=1587641059` |
| +12 |  |  | xxxselected.com | 1 | script | `https://static.xxxselected.com/dist/js/primary.js?hash=1587641059` |
| +12 |  |  | xxxselected.com | 1 | css | `https://static.xxxselected.com/dist/css/primary.css?hash=1587641059` |
| +11 |  |  | xxxselected.com | 1 | doc | `https://xxxselected.com/` |
| +11 |  |  | xxxselected.com | 1 | doc | `http://xxxselected.com/` |
| +9 |  |  | `www.hdpornos.net` | 3 | media | `https://ovhv8.twincdn.com/previews/68/68652/preview.mp4` |
| +9 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxMjY0NDU2MDQ2LCJ0IjoxNjAyMzUzOTM5fQ%3D%3D--103b15c79c64c2c312ff50bc32a30a287f8a347212e1c84a105be511e1436f35&shared=true |
| +6 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxMjY0NDU2MDQ2LCJ0IjoxNjAyMzUzOTM5fQ%3D%3D--103b15c79c64c2c312ff50bc32a30a287f8a347212e1c84a105be511e1436f35&shared=true |
| +4 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxMjY0NDU2MDQ2LCJ0IjoxNjAyMzUzOTM5fQ%3D%3D--103b15c79c64c2c312ff50bc32a30a287f8a347212e1c84a105be511e1436f35&shared=true |
| +4 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +4 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +0 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMjc3ODcxMzkwLCJ0IjoxNjAyMzUzOTE5fQ%3D%3D--b0e5ef4226fc9de2f3cf8951a954fac1a5d5921d1856da77c74debe987e628f3&shared=true |
</details>
