### ISSUE TITLE
handjobhub.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#317]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
handjobhub.com
cdn.handjobhub.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-214201](https://user-images.githubusercontent.com/38778536/95653100-a55c4700-0b41-11eb-8d94-8390c78e68f4.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/hosts.txt)?
- [X] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +28 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozNTI0NDMwNTQ0LCJ0IjoxNjAyMzU0MzQwfQ%3D%3D--6be89ea02f88cb76520b7917a1cab5944666b747ab47a573366064de5b0b5161&shared=true |
| +23 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/templates/default_tube2016/images/touch/fav.png` |
| +23 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/templates/default_tube2016/images/touch/chrome-touch-icon-192x192.png` |
| +23 | ##.i-rss |  | handjobhub.com |  | dom | `https://handjobhub.com/` |
| +23 | ###scrollUp:not(body):not(html) |  | handjobhub.com |  | dom | `https://handjobhub.com/` |
| +23 | ##a[title="RSS"] |  | handjobhub.com |  | dom | `https://handjobhub.com/` |
| +23 | ##.aff-inner-col |  | handjobhub.com |  | dom | `https://handjobhub.com/` |
| +23 | ##.aff-content-col |  | handjobhub.com |  | dom | `https://handjobhub.com/` |
| +22 |  |  | handjobhub.com | 1 | image | `https://cdn.handjobhub.com/thumbs/4/f/9/a/5/4f9a52b19b4ccfile6449be0a90fd30820ebaf82405e94aa2.avi/4f9a52b19b4ccfile6449be0a90fd30820ebaf82405e94aa2.avi-6.jpg` |
| +22 |  |  | handjobhub.com | 1 | image | `https://cdn.handjobhub.com/thumbs/5/1/d/c/e/51da240fce61cGlorious%20Handjob%20Compilation.wmv/51da240fce61cGlorious%20Handjob%20Compilation.wmv-5.jpg` |
| +22 |  |  | handjobhub.com | 1 | image | `https://cdn.handjobhub.com/thumbs/4/f/8/1/f/4f81f3eb1ab240002.avi/4f81f3eb1ab240002.avi-3.jpg` |
| +22 |  |  | handjobhub.com | 1 | image | `https://cdn.handjobhub.com/thumbs/5/c/4/7/f/16245c3630d78f7c6.mp4/16245c3630d78f7c6.mp4-5.jpg` |
| +22 |  |  | handjobhub.com | 1 | image | `https://cdn.handjobhub.com/thumbs/5/d/b/8/a/5db2393acd55f9.66844965.mp4/5db2393acd55f9.66844965.mp4-3.jpg` |
| +22 |  |  | handjobhub.com | 1 | image | `https://cdn.handjobhub.com/thumbs/1/6/2/4/5/1624522dbfb4733a3.mp4/1624522dbfb4733a3.mp4-3.jpg` |
| +22 |  |  | handjobhub.com | 1 | image | `https://cdn.handjobhub.com/misc/cat16.jpg` |
| +22 |  |  | handjobhub.com | 1 | image | `https://cdn.handjobhub.com/misc/cat25.jpg` |
| +22 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/templates/default_tube2016/images/lightbox/close.png` |
| +22 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/templates/default_tube2016/images/lightbox/loading.gif` |
| +22 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/templates/default_tube2016/images/lightbox/next.png` |
| +22 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/templates/default_tube2016/images/lightbox/prev.png` |
| +22 | \|\|getscriptjs.com^$3p | -- | handjobhub.com | 3 | script | `https://getscriptjs.com/p.js` |
| +22 | /sp/delivery/* | -- | handjobhub.com | 1 | script | `https://handjobhub.com/sp/delivery/js.php?advplaces=17` |
| +22 | /sp/delivery/* | -- | handjobhub.com | 1 | script | `https://www.handjobhub.com/sp/delivery/js.php?advplaces=12` |
| +22 | /sp/delivery/* | -- | handjobhub.com | 1 | script | `https://www.handjobhub.com/sp/delivery/js.php?advplaces=11` |
| +22 | /sp/delivery/* | -- | handjobhub.com | 1 | script | `https://www.handjobhub.com/sp/delivery/js.php?advplaces=10` |
| +22 | /sp/delivery/* | -- | handjobhub.com | 1 | script | `https://www.handjobhub.com/sp/delivery/js.php?advplaces=4` |
| +22 | /sp/delivery/* | -- | handjobhub.com | 1 | script | `https://www.handjobhub.com/sp/delivery/js.php?advplaces=2` |
| +22 |  |  | handjobhub.com | 1 | font | `https://handjobhub.com/templates/default_tube2016/fonts/fontawesome/fontawesome-webfont.woff?v=4.5.0` |
| +22 | /sp/delivery/* | -- | handjobhub.com | 1 | script | `https://www.handjobhub.com/sp/delivery/js.php?advplaces=9` |
| +22 | \|\|googletagmanager.com/gtag/$3p | -- | handjobhub.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-28046178-1` |
| +22 | \|\|googleapis.com^$important | -- | handjobhub.com | 3 | script | `https://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js` |
| +21 | \|\|googleapis.com^$important | -- | handjobhub.com | 3 | css | `https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic&subset=latin,latin-ext` |
| +21 | \|\|getscriptjs.com^$3p | -- | handjobhub.com | 3 | script | `https://getscriptjs.com/p.js` |
| +21 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/te3/thumbs/handjob-handjob.com_1_4.jpg` |
| +21 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/te3/thumbs/88gals.com_1_1.jpg` |
| +21 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/te3/thumbs/livehandjob.com_1_3.jpg` |
| +21 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/te3/toplist/notfound.gif` |
| +21 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/te3/thumbs/pornwaiter.com_1_3.jpg` |
| +21 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/te3/thumbs/8teenxxx.com_1_4.jpg` |
| +21 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/te3/thumbs/handjob-tube.com_1_3.jpg` |
| +21 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/te3/thumbs/bestcfnmvideos.com_1_1.jpg` |
| +21 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/te3/thumbs/cfnmhandjobvideos.com_1_3.jpg` |
| +21 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/images/bestpaypornsites-favicon.png` |
| +21 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/core/images/flags/en.png` |
| +21 |  |  | handjobhub.com | 1 | image | `https://handjobhub.com/templates/default_tube2016/images/logo.png` |
| +21 | \|\|googletagmanager.com/gtag/$3p | -- | handjobhub.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-28046178-1` |
| +21 |  |  | handjobhub.com | 1 | script | `https://handjobhub.com/templates/default_tube2016/js/jquery.cookies.js` |
| +21 |  |  | handjobhub.com | 1 | script | `https://handjobhub.com/templates/default_tube2016/js/jquery.browser.min.js` |
| +21 |  |  | handjobhub.com | 1 | script | `https://handjobhub.com/core/js/Tube.js` |
| +21 |  |  | handjobhub.com | 1 | script | `https://handjobhub.com/templates/default_tube2016/js/functions.min.js` |
| +21 |  |  | handjobhub.com | 1 | css | `https://handjobhub.com/templates/default_tube2016/css/custom.css` |
| +21 |  |  | handjobhub.com | 1 | css | `https://handjobhub.com/templates/default_tube2016/css/overwrite.css` |
| +21 |  |  | handjobhub.com | 1 | css | `https://handjobhub.com/templates/default_tube2016/css/styles.css` |
| +20 |  |  | handjobhub.com | 1 | doc | `https://handjobhub.com/` |
| +19 |  |  | `www.handjobhub.com` | 1 | doc | `http://www.handjobhub.com/` |
| +6 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +6 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +0 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +0 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
</details>
