### ISSUE TITLE
pornoreino.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#318]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
www.pornoreino.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-214542](https://user-images.githubusercontent.com/38778536/95653165-2f0c1480-0b42-11eb-9420-af1bdeac357e.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +33 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MDQwODg2MjQxLCJ0IjoxNjAyMzU0MjU1fQ%3D%3D--e9bc92fbf300c9f281b9c3551b0adee11af5397f4f7ee5aa844edf9d3426e847&shared=true |
| +6 | ##.social-bookmarks |  | `www.pornoreino.com` |  | dom | `https://www.pornoreino.com/` |
| +6 | &action=js_stats& | -- | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/?mode=async&action=js_stats&rand=1602354276795` |
| +6 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/static/icons/favicon-16x16.png` |
| +6 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/static/icons/apple-touch-icon.png` |
| +6 | \|\|realsrv.com^ | -- | `www.pornoreino.com` | 3 | script | `https://a.realsrv.com/popunder1000.js` |
| +5 | \|\|realsrv.com^ | -- | `www.pornoreino.com` | 3 | script | `https://a.realsrv.com/video-slider.js` |
| +5 | \|\|eroadvertising.com^$3p | -- | `www.pornoreino.com` | 3 | script | `https://go.eroadvertising.com/loadeactrl.go?pid=73041&siteid=122132&spaceid=3536998` |
| +5 | \|\|realsrv.com^ | -- | `www.pornoreino.com` | 3 | script | `https://a.realsrv.com/ads.js` |
| +5 |  |  | `www.pornoreino.com` | 1 | font | `https://www.pornoreino.com/static/fonts/roboto-slab-v11-latin-900.woff2` |
| +5 |  |  | `www.pornoreino.com` | 1 | font | `https://www.pornoreino.com/static/fonts/balsamiq-sans-v1-latin-regular.woff2` |
| +5 | \|\|realsrv.com^ | -- | `www.pornoreino.com` | 3 | script | `https://a.realsrv.com/ads.js` |
| +5 | \|\|realsrv.com^ | -- | `www.pornoreino.com` | 3 | script | `https://a.realsrv.com/video-slider.js` |
| +5 |  |  | `www.pornoreino.com` | 1 | script | `https://www.pornoreino.com/static/js/functions.js` |
| +5 |  |  | `www.pornoreino.com` | 1 | script | `https://www.pornoreino.com/static/js/main.min.js` |
| +5 | \|\|realsrv.com^ | -- | `www.pornoreino.com` | 3 | script | `https://a.realsrv.com/ads.js` |
| +5 | \|\|realsrv.com^ | -- | `www.pornoreino.com` | 3 | script | `https://a.realsrv.com/nativeads-v2.js` |
| +5 |  |  | `www.pornoreino.com` | 1 | font | `https://www.pornoreino.com/static/images/fonts/icomoon.ttf?nddhpi` |
| +5 |  |  | `www.pornoreino.com` | 1 | font | `https://www.pornoreino.com/static/fonts/roboto-slab-v11-latin-700.woff2` |
| +5 |  |  | `www.pornoreino.com` | 1 | font | `https://www.pornoreino.com/static/fonts/roboto-slab-v11-latin-regular.woff2` |
| +5 | \|\|cdn.jsdelivr.net/npm/yandex-metrica-watch/watch.js | -- | `www.pornoreino.com` | 3 | script | `https://cdn.jsdelivr.net/npm/yandex-metrica-watch/watch.js` |
| +5 | \|\|googletagmanager.com/gtag/$3p | -- | `www.pornoreino.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-63782772-1` |
| +5 | \|\|googletagmanager.com/gtag/$3p | -- | `www.pornoreino.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-63782772-1` |
| +5 | \|\|wpnsrv.com^ | -- | `www.pornoreino.com` | 3 | script | `https://js.wpnsrv.com/pn.php` |
| +5 | ##+js(abort-on-property-read, open) |  | `www.pornoreino.com` |  | dom | `https://www.pornoreino.com/` |
| +5 | ##+js(abort-on-property-read, ExoLoader) |  | `www.pornoreino.com` |  | dom | `https://www.pornoreino.com/` |
| +5 |  |  | `www.pornoreino.com` | 1 | doc | `https://www.pornoreino.com/` |
| +4 |  |  | pornoreino.com | 1 | doc | `https://pornoreino.com/` |
| +4 |  |  | pornoreino.com | 1 | doc | `http://pornoreino.com/` |
| +2 | ##.social-bookmarks |  | `www.pornoreino.com` |  | dom | `https://www.pornoreino.com/` |
| +2 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/contents/videos_screenshots/72000/72526/320x180/2.jpg` |
| +2 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/contents/videos_screenshots/27000/27309/320x180/1.jpg` |
| +2 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/contents/videos_screenshots/24000/24335/320x180/1.jpg` |
| +2 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/contents/videos_screenshots/1000/1252/320x180/1.jpg` |
| +2 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/contents/videos_screenshots/44000/44409/320x180/4.jpg` |
| +2 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/contents/videos_screenshots/74000/74927/320x180/2.jpg` |
| +2 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/contents/videos_screenshots/70000/70453/320x180/1.jpg` |
| +2 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/contents/videos_screenshots/36000/36574/320x180/8.jpg` |
| +2 | &action=js_stats& | -- | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/?mode=async&action=js_stats&rand=1602354272906` |
| +2 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/static/icons/favicon-16x16.png` |
| +2 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/static/icons/apple-touch-icon.png` |
| +2 | \|\|realsrv.com^ | -- | `www.pornoreino.com` | 3 | script | `https://a.realsrv.com/popunder1000.js` |
| +1 | \|\|realsrv.com^ | -- | `www.pornoreino.com` | 3 | script | `https://a.realsrv.com/video-slider.js` |
| +1 |  |  | `www.pornoreino.com` | 1 | font | `https://www.pornoreino.com/static/fonts/roboto-slab-v11-latin-900.woff2` |
| +1 |  |  | `www.pornoreino.com` | 1 | font | `https://www.pornoreino.com/static/fonts/balsamiq-sans-v1-latin-regular.woff2` |
| +1 |  |  | `www.pornoreino.com` | 1 | font | `https://www.pornoreino.com/static/images/fonts/icomoon.ttf?nddhpi` |
| +1 |  |  | `www.pornoreino.com` | 1 | font | `https://www.pornoreino.com/static/fonts/roboto-slab-v11-latin-700.woff2` |
| +1 |  |  | `www.pornoreino.com` | 1 | font | `https://www.pornoreino.com/static/fonts/roboto-slab-v11-latin-regular.woff2` |
| +1 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/static/images/videos_bg.jpg` |
| +1 | \|\|realsrv.com^ | -- | `www.pornoreino.com` | 3 | script | `https://a.realsrv.com/nativeads-v2.js` |
| +1 | \|\|realsrv.com^ | -- | `www.pornoreino.com` | 3 | script | `https://a.realsrv.com/video-slider.js` |
| +1 |  |  | `www.pornoreino.com` | 1 | script | `https://www.pornoreino.com/static/js/functions.js` |
| +1 |  |  | `www.pornoreino.com` | 1 | script | `https://www.pornoreino.com/static/js/main.min.js` |
| +1 | \|\|realsrv.com^ | -- | `www.pornoreino.com` | 3 | script | `https://a.realsrv.com/nativeads-v2.js` |
| +1 |  |  | `www.pornoreino.com` | 1 | font | `https://www.pornoreino.com/static/fonts/roboto-slab-v11-latin-900.woff2` |
| +1 |  |  | `www.pornoreino.com` | 1 | font | `https://www.pornoreino.com/static/images/fonts/icomoon.ttf?nddhpi` |
| +1 |  |  | `www.pornoreino.com` | 1 | font | `https://www.pornoreino.com/static/fonts/roboto-slab-v11-latin-700.woff2` |
| +1 |  |  | `www.pornoreino.com` | 1 | font | `https://www.pornoreino.com/static/fonts/roboto-slab-v11-latin-regular.woff2` |
| +1 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/static/flags/pt.svg` |
| +1 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/static/flags/us.svg` |
| +1 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/static/flags/es.svg` |
| +1 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/static/images/search.svg` |
| +1 | \|\|cdn.jsdelivr.net/npm/yandex-metrica-watch/watch.js | -- | `www.pornoreino.com` | 3 | script | `https://cdn.jsdelivr.net/npm/yandex-metrica-watch/watch.js` |
| +1 | \|\|googletagmanager.com/gtag/$3p | -- | `www.pornoreino.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-63782772-1` |
| +1 |  |  | `www.pornoreino.com` | 1 | image | `https://www.pornoreino.com/static/images/logo_pr2.png` |
| +1 | \|\|googletagmanager.com/gtag/$3p | -- | `www.pornoreino.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-63782772-1` |
| +1 | \|\|wpnsrv.com^ | -- | `www.pornoreino.com` | 3 | script | `https://js.wpnsrv.com/pn.php` |
| +1 |  |  | `www.pornoreino.com` | 1 | css | `https://www.pornoreino.com/static/styles/style.css` |
| +1 | ##+js(abort-on-property-read, open) |  | `www.pornoreino.com` |  | dom | `https://www.pornoreino.com/` |
| +1 | ##+js(abort-on-property-read, ExoLoader) |  | `www.pornoreino.com` |  | dom | `https://www.pornoreino.com/` |
| +0 |  |  | `www.pornoreino.com` | 1 | doc | `https://www.pornoreino.com/` |
| +0 |  |  | `www.pornoreino.com` | 1 | doc | `http://www.pornoreino.com/` |
</details>
