### ISSUE TITLE
bigcocker.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#319]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
bigcocker.com
www.bigcocker.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-215218](https://user-images.githubusercontent.com/38778536/95653244-0afd0300-0b43-11eb-81f9-7ce46417c745.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +44 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozMDY4NDc3MzQ5LCJ0IjoxNjAyMzU0MTgxfQ%3D%3D--4fb6811a255b25934d42c61f0dbb4553c45d4ccaa2b2fb05e071e88cec0b8409&shared=true |
| +23 | ##.bottomad |  | `www.bigcocker.com` |  | dom | `https://www.bigcocker.com/` |
| +23 |  |  | `www.bigcocker.com` | 1 | script | `https://www.bigcocker.com/ts/tt_1.php` |
| +23 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/favicon.ico` |
| +23 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://a.exosrv.com/video-slider.js` |
| +23 | google-analytics.com/analytics.js | << | `www.bigcocker.com` |  | script | `https://www.google-analytics.com/analytics.js` |
| +23 | \|\|google-analytics.com^ | -- | `www.bigcocker.com` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +23 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/ads.js` |
| +23 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/ads.js` |
| +23 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/ads.js` |
| +23 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/nativeads.js` |
| +23 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/nativeads.js` |
| +23 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/nativeads.js` |
| +23 | ://ads.$domain=~ads.ac.uk\|~ads.adstream.com.ro\|~ads.allegro.pl\|~ads.am\|~ads.atmosphere.copernicus.eu\|~ads.bigbom.com\|~ads.brave.com\|~ads.buscaempresas.co\|~ads.colombiaonline.com\|~ads.comeon.com\|~ads.cvut.cz\|~ads.dev.int.revelian.com\|~ads.dollartree.com\|~ads.elcarado.com\|~ads.google.com\|~ads.harvard.edu\|~ads.lapalingo.com\|~ads.lordlucky.com\|~ads.microsoft.com\|~ads.mobilebet.com\|~ads.msstate.edu\|~ads.mst.dk\|~ads.nc\|~ads.nimses.com\|~ads.odesbuild.com\|~ads.olx.pl\|~ads.pinterest.com\|~ads.quasaraffiliates.com\|~ads.red\|~ads.route.cc\|~ads.safi-gmbh.ch\|~ads.sk\|~ads.snapchat.com\|~ads.socialtheater.com\|~ads.spotify.com\|~ads.taboola.com\|~ads.tiktok.com\|~ads.toplayaffiliates.com\|~ads.viksaffiliates.com\|~ads.watson.ch\|~ads.xtribeapp.com\|~ads.yahoosmallbusiness.com\|~badassembly.com\|~caravansforsale.co.uk\|~fusac.fr\|~memo2.nl\|~reempresa.org\|~satmetrix.com\|~seriouswheels.com | -- | `www.bigcocker.com` | 3 | script | `https://ads.exoclick.com/ads.js` |
| +23 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://a.exosrv.com/ads.js` |
| +23 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://a.exosrv.com/video-slider.js` |
| +23 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/ads.js` |
| +23 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/nativeads.js` |
| +23 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://a.exosrv.com/ads.js` |
| +23 |  |  | `www.bigcocker.com` | 1 | script | `https://www.bigcocker.com/ts/ab_1.js` |
| +23 |  |  | `www.bigcocker.com` | 1 | doc | `https://www.bigcocker.com/` |
| +23 |  |  | `www.bigcocker.com` | 1 | doc | `http://www.bigcocker.com/` |
| +23 |  |  | bigcocker.com | 1 | doc | `https://bigcocker.com/` |
| +22 |  |  | bigcocker.com | 1 | doc | `http://bigcocker.com/` |
| +22 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozMDY4NDc3MzQ5LCJ0IjoxNjAyMzU0MTgxfQ%3D%3D--4fb6811a255b25934d42c61f0dbb4553c45d4ccaa2b2fb05e071e88cec0b8409&shared=true |
| +20 | ##.bottomad |  | `www.bigcocker.com` |  | dom | `https://www.bigcocker.com/` |
| +20 |  |  | `www.bigcocker.com` | 1 | script | `https://www.bigcocker.com/ts/tt_1.php` |
| +20 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/favicon.ico` |
| +20 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://a.exosrv.com/video-slider.js` |
| +20 | google-analytics.com/analytics.js | << | `www.bigcocker.com` |  | script | `https://www.google-analytics.com/analytics.js` |
| +20 | \|\|google-analytics.com^ | -- | `www.bigcocker.com` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +20 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/ads.js` |
| +20 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/ads.js` |
| +20 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/ads.js` |
| +20 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/nativeads.js` |
| +20 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/nativeads.js` |
| +20 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/nativeads.js` |
| +20 | ://ads.$domain=~ads.ac.uk\|~ads.adstream.com.ro\|~ads.allegro.pl\|~ads.am\|~ads.atmosphere.copernicus.eu\|~ads.bigbom.com\|~ads.brave.com\|~ads.buscaempresas.co\|~ads.colombiaonline.com\|~ads.comeon.com\|~ads.cvut.cz\|~ads.dev.int.revelian.com\|~ads.dollartree.com\|~ads.elcarado.com\|~ads.google.com\|~ads.harvard.edu\|~ads.lapalingo.com\|~ads.lordlucky.com\|~ads.microsoft.com\|~ads.mobilebet.com\|~ads.msstate.edu\|~ads.mst.dk\|~ads.nc\|~ads.nimses.com\|~ads.odesbuild.com\|~ads.olx.pl\|~ads.pinterest.com\|~ads.quasaraffiliates.com\|~ads.red\|~ads.route.cc\|~ads.safi-gmbh.ch\|~ads.sk\|~ads.snapchat.com\|~ads.socialtheater.com\|~ads.spotify.com\|~ads.taboola.com\|~ads.tiktok.com\|~ads.toplayaffiliates.com\|~ads.viksaffiliates.com\|~ads.watson.ch\|~ads.xtribeapp.com\|~ads.yahoosmallbusiness.com\|~badassembly.com\|~caravansforsale.co.uk\|~fusac.fr\|~memo2.nl\|~reempresa.org\|~satmetrix.com\|~seriouswheels.com | -- | `www.bigcocker.com` | 3 | script | `https://ads.exoclick.com/ads.js` |
| +20 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://a.exosrv.com/ads.js` |
| +19 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://a.exosrv.com/video-slider.js` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/afb/rightbanner.jpg` |
| +19 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/ads.js` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2800.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2798.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2799.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2801.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/1624.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/1293.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2802.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2803.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2804.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2805.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2806.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2556.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2807.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2808.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/1674.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/1711.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2809.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2810.jpg` |
| +19 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://ads.exosrv.com/nativeads.js` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2430.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2783.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2815.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2816.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2813.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/uploads/2814.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/afb/filler.jpg` |
| +19 | \|\|exosrv.com^ | -- | `www.bigcocker.com` | 3 | script | `https://a.exosrv.com/ads.js` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/afb/arrow.gif` |
| +19 |  |  | `www.bigcocker.com` | 1 | image | `https://www.bigcocker.com/afb/header.jpg` |
| +19 |  |  | `www.bigcocker.com` | 1 | script | `https://www.bigcocker.com/ts/ab_1.js` |
| +19 |  |  | `www.bigcocker.com` | 1 | css | `https://www.bigcocker.com/style2.css` |
| +19 |  |  | `www.bigcocker.com` | 1 | doc | `https://www.bigcocker.com/` |
| +18 |  |  | `www.bigcocker.com` | 1 | doc | `http://www.bigcocker.com/` |
| +15 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106753/420x335/3.jpg` |
| +14 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106753/420x335/2.jpg` |
| +7 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozMDY4NDc3MzQ5LCJ0IjoxNjAyMzU0MTgxfQ%3D%3D--4fb6811a255b25934d42c61f0dbb4553c45d4ccaa2b2fb05e071e88cec0b8409&shared=true |
| +7 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +7 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +4 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +4 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +0 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
</details>
