### ISSUE TITLE
pornrewind.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#320]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
www.pornrewind.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-215725](https://user-images.githubusercontent.com/38778536/95653350-dc335c80-0b43-11eb-8008-a5b7fd9948c7.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/hosts.txt)?
- [X] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +69 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106749/420x335/3.jpg` |
| +68 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106742/420x335/3.jpg` |
| +68 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106748/420x335/2.jpg` |
| +67 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106743/420x335/2.jpg` |
| +67 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106742/420x335/2.jpg` |
| +65 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMDc0NDI1MjExLCJ0IjoxNjAyMzU0MTA1fQ%3D%3D--e84a0dc910876b526839114e3cb95f0b19041568b41a9c8dad791cbe975014a6&shared=true |
| +48 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106753/420x335/2.jpg` |
| +48 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106711/420x335/1.jpg` |
| +48 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106712/420x335/1.jpg` |
| +48 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106719/420x335/1.jpg` |
| +48 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106720/420x335/1.jpg` |
| +48 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106721/420x335/1.jpg` |
| +48 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMDc0NDI1MjExLCJ0IjoxNjAyMzU0MTA1fQ%3D%3D--e84a0dc910876b526839114e3cb95f0b19041568b41a9c8dad791cbe975014a6&shared=true |
| +47 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106749/420x335/2.jpg` |
| +47 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106723/420x335/1.jpg` |
| +47 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106725/420x335/1.jpg` |
| +47 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106728/420x335/1.jpg` |
| +47 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106730/420x335/1.jpg` |
| +47 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106732/420x335/1.jpg` |
| +47 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106733/420x335/1.jpg` |
| +47 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106737/420x335/1.jpg` |
| +47 | `##a[href^="https://www.nutaku.net/signup/landing/"]` |  | `www.pornrewind.com` |  | dom | `https://www.pornrewind.com/home` |
| +47 | `##a[href^="http://adultgames.xxx/"]` |  | `www.pornrewind.com` |  | dom | `https://www.pornrewind.com/home` |
| +47 | &action=js_stats& | -- | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/home?mode=async&action=js_stats&rand=1602354121671` |
| +47 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/favicon.ico` |
| +47 | ://ads.$domain=~ads.ac.uk\|~ads.adstream.com.ro\|~ads.allegro.pl\|~ads.am\|~ads.atmosphere.copernicus.eu\|~ads.bigbom.com\|~ads.brave.com\|~ads.buscaempresas.co\|~ads.colombiaonline.com\|~ads.comeon.com\|~ads.cvut.cz\|~ads.dev.int.revelian.com\|~ads.dollartree.com\|~ads.elcarado.com\|~ads.google.com\|~ads.harvard.edu\|~ads.lapalingo.com\|~ads.lordlucky.com\|~ads.microsoft.com\|~ads.mobilebet.com\|~ads.msstate.edu\|~ads.mst.dk\|~ads.nc\|~ads.nimses.com\|~ads.odesbuild.com\|~ads.olx.pl\|~ads.pinterest.com\|~ads.quasaraffiliates.com\|~ads.red\|~ads.route.cc\|~ads.safi-gmbh.ch\|~ads.sk\|~ads.snapchat.com\|~ads.socialtheater.com\|~ads.spotify.com\|~ads.taboola.com\|~ads.tiktok.com\|~ads.toplayaffiliates.com\|~ads.viksaffiliates.com\|~ads.watson.ch\|~ads.xtribeapp.com\|~ads.yahoosmallbusiness.com\|~badassembly.com\|~caravansforsale.co.uk\|~fusac.fr\|~memo2.nl\|~reempresa.org\|~satmetrix.com\|~seriouswheels.com | -- | `www.pornrewind.com` | 3 | script | `https://ads.bullionyield.com/resources/slider.min.js` |
| +47 | \|\|webpinp.com^ | -- | `www.pornrewind.com` | 3 | script | `https://webpinp.com/pw/waWQiOjEwNTgzMDQsInNpZCI6MTA2MzE5Mywid2lkIjoxMjQ1OTAsInNyYyI6Mn0=eyJ.js` |
| +47 | \|\|realsrv.com^ | -- | `www.pornrewind.com` | 3 | script | `https://a.realsrv.com/popunder1000.js` |
| +47 | \|\|googletagmanager.com/gtag/$3p | -- | `www.pornrewind.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-142979283-1` |
| +46 | \|\|webpinp.com^ | -- | `www.pornrewind.com` | 3 | script | `https://webpinp.com/pw/waWQiOjEwNTgzMDQsInNpZCI6MTA2MzE5Mywid2lkIjoxMjQ1OTAsInNyYyI6Mn0=eyJ.js` |
| +46 | \|\|realsrv.com^ | -- | `www.pornrewind.com` | 3 | script | `https://a.realsrv.com/popunder1000.js` |
| +46 | \|\|googletagmanager.com/gtag/$3p | -- | `www.pornrewind.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-142979283-1` |
| +46 |  |  | `www.pornrewind.com` | 1 | script | `https://www.pornrewind.com/static/js/custom.js?v=1.1` |
| +46 |  |  | `www.pornrewind.com` | 1 | script | `https://www.pornrewind.com/static/js/theme.min.js?v=1.0` |
| +46 |  |  | `www.pornrewind.com` | 1 | script | `https://www.pornrewind.com/static/js/vendors.min.js?v=1.4` |
| +46 | \|\|googleapis.com^$important | -- | `www.pornrewind.com` | 3 | css | `https://fonts.googleapis.com/css?family=Open+Sans:400,500,700` |
| +46 |  |  | `www.pornrewind.com` | 1 | doc | `https://www.pornrewind.com/home` |
| +46 |  |  | `www.pornrewind.com` | 1 | doc | `https://www.pornrewind.com/` |
| +46 |  |  | pornrewind.com | 1 | doc | `http://pornrewind.com/` |
| +45 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106723/420x335/1.jpg` |
| +45 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106725/420x335/1.jpg` |
| +45 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106728/420x335/1.jpg` |
| +45 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106730/420x335/1.jpg` |
| +45 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106732/420x335/1.jpg` |
| +45 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106733/420x335/1.jpg` |
| +45 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106737/420x335/1.jpg` |
| +44 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106738/420x335/1.jpg` |
| +44 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106739/420x335/1.jpg` |
| +44 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106740/420x335/1.jpg` |
| +44 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106741/420x335/1.jpg` |
| +44 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106742/420x335/1.jpg` |
| +44 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106743/420x335/1.jpg` |
| +44 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106744/420x335/1.jpg` |
| +44 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/99000/99732/420x335/1.jpg` |
| +44 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/101000/101784/420x335/1.jpg` |
| +44 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/99000/99742/420x335/1.jpg` |
| +43 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106745/420x335/1.jpg` |
| +43 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106746/420x335/1.jpg` |
| +43 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106747/420x335/1.jpg` |
| +42 | `##a[href^="https://www.nutaku.net/signup/landing/"]` |  | `www.pornrewind.com` |  | dom | `https://www.pornrewind.com/home` |
| +42 | `##a[href^="http://adultgames.xxx/"]` |  | `www.pornrewind.com` |  | dom | `https://www.pornrewind.com/home` |
| +42 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106748/420x335/1.jpg` |
| +42 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106749/420x335/1.jpg` |
| +42 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/106000/106753/420x335/1.jpg` |
| +42 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/100000/100619/420x335/1.jpg` |
| +42 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/99000/99726/420x335/1.jpg` |
| +42 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/100000/100329/420x335/1.jpg` |
| +42 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/100000/100551/420x335/1.jpg` |
| +42 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/99000/99258/420x335/1.jpg` |
| +42 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/99000/99725/420x335/1.jpg` |
| +42 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/contents/videos_screenshots/99000/99299/420x335/1.jpg` |
| +42 | &action=js_stats& | -- | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/home?mode=async&action=js_stats&rand=1602354117299` |
| +42 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/favicon.ico` |
| +42 | ://ads.$domain=~ads.ac.uk\|~ads.adstream.com.ro\|~ads.allegro.pl\|~ads.am\|~ads.atmosphere.copernicus.eu\|~ads.bigbom.com\|~ads.brave.com\|~ads.buscaempresas.co\|~ads.colombiaonline.com\|~ads.comeon.com\|~ads.cvut.cz\|~ads.dev.int.revelian.com\|~ads.dollartree.com\|~ads.elcarado.com\|~ads.google.com\|~ads.harvard.edu\|~ads.lapalingo.com\|~ads.lordlucky.com\|~ads.microsoft.com\|~ads.mobilebet.com\|~ads.msstate.edu\|~ads.mst.dk\|~ads.nc\|~ads.nimses.com\|~ads.odesbuild.com\|~ads.olx.pl\|~ads.pinterest.com\|~ads.quasaraffiliates.com\|~ads.red\|~ads.route.cc\|~ads.safi-gmbh.ch\|~ads.sk\|~ads.snapchat.com\|~ads.socialtheater.com\|~ads.spotify.com\|~ads.taboola.com\|~ads.tiktok.com\|~ads.toplayaffiliates.com\|~ads.viksaffiliates.com\|~ads.watson.ch\|~ads.xtribeapp.com\|~ads.yahoosmallbusiness.com\|~badassembly.com\|~caravansforsale.co.uk\|~fusac.fr\|~memo2.nl\|~reempresa.org\|~satmetrix.com\|~seriouswheels.com | -- | `www.pornrewind.com` | 3 | script | `https://ads.bullionyield.com/resources/slider.min.js` |
| +42 | \|\|webpinp.com^ | -- | `www.pornrewind.com` | 3 | script | `https://webpinp.com/pw/waWQiOjEwNTgzMDQsInNpZCI6MTA2MzE5Mywid2lkIjoxMjQ1OTAsInNyYyI6Mn0=eyJ.js` |
| +42 | \|\|realsrv.com^ | -- | `www.pornrewind.com` | 3 | script | `https://a.realsrv.com/popunder1000.js` |
| +42 | \|\|googletagmanager.com/gtag/$3p | -- | `www.pornrewind.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-142979283-1` |
| +42 |  |  | `www.pornrewind.com` | 1 | font | `https://www.pornrewind.com/static/fonts-new/icomoon.ttf?k3lokk` |
| +42 |  |  | `www.pornrewind.com` | 1 | image | `https://www.pornrewind.com/static/images/logo-light-pink.png` |
| +42 | \|\|webpinp.com^ | -- | `www.pornrewind.com` | 3 | script | `https://webpinp.com/pw/waWQiOjEwNTgzMDQsInNpZCI6MTA2MzE5Mywid2lkIjoxMjQ1OTAsInNyYyI6Mn0=eyJ.js` |
| +42 | \|\|realsrv.com^ | -- | `www.pornrewind.com` | 3 | script | `https://a.realsrv.com/popunder1000.js` |
| +42 | \|\|googletagmanager.com/gtag/$3p | -- | `www.pornrewind.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-142979283-1` |
| +42 |  |  | `www.pornrewind.com` | 1 | script | `https://www.pornrewind.com/static/js/custom.js?v=1.1` |
| +42 |  |  | `www.pornrewind.com` | 1 | script | `https://www.pornrewind.com/static/js/theme.min.js?v=1.0` |
| +42 |  |  | `www.pornrewind.com` | 1 | script | `https://www.pornrewind.com/static/js/vendors.min.js?v=1.4` |
| +42 | \|\|googleapis.com^$important | -- | `www.pornrewind.com` | 3 | css | `https://fonts.googleapis.com/css?family=Open+Sans:400,500,700` |
| +42 |  |  | `www.pornrewind.com` | 1 | css | `https://www.pornrewind.com/static/styles/theme-light-pink.css?v=1.0` |
| +42 |  |  | `www.pornrewind.com` | 1 | css | `https://www.pornrewind.com/static/styles/layout.css?v=2.9` |
| +41 |  |  | `www.pornrewind.com` | 1 | doc | `https://www.pornrewind.com/home` |
| +41 |  |  | `www.pornrewind.com` | 1 | doc | `https://www.pornrewind.com/` |
| +41 |  |  | `www.pornrewind.com` | 1 | doc | `http://www.pornrewind.com/` |
| +39 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMDc0NDI1MjExLCJ0IjoxNjAyMzU0MTA1fQ%3D%3D--e84a0dc910876b526839114e3cb95f0b19041568b41a9c8dad791cbe975014a6&shared=true |
| +35 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMDc0NDI1MjExLCJ0IjoxNjAyMzU0MTA1fQ%3D%3D--e84a0dc910876b526839114e3cb95f0b19041568b41a9c8dad791cbe975014a6&shared=true |
| +33 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMDc0NDI1MjExLCJ0IjoxNjAyMzU0MTA1fQ%3D%3D--e84a0dc910876b526839114e3cb95f0b19041568b41a9c8dad791cbe975014a6&shared=true |
| +32 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMDc0NDI1MjExLCJ0IjoxNjAyMzU0MTA1fQ%3D%3D--e84a0dc910876b526839114e3cb95f0b19041568b41a9c8dad791cbe975014a6&shared=true |
| +32 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +31 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +30 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozODQ4MDExMjA5LCJ0IjoxNjAyMzU0MTAzfQ%3D%3D--05493caf94d859b64b3178d657156e2bac875d089e97c0c8c0adbca7748a768e&shared=true |
| +29 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozODQ4MDExMjA5LCJ0IjoxNjAyMzU0MTAzfQ%3D%3D--05493caf94d859b64b3178d657156e2bac875d089e97c0c8c0adbca7748a768e&shared=true |
| +29 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +29 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +0 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
</details>
