### ISSUE TITLE
hdpornos.net

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#321]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
hdpornos.net
hd-pornos.net
www.hdpornos.net
www.hd-pornos.net
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-220159](https://user-images.githubusercontent.com/38778536/95653446-93c86e80-0b44-11eb-8f59-9e08c904cc54.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
Only added `hdpornos.net` as (www.)?`hd-pornos.net` redirects to this domain
