### ISSUE TITLE
terk.nl

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#322]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
www.terk.nl
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-221351](https://user-images.githubusercontent.com/38778536/95653680-21f12480-0b46-11eb-9983-14536b493ce3.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/hosts.txt)?
- [X] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +36 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/favicon-16x16.png` |
| +36 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/android-icon-192x192.png` |
| +36 | `##[href^="https://twitter.com"]` |  | `www.terk.nl` |  | dom | `https://www.terk.nl/` |
| +36 | \|\|exosrv.com^ | -- | `www.terk.nl` | 3 | script | `https://a.exosrv.com/video-slider.js` |
| +35 | \|\|exosrv.com^ | -- | `www.terk.nl` | 3 | script | `https://ads.exosrv.com/ads.js` |
| +35 | \|\|exosrv.com^ | -- | `www.terk.nl` | 3 | script | `https://ads.exosrv.com/ads.js` |
| +35 | \|\|exosrv.com^ | -- | `www.terk.nl` | 3 | script | `https://ads.exosrv.com/ads.js` |
| +35 | \|\|googletagmanager.com/gtag/$3p | -- | `www.terk.nl` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-133225027-1` |
| +35 | \|\|exosrv.com^ | -- | `www.terk.nl` | 3 | script | `https://a.exosrv.com/video-slider.js` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/twitter.png` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6786.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/5067.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/5008.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6697.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6647.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/2955.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/4582.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/3451.jpg` |
| +35 | \|\|exosrv.com^ | -- | `www.terk.nl` | 3 | script | `https://ads.exosrv.com/ads.js` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/dot.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6934.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6928.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6931.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6929.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6938.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/3981.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6944.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6941.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6942.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6939.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6943.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6940.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6945.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6946.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6020.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6953.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6949.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6951.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6950.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6882.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6952.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6955.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6954.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/3328.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/1622.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6958.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6947.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6959.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6948.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/thumbs_up_home.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/views.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/clock.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/uploads/6957.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/filler.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/themes.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/misc.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/wtf.gif` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/drunk.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/cum.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/big-cock.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/titdrop.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/public.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/anal.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/slutty.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/heart.jpg` |
| +35 |  |  | `www.terk.nl` | 1 | image | `https://www.terk.nl/afb/logo2.jpg` |
| +35 | \|\|googletagmanager.com/gtag/$3p | -- | `www.terk.nl` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-133225027-1` |
| +35 |  |  | `www.terk.nl` | 1 | css | `https://www.terk.nl/style4.css` |
| +34 |  |  | `www.terk.nl` | 1 | doc | `https://www.terk.nl/` |
| +34 |  |  | terk.nl | 1 | doc | `http://terk.nl/` |
| +24 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxNzQ3MTM5NTU1LCJ0IjoxNjAyMzUyNzc0fQ%3D%3D--d61f470443fe57bbf62645b2a40092eecdf1c22f8ace2b97b64ff4b6ed917acf&shared=true |
| +20 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +20 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +12 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +12 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +0 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
</details>
