### ISSUE TITLE
forthegirls.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#324]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
forthegirls.com
www.forthegirls.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-222957](https://user-images.githubusercontent.com/38778536/95653959-4c43e180-0b48-11eb-9218-f9d1ee136d1b.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +9 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozNTI5NDUxMjkzLCJ0IjoxNjAyMzUyMjc0fQ%3D%3D--d674ea6e1f4e480c1330605e13c17c2af5c5872fb96c3f3065ca515d08ea9f65&shared=true |
| +9 | ##.social-icons |  | `www.forthegirls.com` |  | dom | `http://www.forthegirls.com/` |
| +9 |  |  | `www.forthegirls.com` | 1 | image | `http://www.forthegirls.com/favicon.ico` |
| +9 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/js/theme.init.js` |
| +8 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/js/custom.js` |
| +8 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/js/theme.js` |
| +8 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/vide/vide.js` |
| +8 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/magnific-popup/jquery.magnific-popup.js` |
| +8 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jflickrfeed/jflickrfeed.js` |
| +8 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/owlcarousel/owl.carousel.js` |
| +8 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/isotope/jquery.isotope.js` |
| +8 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery.gmap/jquery.gmap.js` |
| +8 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery.easy-pie-chart/jquery.easy-pie-chart.js` |
| +8 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery.stellar/jquery.stellar.js` |
| +8 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery.validation/jquery.validation.js` |
| +8 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/common/common.js` |
| +7 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/bootstrap/bootstrap.js` |
| +7 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery-cookie/jquery-cookie.js` |
| +7 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery.easing/jquery.easing.js` |
| +7 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery.appear/jquery.appear.js` |
| +7 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery/jquery.js` |
| +7 | google-analytics.com/analytics.js | << | `www.forthegirls.com` |  | script | `https://www.google-analytics.com/analytics.js` |
| +7 | \|\|google-analytics.com^ | -- | `www.forthegirls.com` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/js/theme.init.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/js/custom.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/js/theme.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/vide/vide.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/magnific-popup/jquery.magnific-popup.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jflickrfeed/jflickrfeed.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/owlcarousel/owl.carousel.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/isotope/jquery.isotope.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery.gmap/jquery.gmap.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery.easy-pie-chart/jquery.easy-pie-chart.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery.stellar/jquery.stellar.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery.validation/jquery.validation.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/common/common.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/bootstrap/bootstrap.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery-cookie/jquery-cookie.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery.easing/jquery.easing.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery.appear/jquery.appear.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/jquery/jquery.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | image | `http://www.forthegirls.com/images/yesbutton.jpg` |
| +6 |  |  | `www.forthegirls.com` | 1 | image | `http://www.forthegirls.com/images/nobutton.jpg` |
| +6 |  |  | `www.forthegirls.com` | 1 | image | `http://www.forthegirls.com/images/warning.gif` |
| +6 |  |  | `www.forthegirls.com` | 1 | image | `http://www.forthegirls.com/images/eroticfiction2.jpg` |
| +6 |  |  | `www.forthegirls.com` | 1 | image | `http://www.forthegirls.com/images/photos.jpg` |
| +6 |  |  | `www.forthegirls.com` | 1 | image | `http://www.forthegirls.com/images/videos.jpg` |
| +6 |  |  | `www.forthegirls.com` | 1 | image | `http://www.forthegirls.com/images/FTGpornforwomen_frontpage.jpg` |
| +6 |  |  | `www.forthegirls.com` | 1 | image | `http://www.forthegirls.com/images/v2logo.png` |
| +6 |  |  | `www.forthegirls.com` | 1 | script | `http://www.forthegirls.com/vendor/modernizr/modernizr.js` |
| +6 |  |  | `www.forthegirls.com` | 1 | css | `http://www.forthegirls.com/css/custom.css` |
| +6 |  |  | `www.forthegirls.com` | 1 | css | `http://www.forthegirls.com/css/skins/default.css` |
| +6 |  |  | `www.forthegirls.com` | 1 | css | `http://www.forthegirls.com/css/theme-animate.css` |
| +6 |  |  | `www.forthegirls.com` | 1 | css | `http://www.forthegirls.com/css/theme-shop.css` |
| +6 |  |  | `www.forthegirls.com` | 1 | css | `http://www.forthegirls.com/css/theme-blog.css` |
| +6 |  |  | `www.forthegirls.com` | 1 | css | `http://www.forthegirls.com/css/theme-elements.css` |
| +6 |  |  | `www.forthegirls.com` | 1 | css | `http://www.forthegirls.com/css/theme.css` |
| +6 |  |  | `www.forthegirls.com` | 1 | css | `http://www.forthegirls.com/vendor/magnific-popup/magnific-popup.css` |
| +6 |  |  | `www.forthegirls.com` | 1 | css | `http://www.forthegirls.com/vendor/owlcarousel/owl.theme.default.min.css` |
| +6 |  |  | `www.forthegirls.com` | 1 | css | `http://www.forthegirls.com/vendor/owlcarousel/owl.carousel.min.css` |
| +6 |  |  | `www.forthegirls.com` | 1 | css | `http://www.forthegirls.com/vendor/fontawesome/css/font-awesome.css` |
| +6 |  |  | `www.forthegirls.com` | 1 | css | `http://www.forthegirls.com/vendor/bootstrap/bootstrap.css` |
| +6 | \|\|googleapis.com^$important | -- | `www.forthegirls.com` | 3 | css | `http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light` |
| +6 |  |  | `www.forthegirls.com` | 1 | doc | `http://www.forthegirls.com/` |
| +4 | ##.social-icons |  | forthegirls.com |  | dom | `http://forthegirls.com/` |
| +4 |  |  | forthegirls.com | 1 | image | `http://forthegirls.com/favicon.ico` |
| +4 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/js/theme.init.js` |
| +4 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/js/custom.js` |
| +4 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/js/theme.js` |
| +4 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/vide/vide.js` |
| +3 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/magnific-popup/jquery.magnific-popup.js` |
| +3 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jflickrfeed/jflickrfeed.js` |
| +3 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/owlcarousel/owl.carousel.js` |
| +3 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/isotope/jquery.isotope.js` |
| +3 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery.gmap/jquery.gmap.js` |
| +3 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery.easy-pie-chart/jquery.easy-pie-chart.js` |
| +2 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery.stellar/jquery.stellar.js` |
| +2 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery.validation/jquery.validation.js` |
| +2 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/common/common.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery-cookie/jquery-cookie.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery.easing/jquery.easing.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery.appear/jquery.appear.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery/jquery.js` |
| +1 | google-analytics.com/analytics.js | << | forthegirls.com |  | script | `https://www.google-analytics.com/analytics.js` |
| +1 | \|\|google-analytics.com^ | -- | forthegirls.com | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/js/theme.init.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/js/custom.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/js/theme.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/vide/vide.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/magnific-popup/jquery.magnific-popup.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jflickrfeed/jflickrfeed.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/owlcarousel/owl.carousel.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/isotope/jquery.isotope.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery.gmap/jquery.gmap.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery.easy-pie-chart/jquery.easy-pie-chart.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery.stellar/jquery.stellar.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery.validation/jquery.validation.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/common/common.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/bootstrap/bootstrap.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery-cookie/jquery-cookie.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery.easing/jquery.easing.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery.appear/jquery.appear.js` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/jquery/jquery.js` |
| +1 |  |  | forthegirls.com | 1 | image | `http://forthegirls.com/images/yesbutton.jpg` |
| +1 |  |  | forthegirls.com | 1 | image | `http://forthegirls.com/images/nobutton.jpg` |
| +1 |  |  | forthegirls.com | 1 | image | `http://forthegirls.com/images/warning.gif` |
| +1 |  |  | forthegirls.com | 1 | image | `http://forthegirls.com/images/eroticfiction2.jpg` |
| +1 |  |  | forthegirls.com | 1 | image | `http://forthegirls.com/images/photos.jpg` |
| +1 |  |  | forthegirls.com | 1 | image | `http://forthegirls.com/images/videos.jpg` |
| +1 |  |  | forthegirls.com | 1 | image | `http://forthegirls.com/images/FTGpornforwomen_frontpage.jpg` |
| +1 |  |  | forthegirls.com | 1 | image | `http://forthegirls.com/images/v2logo.png` |
| +1 |  |  | forthegirls.com | 1 | script | `http://forthegirls.com/vendor/modernizr/modernizr.js` |
| +1 |  |  | forthegirls.com | 1 | css | `http://forthegirls.com/css/custom.css` |
| +1 |  |  | forthegirls.com | 1 | css | `http://forthegirls.com/css/skins/default.css` |
| +1 |  |  | forthegirls.com | 1 | css | `http://forthegirls.com/css/theme-animate.css` |
| +1 |  |  | forthegirls.com | 1 | css | `http://forthegirls.com/css/theme-shop.css` |
| +1 |  |  | forthegirls.com | 1 | css | `http://forthegirls.com/css/theme-blog.css` |
| +1 |  |  | forthegirls.com | 1 | css | `http://forthegirls.com/css/theme-elements.css` |
| +1 |  |  | forthegirls.com | 1 | css | `http://forthegirls.com/css/theme.css` |
| +1 |  |  | forthegirls.com | 1 | css | `http://forthegirls.com/vendor/magnific-popup/magnific-popup.css` |
| +1 |  |  | forthegirls.com | 1 | css | `http://forthegirls.com/vendor/owlcarousel/owl.theme.default.min.css` |
| +1 |  |  | forthegirls.com | 1 | css | `http://forthegirls.com/vendor/owlcarousel/owl.carousel.min.css` |
| +1 |  |  | forthegirls.com | 1 | css | `http://forthegirls.com/vendor/fontawesome/css/font-awesome.css` |
| +1 |  |  | forthegirls.com | 1 | css | `http://forthegirls.com/vendor/bootstrap/bootstrap.css` |
| +1 | \|\|googleapis.com^$important | -- | forthegirls.com | 3 | css | `http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light` |
| +0 |  |  | forthegirls.com | 1 | doc | `http://forthegirls.com/` |
</details>
