### ISSUE TITLE
hotmoviesforher.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#325]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
www.hotmoviesforher.com
vod.hotmoviesforher.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-223325](https://user-images.githubusercontent.com/38778536/95654093-43074480-0b49-11eb-93d7-a275f76c5134.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +105 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +102 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +101 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +89 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyNjAzOTg3OTIzLCJ0IjoxNjAyMzQ3MDAzfQ%3D%3D--40792db079472dc4de306d5ad34127a6e702602eafff5ceb22ea043fab99f5ef&shared=true |
| +55 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyNjAzOTg3OTIzLCJ0IjoxNjAyMzQ3MDAzfQ%3D%3D--40792db079472dc4de306d5ad34127a6e702602eafff5ceb22ea043fab99f5ef&shared=true |
| +54 | ##.gdpr_cookie_bar |  | vod.hotmoviesforher.com |  | dom | `https://vod.hotmoviesforher.com/` |
| +54 | ##.back_up_but |  | vod.hotmoviesforher.com |  | dom | `https://vod.hotmoviesforher.com/` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img3.vod.com/image2/clip/255/2550222.2.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img1.vod.com/image2/clip/254/2548950.2.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img1.vod.com/image2/clip/254/2549480.3.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img1.vod.com/image2/clip/254/2549894.2.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img2.vod.com/image2/clip/255/2551320.5.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/clip/254/2547298.5.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img3.vod.com/image2/clip/254/2548130.6.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/423/423442.cover.0.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/423/423414.cover.3.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/421/421776.cover.0.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/424/424030.cover.2.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/423/423896.cover.1.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/423/423644.cover.1.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/423/423114.cover.1.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/star/241/Maitland_Ward-241306.32322484781570119356large.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img1.vod.com/image2/star/227/Sloan_Harper-227523.32322483301525701821large.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img3.vod.com/image2/star/134/Chad_Alva-134603.10627189711434984586large.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img1.vod.com/image2/star/222/Lydia_Black-222159.1684951201598898806large.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img3.vod.com/image2/star/208/Anna_de_Ville-208846.32322483541550510855large.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img3.vod.com/image2/star/212/Lucas_Frost-212455.10627189621472237410large.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img3.vod.com/image2/star/192/Eva_Long-192256.1684951471584972759large.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/star/179/Preston_Parker-179353.10627189271464720116large.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/422/422630.cover.0.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/421/421754.cover.1.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/423/423180.cover.2.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/422/422702.cover.1.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/422/422790.cover.0.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/419/419680.cover.1.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/422/422742.cover.1.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/422/422700.cover.1.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/422/422438.cover.0.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/415/415006.cover.0.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/408/408808.cover.0.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/423/423898.cover.1.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/423/423332.cover.2.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/423/423046.cover.0.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/419/419498.cover.2.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/410/410350.cover.0.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img1.vod.com/image2/vodimages/images/exclusive_mark.png` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/423/423266.cover.11.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/424/424190.cover.0.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/419/419826.cover.0.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/424/424192.cover.1.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/423/423376.cover.0.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/418/418682.cover.0.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/424/424178.cover.2.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/image2/cover/424/424148.cover.1.jpg` |
| +50 |  |  | vod.hotmoviesforher.com | 1 | image | `https://vod.hotmoviesforher.com/favicon.ico` |
| +49 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/md/topcategories/4212_category_224.jpg` |
| +49 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/md/topcategories/4212_category_521.jpg` |
| +49 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img2.vod.com/md/topcategories/4212_category_761.jpg` |
| +49 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/md/topcategories/4212_category_228.jpg` |
| +49 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img3.vod.com/md/topcategories/4212_category_496.jpg` |
| +49 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img3.vod.com/md/topcategories/4212_category_452.jpg` |
| +49 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img.vod.com/md/topcategories/4212_category_156.jpg` |
| +49 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img2.vod.com/md/topcategories/4212_category_604.jpg` |
| +49 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img1.vod.com/md/topcategories/4212_category_445.jpg` |
| +49 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img3.vod.com/md/topcategories/4212_category_357.jpg` |
| +49 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img1.vod.com/md/topcategories/4212_category_665.jpg` |
| +49 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img2.vod.com/md/topcategories/4212_category_491.jpg` |
| +49 |  |  | vod.hotmoviesforher.com | 1 | image | `https://vod.hotmoviesforher.com/images/arrow_grey_right.png` |
| +49 |  |  | vod.hotmoviesforher.com | 1 | image | `https://vod.hotmoviesforher.com/images/arrow_grey_left.png` |
| +49 |  |  | vod.hotmoviesforher.com | 1 | font | `https://vod.hotmoviesforher.com/fonts/fontawesome-webfont.woff2?v=4.7.0` |
| +49 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img2.vod.com/image2/vodimages/images/search.png` |
| +49 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img3.vod.com/image2/vodimages/images/bg-noise.png` |
| +49 | \|\|googletagmanager.com/gtag/$3p | -- | vod.hotmoviesforher.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-225147-1` |
| +49 | googletagmanager.com/gtm.js | << | vod.hotmoviesforher.com |  | script | `https://www.googletagmanager.com/gtm.js?id=GTM-PN2RKM` |
| +49 | \|\|googletagmanager.com/gtm.js$script | -- | vod.hotmoviesforher.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-PN2RKM` |
| +48 |  |  | vod.hotmoviesforher.com | 1 | script | `https://vod.hotmoviesforher.com/slick/slick.min.js` |
| +48 |  |  | vod.hotmoviesforher.com | 1 | script | `https://vod.hotmoviesforher.com/page_script.php?page=index` |
| +48 |  |  | vod.hotmoviesforher.com | 1 | script | `https://vod.hotmoviesforher.com/script.php` |
| +48 |  |  | vod.hotmoviesforher.com | 1 | script | `https://vod.hotmoviesforher.com/js/HM_javascript_vars.php?v=20180422&usehttps=1` |
| +48 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img1.vod.com/image2/vodimages/images/footer_roku_sm.jpg` |
| +48 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img1.vod.com/image2/vodimages/images/netnanny_icon_wh.png` |
| +48 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img2.vod.com/image2/vodimages/images/face-rec-ad-dropdown-mobile.jpg` |
| +48 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img3.vod.com/image2/vodimages/images/face-rec-ad-dropdown-small.jpg` |
| +48 |  |  | vod.hotmoviesforher.com | 3 | image | `https://img2.vod.com/md/logos/logo_responsive_4212.1582570928.png` |
| +48 | google-analytics.com/analytics.js | << | vod.hotmoviesforher.com |  | script | `https://www.google-analytics.com/analytics.js` |
| +48 | \|\|google-analytics.com^ | -- | vod.hotmoviesforher.com | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +48 | \|\|googletagmanager.com/gtag/$3p | -- | vod.hotmoviesforher.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-225147-1` |
| +48 |  |  | vod.hotmoviesforher.com | 1 | css | `https://vod.hotmoviesforher.com/style.php?ct=4212&video_preference=default&GDPR_SECURE_VALUE=WkxRR2cweS92VTREelM0emtQR2h6UT09Olp6aFJXRTF6TDFCTk5GTnRZbXR4YjJoc1RHNTRkejA5&cttemplate=responsive&usehttps=1&stylever=201806260947&page=index` |
| +47 |  |  | vod.hotmoviesforher.com | 1 | doc | `https://vod.hotmoviesforher.com/` |
| +47 |  |  | vod.hotmoviesforher.com | 1 | doc | `http://vod.hotmoviesforher.com/` |
| +45 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/?wordfence_lh=1&hid=CC74F1D9FE6CDEEB73C2500C013786F9&r=0.09494995489999214` |
| +32 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyNjAzOTg3OTIzLCJ0IjoxNjAyMzQ3MDAzfQ%3D%3D--40792db079472dc4de306d5ad34127a6e702602eafff5ceb22ea043fab99f5ef&shared=true |
| +31 | `##[href^="https://twitter.com"]` |  | `www.hotmoviesforher.com` |  | dom | `https://www.hotmoviesforher.com/` |
| +30 |  |  | `www.hotmoviesforher.com` | 1 | image | `https://www.hotmoviesforher.com/favicon.ico` |
| +30 | \|\|stats.wp.com^ | -- | `www.hotmoviesforher.com` | 3 | script | `https://stats.wp.com/e-202041.js` |
| +30 | \|\|googleapis.com^$important | -- | `www.hotmoviesforher.com` | 3 | css | `https://fonts.googleapis.com/css?family=Lato%3A300%2C400%2C700%2C900%2C300italic%2C400italic%2C700italic&subset=latin%2Clatin-ext` |
| +30 | \|\|stats.wp.com^ | -- | `www.hotmoviesforher.com` | 3 | script | `https://stats.wp.com/e-202041.js` |
| +30 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-includes/js/wp-embed.min.js?ver=5.2.7` |
| +30 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-content/themes/twentyfourteen/js/functions.js?ver=20150315` |
| +30 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-includes/js/jquery/jquery.masonry.min.js?ver=3.1.2b` |
| +30 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-includes/js/masonry.min.js?ver=3.3.2` |
| +30 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-includes/js/imagesloaded.min.js?ver=3.2.0` |
| +30 |  |  | `www.hotmoviesforher.com` | 3 | script | `https://s0.wp.com/wp-content/js/devicepx-jetpack.js?ver=202041` |
| +30 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1` |
| +30 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp` |
| +30 | \|\|googleapis.com^$important | -- | `www.hotmoviesforher.com` | 3 | css | `https://fonts.googleapis.com/css?family=Lato%3A300%2C400%2C700%2C900%2C300italic%2C400italic%2C700italic&subset=latin%2Clatin-ext` |
| +30 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-content/themes/hotmoviesforher/js/jquery.cycle.all.2.72.js` |
| +30 |  |  | `www.hotmoviesforher.com` | 1 | doc | `https://www.hotmoviesforher.com/` |
| +29 |  |  | hotmoviesforher.com | 1 | doc | `https://hotmoviesforher.com/` |
| +28 |  |  | hotmoviesforher.com | 1 | doc | `http://hotmoviesforher.com/` |
| +26 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/?wordfence_lh=1&hid=CC74F1D9FE6CDEEB73C2500C013786F9&r=0.12729938765688054` |
| +21 |  |  | `www.hotmoviesforher.com` | 1 | image | `https://www.hotmoviesforher.com/favicon.ico` |
| +20 | `##[href^="https://twitter.com"]` |  | `www.hotmoviesforher.com` |  | dom | `https://www.hotmoviesforher.com/` |
| +20 | \|\|stats.wp.com^ | -- | `www.hotmoviesforher.com` | 3 | script | `https://stats.wp.com/e-202041.js` |
| +19 | \|\|googleapis.com^$important | -- | `www.hotmoviesforher.com` | 3 | css | `https://fonts.googleapis.com/css?family=Lato%3A300%2C400%2C700%2C900%2C300italic%2C400italic%2C700italic&subset=latin%2Clatin-ext` |
| +18 | \|\|stats.wp.com^ | -- | `www.hotmoviesforher.com` | 3 | script | `https://stats.wp.com/e-202041.js` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-includes/js/wp-embed.min.js?ver=5.2.7` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-content/themes/twentyfourteen/js/functions.js?ver=20150315` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-includes/js/jquery/jquery.masonry.min.js?ver=3.1.2b` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-includes/js/masonry.min.js?ver=3.3.2` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-includes/js/imagesloaded.min.js?ver=3.2.0` |
| +18 |  |  | `www.hotmoviesforher.com` | 3 | script | `https://s0.wp.com/wp-content/js/devicepx-jetpack.js?ver=202041` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | image | `https://www.hotmoviesforher.com/wp-content/uploads/2017/08/girlfriend-peeping-in-boyfriends-computer-online-stalking.jpg` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | image | `https://www.hotmoviesforher.com/wp-content/uploads/2017/09/346648.xfront.0-e1505760716856-424x576.jpg` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | image | `https://www.hotmoviesforher.com/wp-content/uploads/2018/04/2018-04-24_14-06-26.jpg` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | image | `https://www.hotmoviesforher.com/wp-content/uploads/2018/05/watchingporn.jpg` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | image | `https://www.hotmoviesforher.com/wp-content/uploads/2018/09/2018-09-12_8-59-13.jpg` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | image | `https://www.hotmoviesforher.com/wp-content/uploads/2019/02/Unfolding_AdamEve-425x576.jpg` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | image | `https://www.hotmoviesforher.com/wp-content/uploads/2019/03/a-pureebony-425x576.jpg` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | image | `https://www.hotmoviesforher.com/wp-content/uploads/2019/04/Kay-THREE.jpg` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | image | `https://www.hotmoviesforher.com/wp-content/uploads/2019/05/missy-martinez-thumb-2.jpg` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | image | `https://www.hotmoviesforher.com/wp-content/uploads/2019/05/lotus-lain-kink-thumb-800x576.jpg` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | image | `https://www.hotmoviesforher.com/wp-content/uploads/2018/01/header-recolor.png` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | css | `https://www.hotmoviesforher.com/wp-content/plugins/jetpack/css/jetpack.css?ver=7.4.2` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | css | `https://www.hotmoviesforher.com/wp-content/themes/twentyfourteen/css/blocks.css?ver=20181230` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | css | `https://www.hotmoviesforher.com/wp-content/themes/hotmoviesforher3/style.css?ver=5.2.7` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | css | `https://www.hotmoviesforher.com/wp-content/plugins/jetpack/_inc/genericons/genericons/genericons.css?ver=3.1` |
| +18 | \|\|googleapis.com^$important | -- | `www.hotmoviesforher.com` | 3 | css | `https://fonts.googleapis.com/css?family=Lato%3A300%2C400%2C700%2C900%2C300italic%2C400italic%2C700italic&subset=latin%2Clatin-ext` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | css | `https://www.hotmoviesforher.com/wp-content/themes/twentyfourteen/style.css?ver=5.2.7` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | css | `https://www.hotmoviesforher.com/wp-includes/css/dist/block-library/theme.min.css?ver=5.2.7` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | css | `https://www.hotmoviesforher.com/wp-includes/css/dist/block-library/style.min.css?ver=5.2.7` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | css | `https://www.hotmoviesforher.com/wp-content/plugins/jetpack/modules/theme-tools/compat/twentyfourteen.css?ver=7.4.2` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | css | `https://www.hotmoviesforher.com/wp-content/plugins/yet-another-related-posts-plugin/style/widget.css?ver=5.2.7` |
| +18 |  |  | `www.hotmoviesforher.com` | 1 | script | `https://www.hotmoviesforher.com/wp-content/themes/hotmoviesforher/js/jquery.cycle.all.2.72.js` |
| +17 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyNjAzOTg3OTIzLCJ0IjoxNjAyMzQ3MDAzfQ%3D%3D--40792db079472dc4de306d5ad34127a6e702602eafff5ceb22ea043fab99f5ef&shared=true |
| +17 |  |  | `www.hotmoviesforher.com` | 1 | doc | `https://www.hotmoviesforher.com/` |
| +16 |  |  | `www.hotmoviesforher.com` | 1 | doc | `http://www.hotmoviesforher.com/` |
| +8 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +8 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +7 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo3OTU2ODQ0MTUsInQiOjE2MDIzNDY5OTl9--c73e9177d302d4f015d16718bc5a9d914190001558fa5f7d11cc62bf465cd4dd&shared=true |
| +4 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +4 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +3 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +1 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +0 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +0 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo5MTU1ODIxMDEsInQiOjE2MDIzNDY5MzB9--94f2a4a7ee11b360a764e3463c0c59d89763f87a2299e8cf9fda1a2e0d8bb9f1&shared=true |
</details>
