### ISSUE TITLE
softcoretube.net

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#326]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
softcoretube.net
www.softcoretube.net
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-224310](https://user-images.githubusercontent.com/38778536/95654196-228bba00-0b4a-11eb-865d-532145bca19d.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +37 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo5MTU1ODIxMDEsInQiOjE2MDIzNDY5MzB9--94f2a4a7ee11b360a764e3463c0c59d89763f87a2299e8cf9fda1a2e0d8bb9f1&shared=true |
| +28 |  |  | `www.softcoretube.net` | 1 | font | `https://softcoretube.net/static/images/fonts/icomoon.woff?nddhpi` |
| +28 | ##.bottom-adv |  | `www.softcoretube.net` |  | dom | `https://www.softcoretube.net/` |
| +28 | `##a[href^="https://www.im88trk.com/"]` |  | `www.softcoretube.net` |  | dom | `https://www.softcoretube.net/` |
| +28 | ##.social-bookmarks |  | `www.softcoretube.net` |  | dom | `https://www.softcoretube.net/` |
| +28 | ##.icon-share |  | `www.softcoretube.net` |  | dom | `https://www.softcoretube.net/` |
| +28 | ##.addthis_toolbox |  | `www.softcoretube.net` |  | dom | `https://www.softcoretube.net/` |
| +28 | ##.addthis_default_style |  | `www.softcoretube.net` |  | dom | `https://www.softcoretube.net/` |
| +28 | ##.addthis_button_compact |  | `www.softcoretube.net` |  | dom | `https://www.softcoretube.net/` |
| +28 | ##.addthis_32x32_style |  | `www.softcoretube.net` |  | dom | `https://www.softcoretube.net/` |
| +28 |  |  | `www.softcoretube.net` | 1 | image | `https://softcoretube.net/favicon.ico` |
| +28 | &action=js_stats& | -- | `www.softcoretube.net` | 1 | image | `https://www.softcoretube.net/?mode=async&action=js_stats&rand=1602346954988` |
| +28 |  |  | `www.softcoretube.net` | 1 | font | `https://softcoretube.net/static/images/fonts/icomoon.ttf?nddhpi` |
| +28 | \|\|d38itq6vdv6gr9.cloudfront.net^ | -- | `www.softcoretube.net` | 3 | script | `https://d38itq6vdv6gr9.cloudfront.net/?vqtid=893655` |
| +28 | ://ads.$domain=~ads.ac.uk\|~ads.adstream.com.ro\|~ads.allegro.pl\|~ads.am\|~ads.atmosphere.copernicus.eu\|~ads.bigbom.com\|~ads.brave.com\|~ads.buscaempresas.co\|~ads.colombiaonline.com\|~ads.comeon.com\|~ads.cvut.cz\|~ads.dev.int.revelian.com\|~ads.dollartree.com\|~ads.elcarado.com\|~ads.google.com\|~ads.harvard.edu\|~ads.lapalingo.com\|~ads.lordlucky.com\|~ads.microsoft.com\|~ads.mobilebet.com\|~ads.msstate.edu\|~ads.mst.dk\|~ads.nc\|~ads.nimses.com\|~ads.odesbuild.com\|~ads.olx.pl\|~ads.pinterest.com\|~ads.quasaraffiliates.com\|~ads.red\|~ads.route.cc\|~ads.safi-gmbh.ch\|~ads.sk\|~ads.snapchat.com\|~ads.socialtheater.com\|~ads.spotify.com\|~ads.taboola.com\|~ads.tiktok.com\|~ads.toplayaffiliates.com\|~ads.viksaffiliates.com\|~ads.watson.ch\|~ads.xtribeapp.com\|~ads.yahoosmallbusiness.com\|~badassembly.com\|~caravansforsale.co.uk\|~fusac.fr\|~memo2.nl\|~reempresa.org\|~satmetrix.com\|~seriouswheels.com | -- | `www.softcoretube.net` | 3 | script | `https://ads.bullionyield.com/resources/slider.min.js` |
| +28 | \|\|wpush.org^$3p | -- | `www.softcoretube.net` | 3 | script | `https://sw.wpush.org/script/main.js?promo=17580&tcid=5095&src=241352630` |
| +28 | \|\|googletagmanager.com/gtag/$3p | -- | `www.softcoretube.net` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-124378457-1` |
| +28 | \|\|exosrv.com^ | -- | `www.softcoretube.net` | 3 | frame | `https://a.exosrv.com/iframe.php?idzone=3780975&size=300x250` |
| +28 | \|\|exosrv.com^ | -- | `www.softcoretube.net` | 3 | frame | `https://a.exosrv.com/iframe.php?idzone=3780971&size=300x250` |
| +28 | \|\|exosrv.com^ | -- | `www.softcoretube.net` | 3 | frame | `https://a.exosrv.com/iframe.php?idzone=3780965&size=300x250` |
| +28 | \|\|exosrv.com^ | -- | `www.softcoretube.net` | 3 | frame | `https://a.exosrv.com/iframe.php?idzone=3780963&size=300x250` |
| +28 | \|\|theporndude.com/graphics/tpd-$3p | -- | `www.softcoretube.net` | 3 | image | `https://cdn1.theporndude.com/graphics/tpd-b-24px.png` |
| +27 | \|\|d38itq6vdv6gr9.cloudfront.net^ | -- | `www.softcoretube.net` | 3 | script | `https://d38itq6vdv6gr9.cloudfront.net/?vqtid=893655` |
| +27 | \|\|googletagmanager.com/gtag/$3p | -- | `www.softcoretube.net` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-124378457-1` |
| +27 |  |  | `www.softcoretube.net` | 1 | script | `https://softcoretube.net/static/js/main.min.js?v=7.5` |
| +27 | addthis.com/addthis_widget.js | << | `www.softcoretube.net` |  | script | `https://s7.addthis.com/js/250/addthis_widget.js` |
| +27 | \|\|addthis.com^$3p,important,domain=~missingkids.com\|~missingkids.org\|~sainsburys.jobs\|~sitecore.com\|~amd.com | -- | `www.softcoretube.net` | 3 | script | `https://s7.addthis.com/js/250/addthis_widget.js` |
| +27 | \|\|theporndude.com/graphics/tpd-$3p | -- | `www.softcoretube.net` | 3 | image | `https://cdn1.theporndude.com/graphics/tpd-b-24px.png` |
| +27 |  |  | `www.softcoretube.net` | 1 | css | `https://softcoretube.net/static/styles/jquery.fancybox-white.css?v=7.5` |
| +27 |  |  | `www.softcoretube.net` | 1 | css | `https://softcoretube.net/static/styles/all-responsive-white.css?v=7.5` |
| +21 |  |  | `www.softcoretube.net` | 1 | doc | `https://www.softcoretube.net/` |
| +21 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo5MTU1ODIxMDEsInQiOjE2MDIzNDY5MzB9--94f2a4a7ee11b360a764e3463c0c59d89763f87a2299e8cf9fda1a2e0d8bb9f1&shared=true |
| +20 |  |  | `www.softcoretube.net` | 1 | doc | `http://www.softcoretube.net/` |
| +17 |  |  | softcoretube.net | 1 | image | `https://softcoretube.net/favicon.ico` |
| +16 | ##.bottom-adv |  | softcoretube.net |  | dom | `https://softcoretube.net/` |
| +16 | `##a[href^="https://www.im88trk.com/"]` |  | softcoretube.net |  | dom | `https://softcoretube.net/` |
| +16 | ##.social-bookmarks |  | softcoretube.net |  | dom | `https://softcoretube.net/` |
| +16 | ##.icon-share |  | softcoretube.net |  | dom | `https://softcoretube.net/` |
| +16 | ##.addthis_toolbox |  | softcoretube.net |  | dom | `https://softcoretube.net/` |
| +16 | ##.addthis_default_style |  | softcoretube.net |  | dom | `https://softcoretube.net/` |
| +16 | ##.addthis_button_compact |  | softcoretube.net |  | dom | `https://softcoretube.net/` |
| +16 | ##.addthis_32x32_style |  | softcoretube.net |  | dom | `https://softcoretube.net/` |
| +16 |  |  | softcoretube.net | 1 | image | `https://softcoretube.net/contents/videos_screenshots/0/311/320x180/1.jpg` |
| +16 |  |  | softcoretube.net | 1 | image | `https://softcoretube.net/contents/videos_screenshots/4000/4682/320x180/1.jpg` |
| +16 |  |  | softcoretube.net | 1 | image | `https://softcoretube.net/contents/videos_screenshots/0/149/320x180/1.jpg` |
| +16 |  |  | softcoretube.net | 1 | image | `https://softcoretube.net/contents/videos_screenshots/2000/2166/320x180/1.jpg` |
| +16 |  |  | softcoretube.net | 1 | image | `https://softcoretube.net/contents/videos_screenshots/2000/2740/320x180/1.jpg` |
| +16 |  |  | softcoretube.net | 1 | image | `https://softcoretube.net/contents/videos_screenshots/1000/1064/320x180/1.jpg` |
| +16 |  |  | softcoretube.net | 1 | image | `https://softcoretube.net/contents/videos_screenshots/0/420/320x180/1.jpg` |
| +16 |  |  | softcoretube.net | 1 | image | `https://softcoretube.net/contents/videos_screenshots/1000/1212/320x180/1.jpg` |
| +16 |  |  | softcoretube.net | 1 | image | `https://softcoretube.net/contents/videos_screenshots/1000/1758/320x180/1.jpg` |
| +16 | &action=js_stats& | -- | softcoretube.net | 1 | image | `https://softcoretube.net/?mode=async&action=js_stats&rand=1602346942949` |
| +16 | \|\|d38itq6vdv6gr9.cloudfront.net^ | -- | softcoretube.net | 3 | script | `https://d38itq6vdv6gr9.cloudfront.net/?vqtid=893655` |
| +16 | ://ads.$domain=~ads.ac.uk\|~ads.adstream.com.ro\|~ads.allegro.pl\|~ads.am\|~ads.atmosphere.copernicus.eu\|~ads.bigbom.com\|~ads.brave.com\|~ads.buscaempresas.co\|~ads.colombiaonline.com\|~ads.comeon.com\|~ads.cvut.cz\|~ads.dev.int.revelian.com\|~ads.dollartree.com\|~ads.elcarado.com\|~ads.google.com\|~ads.harvard.edu\|~ads.lapalingo.com\|~ads.lordlucky.com\|~ads.microsoft.com\|~ads.mobilebet.com\|~ads.msstate.edu\|~ads.mst.dk\|~ads.nc\|~ads.nimses.com\|~ads.odesbuild.com\|~ads.olx.pl\|~ads.pinterest.com\|~ads.quasaraffiliates.com\|~ads.red\|~ads.route.cc\|~ads.safi-gmbh.ch\|~ads.sk\|~ads.snapchat.com\|~ads.socialtheater.com\|~ads.spotify.com\|~ads.taboola.com\|~ads.tiktok.com\|~ads.toplayaffiliates.com\|~ads.viksaffiliates.com\|~ads.watson.ch\|~ads.xtribeapp.com\|~ads.yahoosmallbusiness.com\|~badassembly.com\|~caravansforsale.co.uk\|~fusac.fr\|~memo2.nl\|~reempresa.org\|~satmetrix.com\|~seriouswheels.com | -- | softcoretube.net | 3 | script | `https://ads.bullionyield.com/resources/slider.min.js` |
| +16 | \|\|wpush.org^$3p | -- | softcoretube.net | 3 | script | `https://sw.wpush.org/script/main.js?promo=17580&tcid=5095&src=241352630` |
| +16 | \|\|googletagmanager.com/gtag/$3p | -- | softcoretube.net | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-124378457-1` |
| +16 |  |  | softcoretube.net | 1 | font | `https://softcoretube.net/static/images/fonts/icomoon.ttf?nddhpi` |
| +15 |  |  | softcoretube.net | 1 | image | `https://softcoretube.net/static/images/search.svg` |
| +15 | \|\|exosrv.com^ | -- | softcoretube.net | 3 | frame | `https://a.exosrv.com/iframe.php?idzone=3780975&size=300x250` |
| +15 | \|\|exosrv.com^ | -- | softcoretube.net | 3 | frame | `https://a.exosrv.com/iframe.php?idzone=3780971&size=300x250` |
| +15 | \|\|exosrv.com^ | -- | softcoretube.net | 3 | frame | `https://a.exosrv.com/iframe.php?idzone=3780965&size=300x250` |
| +15 | \|\|exosrv.com^ | -- | softcoretube.net | 3 | frame | `https://a.exosrv.com/iframe.php?idzone=3780963&size=300x250` |
| +15 | \|\|theporndude.com/graphics/tpd-$3p | -- | softcoretube.net | 3 | image | `https://cdn1.theporndude.com/graphics/tpd-b-24px.png` |
| +15 | \|\|d38itq6vdv6gr9.cloudfront.net^ | -- | softcoretube.net | 3 | script | `https://d38itq6vdv6gr9.cloudfront.net/?vqtid=893655` |
| +15 | \|\|googletagmanager.com/gtag/$3p | -- | softcoretube.net | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-124378457-1` |
| +15 |  |  | softcoretube.net | 1 | script | `https://softcoretube.net/static/js/main.min.js?v=7.5` |
| +15 | addthis.com/addthis_widget.js | << | softcoretube.net |  | script | `https://s7.addthis.com/js/250/addthis_widget.js` |
| +15 | \|\|addthis.com^$3p,important,domain=~missingkids.com\|~missingkids.org\|~sainsburys.jobs\|~sitecore.com\|~amd.com | -- | softcoretube.net | 3 | script | `https://s7.addthis.com/js/250/addthis_widget.js` |
| +15 |  |  | softcoretube.net | 1 | image | `https://softcoretube.net/static/images/logo.png` |
| +15 | \|\|theporndude.com/graphics/tpd-$3p | -- | softcoretube.net | 3 | image | `https://cdn1.theporndude.com/graphics/tpd-b-24px.png` |
| +15 |  |  | softcoretube.net | 1 | css | `https://softcoretube.net/static/styles/jquery.fancybox-white.css?v=7.5` |
| +15 |  |  | softcoretube.net | 1 | css | `https://softcoretube.net/static/styles/all-responsive-white.css?v=7.5` |
| +13 |  |  | softcoretube.net | 1 | doc | `https://softcoretube.net/` |
| +12 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo5MTU1ODIxMDEsInQiOjE2MDIzNDY5MzB9--94f2a4a7ee11b360a764e3463c0c59d89763f87a2299e8cf9fda1a2e0d8bb9f1&shared=true |
| +12 |  |  | softcoretube.net | 1 | doc | `http://softcoretube.net/` |
| +8 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo5MTU1ODIxMDEsInQiOjE2MDIzNDY5MzB9--94f2a4a7ee11b360a764e3463c0c59d89763f87a2299e8cf9fda1a2e0d8bb9f1&shared=true |
| +6 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo5MTU1ODIxMDEsInQiOjE2MDIzNDY5MzB9--94f2a4a7ee11b360a764e3463c0c59d89763f87a2299e8cf9fda1a2e0d8bb9f1&shared=true |
| +5 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo5MTU1ODIxMDEsInQiOjE2MDIzNDY5MzB9--94f2a4a7ee11b360a764e3463c0c59d89763f87a2299e8cf9fda1a2e0d8bb9f1&shared=true |
| +5 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +4 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +2 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozNDQwMDU1MDgwLCJ0IjoxNjAyMzQ2OTI2fQ%3D%3D--8f75aea04fe2e8a9a521eed166e7547258749c3bf644386c3496d1082d7afefd&shared=true |
| +1 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozNDQwMDU1MDgwLCJ0IjoxNjAyMzQ2OTI2fQ%3D%3D--8f75aea04fe2e8a9a521eed166e7547258749c3bf644386c3496d1082d7afefd&shared=true |
| +0 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +0 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
</details>
