### ISSUE TITLE
joybear.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#327]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
joybear.com
media.joybear.com
www.joybear.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-224835](https://user-images.githubusercontent.com/38778536/95654300-ead14200-0b4a-11eb-8814-d7a643c6cdfa.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/hosts.txt)?
- [X] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +60 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MTE0NDY3NDA2LCJ0IjoxNjAyMzQ1NzQ4fQ%3D%3D--ae32f84916dab6ce35eaa90643d3b1785710062667d3aa52684b13b5f21e0c61&shared=true |
| +49 |  |  | joybear.com | 1 | image | `https://media.joybear.com/assets//images/favicons/favicon-16x16.png` |
| +49 |  |  | joybear.com | 1 | image | `https://media.joybear.com/assets//images/favicons/apple-touch-icon.png` |
| +43 | ###btnNewsletter |  | joybear.com |  | dom | `https://joybear.com/` |
| +43 |  |  | joybear.com | 1 | font | `https://media.joybear.com/assets//font/pro/Italic.otf` |
| +43 |  |  | joybear.com | 1 | font | `https://media.joybear.com/assets//font/fonts/fontawesome-webfont.woff2?v=4.5.0` |
| +43 |  |  | joybear.com | 1 | image | `https://media.joybear.com/assets//images/banner01.jpg` |
| +43 | \|\|googletagmanager.com/gtag/$3p | -- | joybear.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-45895023-1` |
| +43 |  |  | joybear.com | 1 | font | `https://media.joybear.com/assets//font/pro/Regular.otf` |
| +43 | \|\|googletagmanager.com/gtag/$3p | -- | joybear.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-45895023-1` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/js/custom.js?stamp=1601469571` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/js/scripts.js?stamp=1601465242` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/js/libs/jquery.form.min.js` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/js/libs/jquery.dotdotdot.min.js` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/js/components/search-box.js` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/js/libs/chosen/chosen.jquery.min.js` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/js/libs/slick.min.js` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/assets/images/logo.svg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/blog/vaginas-part-ii/cover/vaginas-part-ii_cover.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/blog/inspire-your-next-erotic-adventure-with-taste-of-honey/cover/inspire-your-next-erotic-adventure-with-taste-of-honey_cover.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/blog/reasons-to-masturbate-today/cover/reasons-to-masturbate-today_cover.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/blog/bts-with-nat-jesu-s/cover/bts-with-nat-jesu-s_cover.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/dvd/housemates-3-the-landlady/cover/housemates-3-the-landlady_cover.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/dvd/pleasure-fix/cover/pleasure-fix_cover.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/dvd/love-is-blind/cover/love-is-blind_cover.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/assets//images/flag.png` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/movies/love-your-cunt/cover/love-your-cunt_hd_soft.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/movies/be-yourself/cover/be-yourself_hd_soft.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/movies/the-apology/cover/the-apology_hd_soft.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/movies/corporate-affairs/cover/corporate-affairs_hd_soft.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/movies/taste-of-honey/cover/taste-of-honey_hd_soft.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/movies/surprise-anniversary/cover/surprise-anniversary_hd_soft.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/movies/marcel-alexa/cover/marcel-alexa_hd_soft.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/movies/observed/cover/observed_hd_soft.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/assets//images/play.svg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/content/movies/the-whole-package/cover/the-whole-package_hd_soft.jpg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/assets//images/XBiz-Award-2020.png` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/assets//images/award19.svg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/assets//images/award162.svg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/assets//images/award16.svg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/assets//images/award14.svg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/assets//images/award13.svg` |
| +42 |  |  | joybear.com | 1 | image | `https://media.joybear.com/assets/images/October1.3.jpg` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/js/carousel.js` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/js/cycle.js` |
| +42 |  |  | joybear.com | 1 | css | `https://media.joybear.com/assets/videojs/videojs-vtt-thumbnails.css` |
| +42 |  |  | joybear.com | 1 | css | `https://media.joybear.com/assets/videojs/videojs-resolution-switcher.css` |
| +42 |  |  | joybear.com | 1 | css | `https://media.joybear.com/assets/videojs/videojs.css` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/videojs/videojs-playlist.min.js` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/videojs/videojs.persistvolume.js` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/videojs/videojs-ie8.min.js` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/videojs/videojs-vtt-thumbnails.min.js` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/videojs/videojs-resolution-switcher.js` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/videojs/video.min.js` |
| +42 |  |  | joybear.com | 1 | script | `https://media.joybear.com/assets/js/libs/jquery-1.12.4.min.js` |
| +42 |  |  | joybear.com | 1 | css | `https://media.joybear.com/assets/js/libs/chosen/chosen.min.css` |
| +42 |  |  | joybear.com | 1 | css | `https://media.joybear.com/assets//styles/slick/slick-theme.css` |
| +42 |  |  | joybear.com | 1 | css | `https://media.joybear.com/assets//styles/slick/slick.css` |
| +42 |  |  | joybear.com | 1 | css | `https://media.joybear.com/assets//font/css/awesome.css` |
| +42 |  |  | joybear.com | 1 | css | `https://media.joybear.com/assets//styles/styles.css?stamp=1601465285` |
| +42 |  |  | joybear.com | 1 | css | `https://media.joybear.com/assets//styles/reset.css` |
| +41 |  |  | joybear.com | 1 | doc | `https://joybear.com/` |
| +41 |  |  | joybear.com | 1 | font | `https://media.joybear.com/assets//font/fonts/fontawesome-webfont.woff?v=4.5.0` |
| +41 |  |  | joybear.com | 1 | font | `https://media.joybear.com/assets//font/pro/Italic.ttf` |
| +41 |  |  | joybear.com | 1 | font | `https://media.joybear.com/assets//font/pro/Regular.ttf` |
| +41 | ###btnNewsletter |  | `www.joybear.com` |  | dom | `https://www.joybear.com/` |
| +41 |  |  | joybear.com | 1 | doc | `http://joybear.com/` |
| +41 | \|\|googletagmanager.com/gtag/$3p | -- | `www.joybear.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-45895023-1` |
| +41 |  |  | `www.joybear.com` | 1 | font | `https://media.joybear.com/assets//font/pro/Italic.otf` |
| +41 |  |  | `www.joybear.com` | 1 | font | `https://media.joybear.com/assets//font/fonts/fontawesome-webfont.woff2?v=4.5.0` |
| +41 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/assets//images/banner01.jpg` |
| +40 |  |  | `www.joybear.com` | 1 | font | `https://media.joybear.com/assets//font/pro/Regular.otf` |
| +38 | \|\|googletagmanager.com/gtag/$3p | -- | `www.joybear.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-45895023-1` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/js/custom.js?stamp=1601469571` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/js/scripts.js?stamp=1601465242` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/js/libs/jquery.form.min.js` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/js/libs/jquery.dotdotdot.min.js` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/js/components/search-box.js` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/js/libs/chosen/chosen.jquery.min.js` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/js/libs/slick.min.js` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/assets/images/logo.svg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/blog/vaginas-part-ii/cover/vaginas-part-ii_cover.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/blog/inspire-your-next-erotic-adventure-with-taste-of-honey/cover/inspire-your-next-erotic-adventure-with-taste-of-honey_cover.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/blog/reasons-to-masturbate-today/cover/reasons-to-masturbate-today_cover.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/blog/bts-with-nat-jesu-s/cover/bts-with-nat-jesu-s_cover.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/dvd/housemates-3-the-landlady/cover/housemates-3-the-landlady_cover.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/dvd/pleasure-fix/cover/pleasure-fix_cover.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/dvd/love-is-blind/cover/love-is-blind_cover.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/assets//images/flag.png` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/movies/love-your-cunt/cover/love-your-cunt_hd_soft.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/movies/fuck-normal/cover/fuck-normal_hd_soft.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/movies/breakfast-in-bed/cover/breakfast-in-bed_hd_soft.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/movies/the-stable-girl-offers-support/cover/the-stable-girl-offers-support_hd_soft.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/movies/taste-of-honey/cover/taste-of-honey_hd_soft.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/movies/experience/cover/experience_hd_soft.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/movies/my-dishy-new-head-of-design/cover/my-dishy-new-head-of-design_hd_soft.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/movies/shibari-reverie/cover/shibari-reverie_hd_soft.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/assets//images/play.svg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/content/movies/the-whole-package/cover/the-whole-package_hd_soft.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/assets//images/XBiz-Award-2020.png` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/assets//images/award19.svg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/assets//images/award162.svg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/assets//images/award16.svg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/assets//images/award14.svg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/assets//images/award13.svg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/assets/images/October1.3.jpg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/assets//images/logo.svg` |
| +38 |  |  | `www.joybear.com` | 1 | image | `https://media.joybear.com/assets//images/flag.svg` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/js/carousel.js` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/js/cycle.js` |
| +38 |  |  | `www.joybear.com` | 1 | css | `https://media.joybear.com/assets/videojs/videojs-vtt-thumbnails.css` |
| +38 |  |  | `www.joybear.com` | 1 | css | `https://media.joybear.com/assets/videojs/videojs-resolution-switcher.css` |
| +38 |  |  | `www.joybear.com` | 1 | css | `https://media.joybear.com/assets/videojs/videojs.css` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/videojs/videojs-playlist.min.js` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/videojs/videojs.persistvolume.js` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/videojs/videojs-ie8.min.js` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/videojs/videojs-vtt-thumbnails.min.js` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/videojs/videojs-resolution-switcher.js` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/videojs/video.min.js` |
| +38 |  |  | `www.joybear.com` | 1 | script | `https://media.joybear.com/assets/js/libs/jquery-1.12.4.min.js` |
| +38 |  |  | `www.joybear.com` | 1 | css | `https://media.joybear.com/assets/js/libs/chosen/chosen.min.css` |
| +38 |  |  | `www.joybear.com` | 1 | css | `https://media.joybear.com/assets//styles/slick/slick-theme.css` |
| +38 |  |  | `www.joybear.com` | 1 | css | `https://media.joybear.com/assets//styles/slick/slick.css` |
| +38 |  |  | `www.joybear.com` | 1 | css | `https://media.joybear.com/assets//font/css/awesome.css` |
| +38 |  |  | `www.joybear.com` | 1 | css | `https://media.joybear.com/assets//styles/styles.css?stamp=1601465285` |
| +38 |  |  | `www.joybear.com` | 1 | css | `https://media.joybear.com/assets//styles/reset.css` |
| +37 |  |  | `www.joybear.com` | 1 | doc | `https://www.joybear.com/` |
| +36 |  |  | `www.joybear.com` | 1 | doc | `http://www.joybear.com/` |
| +21 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +21 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +19 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +19 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +0 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozNjA0ODUyNDg3LCJ0IjoxNjAyMzQ1NTUwfQ%3D%3D--aeb54288cb38654463d6a56872e4cd9c3e3c0be14d3f967ec8765fc23cd3c0d9&shared=true |
</details>
