### ISSUE TITLE
danejones.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#329]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
www.danejones.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-225933](https://user-images.githubusercontent.com/38778536/95654580-9af37a80-0b4c-11eb-8de6-6fb930851abd.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [X] Added to [Source file](submit_here/hosts.txt)?
- [X] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +270 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozMDAwMDYzNDkxLCJ0IjoxNjAyMzQ1MDE3fQ%3D%3D--56c75a1bb36da9bd3eaedea498ee7fb2f3fae818b2ca1b0de4978100ac811b4f&shared=true |
| +254 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +222 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +210 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozMDAwMDYzNDkxLCJ0IjoxNjAyMzQ1MDE3fQ%3D%3D--56c75a1bb36da9bd3eaedea498ee7fb2f3fae818b2ca1b0de4978100ac811b4f&shared=true |
| +205 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +197 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +194 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIaldGO6Rr_d/982/240/d91/f7a/46d/488/c42/cd6/ad4/859/3d/poster/poster_01.webp` |
| +194 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=eyzaevFb/982/240/d91/f7a/46d/488/c42/cd6/ad4/859/3d/poster/poster_01.jpg` |
| +194 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIaldGO6Rr_d/3cf/c6f/d31/d22/4eb/494/559/5f5/aad/6b3/7d/poster/poster_01.webp` |
| +194 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=eyzaevFb/3cf/c6f/d31/d22/4eb/494/559/5f5/aad/6b3/7d/poster/poster_01.jpg` |
| +194 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIaldGO6Rr_d/a8f/1b8/df2/3ae/4b8/5a4/935/1b2/129/8c3/b2/poster/poster_01.webp` |
| +194 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=eyzaevFb/a8f/1b8/df2/3ae/4b8/5a4/935/1b2/129/8c3/b2/poster/poster_01.jpg` |
| +192 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +190 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +189 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +173 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIaldGO6Rr_d/4ba/70b/3a2/e9a/4e7/7b8/0cf/9d5/321/1a9/98/poster/poster_01.webp` |
| +173 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIaldGO6Rr_d/029/57c/362/a4b/47d/882/c0e/908/0b0/d97/cf/poster/poster_01.webp` |
| +173 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=eyzaevFb/029/57c/362/a4b/47d/882/c0e/908/0b0/d97/cf/poster/poster_01.jpg` |
| +173 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIaldGO6Rr_d/e08/858/cf5/44d/40c/8b0/1b9/be5/907/8d0/32/poster/poster_01.webp` |
| +170 |  |  | `www.danejones.com` | 3 | image | `https://images-assets-ht.project1content.com/Sexyhub/SubsiteTours/DaneJones/Logos/5cfa6f3f472383.11495873.png` |
| +170 | \|\|atsptp.com^$3p | -- | `www.danejones.com` | 3 | xhr | `https://atlas.atsptp.com/events?app_id=10303&eventName=TRACK&saffCode=eyJhIjo5NDk2LCJjIjo1NjU4NTQyNSwibiI6MzEsInMiOjI3MCwiZSI6OTI0MywicCI6M30%3D&saffCodeType=ats&saffDomain=projectone.com&snetworkCode=SH&sconversionType=TRACK&sconvertingPage=https%3A%2F%2Fwww.danejones.com%2F&suserAgent=Mozilla%2F5.0+(X11%3B+Ubuntu%3B+Linux+x86_64%3B+rv%3A81.0)+Gecko%2F20100101+Firefox%2F81.0&nvalue=1&nab=0&ssku=Legacy&ninstanceId=121322&npageId=1652602&nadId=0&sreferralDomain=http%3A%2F%2Forganic%2F&sreferralPath=http%3A%2F%2Forganic%2F&satlasJsVersion=1.5.6&_sscreen=1920+x+1080&_sbrowser=Firefox&_sbrowserVersion=81.0&_bmobile=false&_sos=Linux&_sosVersion=-&_bcookies=true&_sflashVersion=no+check&_slanguages=en-US%2Cen&_splugins=&_errors%5B%5D=100&_errors%5B%5D=%2C` |
| +170 | \|\|atsptp.com^$3p | -- | `www.danejones.com` | 3 | xhr | `https://atlas.atsptp.com/events?app_id=10303&eventName=UNIQUE_TRACK&saffCode=eyJhIjo5NDk2LCJjIjo1NjU4NTQyNSwibiI6MzEsInMiOjI3MCwiZSI6OTI0MywicCI6M30%3D&saffCodeType=ats&saffDomain=projectone.com&snetworkCode=SH&sconversionType=UNIQUE_TRACK&sconvertingPage=https%3A%2F%2Fwww.danejones.com%2F&suserAgent=Mozilla%2F5.0+(X11%3B+Ubuntu%3B+Linux+x86_64%3B+rv%3A81.0)+Gecko%2F20100101+Firefox%2F81.0&nvalue=1&nab=0&ssku=Legacy&ninstanceId=121322&npageId=1652602&nadId=0&sreferralDomain=http%3A%2F%2Forganic%2F&sreferralPath=http%3A%2F%2Forganic%2F&satlasJsVersion=1.5.6&_sscreen=1920+x+1080&_sbrowser=Firefox&_sbrowserVersion=81.0&_bmobile=false&_sos=Linux&_sosVersion=-&_bcookies=true&_sflashVersion=no+check&_slanguages=en-US%2Cen&_splugins=&_errors%5B%5D=100&_errors%5B%5D=%2C` |
| +170 |  |  | `www.danejones.com` | 3 | media | `https://assets-land-ht.contentdef.com/P1TOUR/DJ/dj_default_v0/hometgp/PC/R1_02.mp4` |
| +170 | \|\|atsptp.com^$3p | -- | `www.danejones.com` | 3 | xhr | `https://sync.atsptp.com/fp` |
| +170 | \|\|atsptp.com^$3p | -- | `www.danejones.com` | 3 | xhr | `https://atlas.atsptp.com/guid?app_id=&eventName=&` |
| +169 |  |  | `www.danejones.com` | 3 | image | `https://images-assets-ht.project1content.com/Sexyhub/Tour/Catfish/5d25f78d63d2e5.45618641.png` |
| +169 |  |  | `www.danejones.com` | 3 | xhr | `https://site-api.project1service.com/v2/releases?id=4360959%3B4393476%3B4360614%3B4352692%3B4361223%3B4360695&limit=6&offset=0&orderBy=-stats.rating` |
| +169 |  |  | `www.danejones.com` | 3 | xhr | `https://site-api.project1service.com/v2/releases?id=4360959%3B4393476%3B4360614%3B4352692%3B4361223%3B4360695&limit=6&offset=0&orderBy=-stats.rating` |
| +169 |  |  | `www.danejones.com` | 3 | xhr | `https://site-api.project1service.com/v2/releases?dateReleased=%3C2020-10-11&limit=6&offset=0&orderBy=-dateReleased&type=scene` |
| +169 |  |  | `www.danejones.com` | 3 | xhr | `https://site-api.project1service.com/v2/releases?dateReleased=%3C2020-10-11&limit=6&offset=0&orderBy=-dateReleased&type=scene` |
| +169 | google-analytics.com/analytics.js | << | `www.danejones.com` |  | script | `https://www.google-analytics.com/analytics.js` |
| +169 | \|\|google-analytics.com^ | -- | `www.danejones.com` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +169 |  |  | `www.danejones.com` | 3 | script | `https://static-ma-ht.project1content.com/static1/vortex.modern.min.js` |
| +159 |  |  | `www.danejones.com` | 3 | script | `https://static-ma-ht.project1content.com/static1/main.2d966559.js` |
| +159 |  |  | `www.danejones.com` | 3 | script | `https://static-ma-ht.project1content.com/static1/vendors~main.4aa10d1b.js` |
| +159 |  |  | `www.danejones.com` | 3 | script | `https://static-ma-ht.project1content.com/static1/runtime.d289717e.js` |
| +159 |  |  | `www.danejones.com` | 3 | script | `https://static-ma-ht.project1content.com/static1/@one/blocks/async/CatfishBlock.fbdd6bce.js` |
| +159 |  |  | `www.danejones.com` | 3 | script | `https://static-ma-ht.project1content.com/static1/@one/blocks/async/PopupBlock.e6305e89.js` |
| +159 |  |  | `www.danejones.com` | 3 | script | `https://static-ma-ht.project1content.com/static1/@one/blocks/async/DisclaimerBlock.c688e4e0.js` |
| +159 |  |  | `www.danejones.com` | 3 | script | `https://static-ma-ht.project1content.com/static1/@one/blocks/async/FooterBlock.ee6bc47f.js` |
| +159 |  |  | `www.danejones.com` | 3 | script | `https://static-ma-ht.project1content.com/static1/@one/blocks/async/FeaturedSceneListBlock.4dca3b80.js` |
| +159 |  |  | `www.danejones.com` | 3 | script | `https://static-ma-ht.project1content.com/static1/@one/blocks/async/ConditionalBlock.1d25711d.js` |
| +159 |  |  | `www.danejones.com` | 3 | script | `https://static-ma-ht.project1content.com/static1/@one/blocks/async/ImageBlock.8f7ef894.js` |
| +159 |  |  | `www.danejones.com` | 3 | script | `https://static-ma-ht.project1content.com/static1/@one/blocks/async/ColumnBlock.9a5dfb90.js` |
| +159 |  |  | `www.danejones.com` | 3 | script | `https://static-ma-ht.project1content.com/static1/@one/blocks/async/RowBlock.628a5921.js` |
| +159 |  |  | `www.danejones.com` | 3 | script | `https://static-ma-ht.project1content.com/static1/@one/blocks/async/HeaderBlock.744f5f51.js` |
| +159 |  |  | `www.danejones.com` | 3 | script | `https://static-ma-ht.project1content.com/static1/@one/blocks/async/ContainerBlock.6d0a6a74.js` |
| +159 |  |  | `www.danejones.com` | 3 | media | `https://assets-land-ht.contentdef.com/P1TOUR/DJ/dj_default_v0/hometgp/PC/R1_02.mp4` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://images-assets-ht.project1content.com/Common_Images/TransparentPNGs/5be0c6e6698b98.44447930.png` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://images-assets-ht.project1content.com/Common_Images/TransparentPNGs/5cacf58b861106.69237075.png` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://static-ma-ht.project1content.com/static1/assets/mg-addr.936dbc09.png` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://static-ma-ht.project1content.com/static1/assets/rta.6e25c31d.jpg` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://static-ma-ht.project1content.com/static1/assets/probiller.5f27a427.png` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://imageservice-assets-ht.project1content.com/m=bYi-b/assets/Sexyhub/Tour/CTA/5d14e945c2c6c2.69195633.webp` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://images-assets-ht.project1content.com/Sexyhub/SubsiteTours/DaneJones/Logos/5d1512880ce7a5.91764417.png` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIGLsLVg5p/4a6/5e7/308/7e8/4ad/29a/72a/a4b/d9a/9f7/04/poster/poster_01.webp` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIGLsLVg5p/314/a46/f1d/8a1/465/a80/bb9/4d1/0e0/a30/c9/poster/poster_01.webp` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIGLsLVg5p/b64/737/5c5/c79/4bc/193/0fd/e45/6aa/2d9/8b/poster/poster_01.webp` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIGLsLVg5p/ed9/a13/8c9/dc4/486/59b/cde/369/c9e/5c8/f3/poster/poster_01.webp` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIGLsLVg5p/d78/aef/6ce/0a3/42a/e88/ff8/6b6/0a2/a90/2d/poster/poster_01.webp` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIGLsLVg5p/bd8/b8f/cea/b52/472/ea3/335/737/07a/e13/ef/poster/poster_01.webp` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://imageservice-assets-ht.project1content.com/m=bYi-b/assets/Sexyhub/SubsiteTours/DaneJones/Banners/5e187be7c50f76.91996823.webp` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIGLsLVg5p/982/240/d91/f7a/46d/488/c42/cd6/ad4/859/3d/poster/poster_01.webp` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIGLsLVg5p/3cf/c6f/d31/d22/4eb/494/559/5f5/aad/6b3/7d/poster/poster_01.webp` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIGLsLVg5p/a8f/1b8/df2/3ae/4b8/5a4/935/1b2/129/8c3/b2/poster/poster_01.webp` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIGLsLVg5p/4ba/70b/3a2/e9a/4e7/7b8/0cf/9d5/321/1a9/98/poster/poster_01.webp` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIGLsLVg5p/029/57c/362/a4b/47d/882/c0e/908/0b0/d97/cf/poster/poster_01.webp` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://media-public-ht.project1content.com/m=bIGLsLVg5p/e08/858/cf5/44d/40c/8b0/1b9/be5/907/8d0/32/poster/poster_01.webp` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://assets-land-ht.contentdef.com/P1TOUR/DJ/dj_default_v0/hometgp/PC/R2_04.jpg` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://assets-land-ht.contentdef.com/P1TOUR/DJ/dj_default_v0/hometgp/PC/R2_03.jpg` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://assets-land-ht.contentdef.com/P1TOUR/DJ/dj_default_v0/hometgp/PC/R2_02.jpg` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://assets-land-ht.contentdef.com/P1TOUR/DJ/dj_default_v0/hometgp/PC/R2_01.jpg` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://assets-land-ht.contentdef.com/P1TOUR/DJ/dj_default_v0/hometgp/PC/R1_04.jpg` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://assets-land-ht.contentdef.com/P1TOUR/DJ/dj_default_v0/hometgp/PC/R1_03.jpg` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://assets-land-ht.contentdef.com/P1TOUR/DJ/dj_default_v0/hometgp/MO/R1_01.jpg` |
| +159 |  |  | `www.danejones.com` | 3 | image | `https://images-assets-ht.project1content.com/Sexyhub/SubsiteTours/DaneJones/Logos/5d81232600ea78.03753764.png` |
| +159 | \|\|googleapis.com^$important | -- | `www.danejones.com` | 3 | css | `https://fonts.googleapis.com/css?family=Droid+Sans:400,700` |
| +156 |  |  | `www.danejones.com` | 1 | doc | `https://www.danejones.com/` |
| +156 |  |  | danejones.com | 1 | doc | `http://danejones.com/` |
| +150 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozMDAwMDYzNDkxLCJ0IjoxNjAyMzQ1MDE3fQ%3D%3D--56c75a1bb36da9bd3eaedea498ee7fb2f3fae818b2ca1b0de4978100ac811b4f&shared=true |
| +95 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +95 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +90 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo1ODIyMDA1NDYsInQiOjE2MDIzNDUwMTF9--fbe73f76f740d6766b17495f581340f30b29228ee0ad61c84f6674f383d8ee82&shared=true |
| +90 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +90 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +29 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +0 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxMDUxNTMxMzksInQiOjE2MDIzNDQ1NDh9--366d85dff5559a57af8d26364c95ad24819ab6814836d76b7bcc5fdddc206255&shared=true |
</details>
