### ISSUE TITLE
couplescinema.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#330]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
couplescinema.com
www.couplescinema.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-230423](https://user-images.githubusercontent.com/38778536/95654645-1523ff00-0b4d-11eb-89a8-34d9f6560efd.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +352 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +323 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxMDUxNTMxMzksInQiOjE2MDIzNDQ1NDh9--366d85dff5559a57af8d26364c95ad24819ab6814836d76b7bcc5fdddc206255&shared=true |
| +292 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +263 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxMDUxNTMxMzksInQiOjE2MDIzNDQ1NDh9--366d85dff5559a57af8d26364c95ad24819ab6814836d76b7bcc5fdddc206255&shared=true |
| +232 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +203 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxMDUxNTMxMzksInQiOjE2MDIzNDQ1NDh9--366d85dff5559a57af8d26364c95ad24819ab6814836d76b7bcc5fdddc206255&shared=true |
| +172 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +143 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxMDUxNTMxMzksInQiOjE2MDIzNDQ1NDh9--366d85dff5559a57af8d26364c95ad24819ab6814836d76b7bcc5fdddc206255&shared=true |
| +137 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +121 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +112 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +108 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +106 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +105 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +83 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxMDUxNTMxMzksInQiOjE2MDIzNDQ1NDh9--366d85dff5559a57af8d26364c95ad24819ab6814836d76b7bcc5fdddc206255&shared=true |
| +59 |  |  | `www.couplescinema.com` | 1 | image | `https://www.couplescinema.com/bundles/mmfrontend/couplescinema/images/fav.png` |
| +54 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_gentledesire/videos/b585c01eb2102cb30d2e16aa26fa1910/cum-on-these-006.jpg` |
| +54 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_eroticstories/videos/cb04663897b03f5ffbefb784338d8fb6/live-within-the-moment-005.jpg` |
| +54 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_eroticstories/videos/95e37723ee9bfae7910edb8d8e4d4a5b/safe-word-005.jpg` |
| +54 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/10092020172144/0765b917f6ac69c9a0ba7ebb6cc75ad0.jpg` |
| +54 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/10092020174007/03b0d82c910c70eee5516e34b1dc8bf6.jpg` |
| +54 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/11092020085845/bf5a98ef878fd83786cf53c9c883300f.jpg` |
| +54 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/11092020090910/c4bcea4e8a4f2610c7c7049927bde2d9.jpg` |
| +54 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_eroticstories/videos/89f56e801ce6f92c6cd4c4a20324866b/the-note-005.jpg` |
| +54 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_gentledesire/videos/f59205f32bdcec5e3af6ffa458ccd923/patiently-waiting-for-fun--006.jpg` |
| +54 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/11092020085454/efd50f7757c5905366658285395e5c71.jpg` |
| +54 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/10092020172958/a375ed618352143462706e3a113abe98.jpg` |
| +54 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/11092020090247/372129c122f7d755df66abf0b7736911.jpg` |
| +53 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_petrajoy/videos/5cbd25d2dfd585093a24a8943681fee0/e9a73f4f76362d8b05be69ad3e01bd7b.jpg` |
| +53 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_versocinema/videos/501f04cd3d12ddfb4fb83acb2432b32b/driving-007.jpg` |
| +53 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_versocinema/videos/31d8a5ec1a8de0cb263bb9fc376d02ba/61b05ba1c5b6d05126eaad5924ae1b85.jpg` |
| +53 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_versocinema/videos/335ce19b362f1b33f577aec08e9375ab/deb1555d24fb69c658999b11089ba3c3.jpg` |
| +53 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_versocinema/videos/f9580ef7d6fe83e417f9b1e0aae39b99/199483afb70d9e77ae37a2e5c255467d.jpg` |
| +53 |  |  | `www.couplescinema.com` | 1 | image | `https://www.couplescinema.com/bundles/mmfrontend/couplescinema/images/tourMission.jpg` |
| +53 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_couplefantasies/videos/61df20290f57fef09a4ff011d8ea75df/782c57ea7332bb84d9202b06a21f0898.jpg` |
| +53 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_couplefantasies/videos/36eb4336dc07817e8bcba2580b6a6e32/53db6cfc0b3c758907cb835b1fab2908.jpg` |
| +53 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_couplefantasies/videos/c00a2947d8903b46a385ca3f29c8dd1e/dc19377906222fc9a0000cc9e67ab2a5.jpg` |
| +53 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_couplefantasies/videos/c665e0f66160ecc5b522d21331ba5cd9/d79b13329f4d9763938e7f5a58b0df7f.jpg` |
| +53 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_mariabeatty/videos/2a6ae20cdafb1e6a155a175d5de2537d/948046b120f3f675b5231e6fc2e5cfc1.jpg` |
| +53 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_petrajoy/videos/5b23dee2d70e338faffbd09b844692ac/46113959c8bab0174644635e0ee36b0b.jpg` |
| +53 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_versocinema/videos/c2daac30b1bce4f9c3363524780cae26/7fdffc4024890d5b97393d82841b6026.jpg` |
| +53 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/joybear/videos/29062020120027/4477fa38b42d1277b5c9b89e04bf677e.jpg` |
| +53 | \|\|googletagmanager.com/gtag/$3p | -- | `www.couplescinema.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-173972048-1` |
| +52 |  |  | `www.couplescinema.com` | 1 | image | `https://www.couplescinema.com/bundles/mmfrontend/couplescinema/images/tourBenefits.jpg` |
| +52 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmcore/plugins/bgmosaic/xlabs.bgmosaic.js` |
| +52 | \|\|googletagmanager.com/gtag/$3p | -- | `www.couplescinema.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-173972048-1` |
| +52 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmcore/plugins/jquery.carousel/jquery.carousel.js` |
| +52 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmfrontend/js/jquery.cycle2.js` |
| +52 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmcore/plugins/jquery.preloader/jquery.preloader.js` |
| +52 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmfrontend/js/avatarCropper.js` |
| +52 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmcore/plugins/cropper/cropper.js` |
| +52 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmfrontend/js/jquery.validate.js` |
| +52 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmfrontend/js/jquery-ui.min.1121.js` |
| +52 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/atmemojis/js/jquery.emojis.js` |
| +52 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/atmcomment/js/comments.js` |
| +52 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/js/d2a80bf.js` |
| +52 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmcore/jquery-1.11.2.min.js` |
| +52 |  |  | `www.couplescinema.com` | 1 | doc | `https://www.couplescinema.com/` |
| +46 |  |  | couplescinema.com | 1 | doc | `https://couplescinema.com/` |
| +45 |  |  | couplescinema.com | 1 | doc | `http://couplescinema.com/` |
| +38 |  |  | `www.couplescinema.com` | 1 | image | `https://www.couplescinema.com/bundles/mmfrontend/couplescinema/images/fav.png` |
| +25 |  |  | `www.couplescinema.com` | 3 | font | `https://cdn.static.3tech.xyz/media/gasm/assets/fonts/font-awesome/webfonts/fa-solid-900.woff2` |
| +25 |  |  | `www.couplescinema.com` | 3 | font | `https://cdn.static.3tech.xyz/media/gasm/assets/fonts/font-awesome/webfonts/fa-regular-400.woff2` |
| +25 |  |  | `www.couplescinema.com` | 1 | font | `https://www.couplescinema.com/bundles/mmfrontend/fonts/Lato/Lato-Medium.woff2` |
| +25 |  |  | `www.couplescinema.com` | 1 | font | `https://www.couplescinema.com/bundles/mmfrontend/fonts/Lato/Lato-BoldItalic.woff2` |
| +25 |  |  | `www.couplescinema.com` | 1 | font | `https://www.couplescinema.com/bundles/mmfrontend/fonts/Lato/Lato-Bold.woff2` |
| +25 |  |  | `www.couplescinema.com` | 1 | font | `https://www.couplescinema.com/bundles/mmfrontend/fonts/Lato/Lato-Regular.woff2` |
| +25 |  |  | `www.couplescinema.com` | 1 | font | `https://www.couplescinema.com/bundles/mmfrontend/fonts/Lato/Lato-Italic.woff2` |
| +25 |  |  | `www.couplescinema.com` | 1 | image | `https://www.couplescinema.com/bundles/mmfrontend/couplescinema/images/item/locked-white.svg` |
| +23 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_gentledesire/videos/b585c01eb2102cb30d2e16aa26fa1910/cum-on-these-006.jpg` |
| +23 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_mariabeatty/videos/d707c2b675368c3c0cc084c948394217/f1d034176f56e74107a39a511271d441.jpg` |
| +23 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_eroticstories/videos/cb04663897b03f5ffbefb784338d8fb6/live-within-the-moment-005.jpg` |
| +23 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/09092020150522/c129015b8ca1532376b9fb92aee72b01.jpg` |
| +23 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/10092020175539/efc4e6fecc9265a654ca7c12c5ec3f20.jpg` |
| +23 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_eroticstories/videos/95e37723ee9bfae7910edb8d8e4d4a5b/safe-word-005.jpg` |
| +23 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/10092020172144/0765b917f6ac69c9a0ba7ebb6cc75ad0.jpg` |
| +23 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/10092020174007/03b0d82c910c70eee5516e34b1dc8bf6.jpg` |
| +23 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/11092020085845/bf5a98ef878fd83786cf53c9c883300f.jpg` |
| +23 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/11092020090910/c4bcea4e8a4f2610c7c7049927bde2d9.jpg` |
| +23 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_eroticstories/videos/89f56e801ce6f92c6cd4c4a20324866b/the-note-005.jpg` |
| +23 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_gentledesire/videos/f59205f32bdcec5e3af6ffa458ccd923/patiently-waiting-for-fun--006.jpg` |
| +23 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/11092020085454/efd50f7757c5905366658285395e5c71.jpg` |
| +23 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/10092020172958/a375ed618352143462706e3a113abe98.jpg` |
| +23 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/commonsensual/videos/11092020090247/372129c122f7d755df66abf0b7736911.jpg` |
| +23 | \|\|googletagmanager.com/gtag/$3p | -- | `www.couplescinema.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-173972048-1` |
| +23 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxMDUxNTMxMzksInQiOjE2MDIzNDQ1NDh9--366d85dff5559a57af8d26364c95ad24819ab6814836d76b7bcc5fdddc206255&shared=true |
| +21 |  |  | `www.couplescinema.com` | 1 | image | `https://www.couplescinema.com/bundles/mmfrontend/couplescinema/images/defaultProfile.svg` |
| +21 |  |  | `www.couplescinema.com` | 1 | image | `https://www.couplescinema.com/bundles/mmfrontend/couplescinema/images/tourBenefits.jpg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_petrajoy/videos/871fb2bb8fa048ac6fbc14ae630c00df/c8b6d42e4dc8fd9183ea0315bd41ca7c.jpg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_petrajoy/videos/30a11f0a81313c8d283816d1eb16fe0a/aa60d93645662e337a50529262b479fa.jpg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_petrajoy/videos/31888507da8a11272c38dafbae697207/dance-for-me-005.jpg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_petrajoy/videos/5cbd25d2dfd585093a24a8943681fee0/e9a73f4f76362d8b05be69ad3e01bd7b.jpg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_versocinema/videos/501f04cd3d12ddfb4fb83acb2432b32b/driving-007.jpg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_versocinema/videos/31d8a5ec1a8de0cb263bb9fc376d02ba/61b05ba1c5b6d05126eaad5924ae1b85.jpg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_versocinema/videos/335ce19b362f1b33f577aec08e9375ab/deb1555d24fb69c658999b11089ba3c3.jpg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_versocinema/videos/f9580ef7d6fe83e417f9b1e0aae39b99/199483afb70d9e77ae37a2e5c255467d.jpg` |
| +21 |  |  | `www.couplescinema.com` | 1 | image | `https://www.couplescinema.com/bundles/mmfrontend/couplescinema/images/tourMission.jpg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_couplefantasies/videos/61df20290f57fef09a4ff011d8ea75df/782c57ea7332bb84d9202b06a21f0898.jpg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_couplefantasies/videos/36eb4336dc07817e8bcba2580b6a6e32/53db6cfc0b3c758907cb835b1fab2908.jpg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_couplefantasies/videos/c00a2947d8903b46a385ca3f29c8dd1e/dc19377906222fc9a0000cc9e67ab2a5.jpg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_couplefantasies/videos/c665e0f66160ecc5b522d21331ba5cd9/d79b13329f4d9763938e7f5a58b0df7f.jpg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_mariabeatty/videos/2a6ae20cdafb1e6a155a175d5de2537d/948046b120f3f675b5231e6fc2e5cfc1.jpg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_petrajoy/videos/5b23dee2d70e338faffbd09b844692ac/46113959c8bab0174644635e0ee36b0b.jpg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/mm_versocinema/videos/c2daac30b1bce4f9c3363524780cae26/7fdffc4024890d5b97393d82841b6026.jpg` |
| +21 |  |  | `www.couplescinema.com` | 1 | image | `https://www.couplescinema.com/bundles/mmfrontend/couplescinema/images/icons/play2B.svg` |
| +21 |  |  | `www.couplescinema.com` | 3 | image | `https://cdn.static.3tech.xyz/media/couplescinema/studios/joybear/videos/29062020120027/4477fa38b42d1277b5c9b89e04bf677e.jpg` |
| +21 |  |  | `www.couplescinema.com` | 1 | image | `https://www.couplescinema.com/bundles/mmfrontend/couplescinema/images/baseTall.svg` |
| +21 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmcore/plugins/bgmosaic/xlabs.bgmosaic.js` |
| +21 |  |  | `www.couplescinema.com` | 1 | css | `https://www.couplescinema.com/bundles/mmcore/plugins/bgmosaic/xlabs.bgmosaic.css` |
| +21 |  |  | `www.couplescinema.com` | 1 | image | `https://www.couplescinema.com/bundles/mmfrontend/couplescinema/images/icons/burger.svg` |
| +21 |  |  | `www.couplescinema.com` | 1 | image | `https://www.couplescinema.com/bundles/mmfrontend/couplescinema/images/logoMin.svg` |
| +21 |  |  | `www.couplescinema.com` | 1 | image | `https://www.couplescinema.com/bundles/mmfrontend/couplescinema/images/logo.svg` |
| +21 |  |  | `www.couplescinema.com` | 1 | image | `https://www.couplescinema.com/bundles/mmfrontend/couplescinema/images/icons/close.svg` |
| +21 | \|\|googletagmanager.com/gtag/$3p | -- | `www.couplescinema.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-173972048-1` |
| +21 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmcore/plugins/jquery.carousel/jquery.carousel.js` |
| +21 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmfrontend/js/jquery.cycle2.js` |
| +21 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmcore/plugins/jquery.preloader/jquery.preloader.js` |
| +21 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmfrontend/js/avatarCropper.js` |
| +21 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmcore/plugins/cropper/cropper.js` |
| +21 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmfrontend/js/jquery.validate.js` |
| +21 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmfrontend/js/jquery-ui.min.1121.js` |
| +21 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/atmemojis/js/jquery.emojis.js` |
| +21 |  |  | `www.couplescinema.com` | 1 | css | `https://www.couplescinema.com/bundles/atmemojis/css/emojis.css` |
| +21 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/atmcomment/js/comments.js` |
| +21 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/js/d2a80bf.js` |
| +21 |  |  | `www.couplescinema.com` | 1 | script | `https://www.couplescinema.com/bundles/mmcore/jquery-1.11.2.min.js` |
| +21 |  |  | `www.couplescinema.com` | 1 | css | `https://www.couplescinema.com/bundles/mmfrontend/css/jquery-ui.css` |
| +21 |  |  | `www.couplescinema.com` | 1 | css | `https://www.couplescinema.com/bundles/mmcore/plugins/cropper/cropper.css` |
| +21 |  |  | `www.couplescinema.com` | 1 | css | `https://www.couplescinema.com/media/couplescinema/assets/fonts/font-awesome/css/all.css` |
| +21 |  |  | `www.couplescinema.com` | 1 | css | `https://www.couplescinema.com/bundles/mmfrontend/fonts/lato.css` |
| +21 |  |  | `www.couplescinema.com` | 1 | css | `https://www.couplescinema.com/bundles/mmfrontend/couplescinema/styles/base_arnau.css` |
| +18 |  |  | `www.couplescinema.com` | 1 | doc | `https://www.couplescinema.com/` |
| +17 |  |  | `www.couplescinema.com` | 1 | doc | `http://www.couplescinema.com/` |
| +10 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +10 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +7 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +7 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +3 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +1 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +0 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
</details>
