### ISSUE TITLE
frolicme.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#331]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
frolicme.com
www.frolicme.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-230822](https://user-images.githubusercontent.com/38778536/95654711-9e3b3600-0b4d-11eb-9640-6e75fff3e75f.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +196 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxNTY3NjgwNjgwLCJ0IjoxNjAyMzQ0NDQzfQ%3D%3D--b3803ad6dc2eea70642b70ee00d751bb3291f4c9cff8afceda82f73674b2cdc1&shared=true |
| +183 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/imgsvc/fit/430/0/ce/0/aHR0cHM6Ly93d3cuZnJvbGljbWUuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE4LzAzLzYwMHgyNTUtNS1lMTU3MzIzNjQ1ODYxMS5qcGc=.jpg` |
| +183 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/imgsvc/fit/300/0/ce/0/aHR0cHM6Ly93d3cuZnJvbGljbWUuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE0LzAxLzI1NXgzMDAtR0FMTEVSWS5qcGc=.jpg` |
| +183 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/imgsvc/fit/460/0/ce/0/aHR0cHM6Ly93d3cuZnJvbGljbWUuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDIwLzAyL21hZ2F6aW5lLWFydGljbGVzLTEwODB4OTE4LTYuanBn.jpg` |
| +182 |  |  | `www.frolicme.com` | 3 | xhr | `https://d1442exqiprt72.cloudfront.net/013%20-%20SIR/TEASER-013-SIR-HLS-HOME-PAGE/encoded-16-47-54-tue-sep-2018/480p/encoded-16-47-54-tue-sep-2018.m3u8` |
| +182 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/imgsvc/fit/1000/0/ce/0/aHR0cHM6Ly93d3cuZnJvbGljbWUuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE5LzExL0hPTUUtUEFHRS1IRUFERVItMTAwMC0xOTAuanBn.jpg` |
| +182 |  |  | `www.frolicme.com` | 3 | xhr | `https://d1442exqiprt72.cloudfront.net/013%20-%20SIR/TEASER-013-SIR-HLS-HOME-PAGE/encoded-16-47-54-tue-sep-2018/240p/encoded-16-47-54-tue-sep-201800000.ts` |
| +182 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/imgsvc/fit/666/0/ce/0/aHR0cHM6Ly93d3cuZnJvbGljbWUuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE0LzAxLzAxMy1TSVItU0hPVy1SRUFMNS5qcGc=.jpg` |
| +182 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/imgsvc/fit/1000/0/ce/0/aHR0cHM6Ly93d3cuZnJvbGljbWUuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE5LzA1L0hPTUUtUEFHRS1IRUFERVItMTAwMC0xODguanBn.jpg` |
| +182 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/imgsvc/fit/1000/0/ce/0/aHR0cHM6Ly93d3cuZnJvbGljbWUuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE5LzExL0hPTUUtUEFHRS1IRUFERVItMTAwMC0xOTIuanBn.jpg` |
| +182 | ##div[button="share"] |  | `www.frolicme.com` |  | dom | `https://www.frolicme.com/` |
| +182 | `##[href^="https://www.facebook.com"]` |  | `www.frolicme.com` |  | dom | `https://www.frolicme.com/` |
| +182 | `##[href^="https://twitter.com"]` |  | `www.frolicme.com` |  | dom | `https://www.frolicme.com/` |
| +182 | ##.social-icons |  | `www.frolicme.com` |  | dom | `https://www.frolicme.com/` |
| +182 | ##.social-cta |  | `www.frolicme.com` |  | dom | `https://www.frolicme.com/` |
| +182 | ##.overlay |  | `www.frolicme.com` |  | dom | `https://www.frolicme.com/` |
| +182 | ##.jw-settings-sharing |  | `www.frolicme.com` |  | dom | `https://www.frolicme.com/` |
| +182 | ##.afs_ads |  | `www.frolicme.com` |  | dom | `https://www.frolicme.com/` |
| +182 |  |  | `www.frolicme.com` | 3 | xhr | `https://d1442exqiprt72.cloudfront.net/013%20-%20SIR/TEASER-013-SIR-HLS-HOME-PAGE/encoded-16-47-54-tue-sep-2018/240p/encoded-16-47-54-tue-sep-2018.m3u8` |
| +182 |  |  | `www.frolicme.com` | 3 | xhr | `https://d1442exqiprt72.cloudfront.net/013%20-%20SIR/TEASER-013-SIR-HLS-HOME-PAGE/encoded-16-47-54-tue-sep-2018/encoded-16-47-54-tue-sep-2018.m3u8` |
| +182 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/wp-content/uploads/2020/01/frolic-icon-380x380-150x150.png` |
| +182 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/wp-content/uploads/2020/01/frolic-icon-380x380.png` |
| +181 |  |  | `www.frolicme.com` | 1 | xhr | `https://www.frolicme.com/wp/wp-admin/admin-ajax.php` |
| +181 |  |  | `www.frolicme.com` | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.16.3/provider.hlsjs.js` |
| +181 |  |  | `www.frolicme.com` | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.16.3/jwplayer.core.controls.js` |
| +181 | /gapro.js | -- | `www.frolicme.com` | 3 | script | `https://ssl.p.jwpcdn.com/player/plugins/gapro/v/2.1.5/gapro.js` |
| +181 |  |  | `www.frolicme.com` | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.16.3/jwpsrv.js` |
| +181 | \|\|polyfill.io^$3p | -- | `www.frolicme.com` | 3 | script | `https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch%2Cdefault&ver=v3` |
| +181 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/imgsvc/fit/460/0/ce/0/aHR0cHM6Ly93d3cuZnJvbGljbWUuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE5LzExL2F1ZGlvLXBvcm4tc3Rvcmllcy0xMDgweDkxOC0zLmpwZw==.jpg` |
| +181 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/imgsvc/fit/460/0/ce/0/aHR0cHM6Ly93d3cuZnJvbGljbWUuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDIwLzAyL2Vyb3RpYy1zZXgtc3Rvcmllcy0xMDgweDkxOC0zLmpwZw==.jpg` |
| +181 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/imgsvc/fit/460/0/ce/0/aHR0cHM6Ly93d3cuZnJvbGljbWUuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE5LzExL2Vyb3RpYy12aWRlb3Mtc2V4LWZpbG1zLTEwODB4OTE4LTMuanBn.jpg` |
| +181 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/imgsvc/fit/1000/0/ce/0/aHR0cHM6Ly93d3cuZnJvbGljbWUuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE5LzExL0hPTUUtUEFHRS1IRUFERVItMTAwMC0xOTEuanBn.jpg` |
| +181 | /simple-share-$image | -- | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/wp-content/plugins/simple-share-buttons-plus/images/simple-share-buttons-logo-white.png` |
| +181 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/wp-content/uploads/2018/07/Twitter_Squ_icon_100.png` |
| +181 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/wp-content/uploads/2018/07/Instagram_Squ_icon_100.png` |
| +181 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/wp-content/themes/frolicme/assets/img/site/dmca-badge-w150-5x1-09-min.png` |
| +181 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/wp-content/uploads/2017/10/POP-UP-OFFER-Autumn-Offer-2-2017.jpg` |
| +181 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/wp-content/uploads/2020/04/STAY-HOME.jpg` |
| +181 |  |  | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/wp-content/themes/frolicme/assets/img/site/logo.png` |
| +181 | \|\|images.dmca.com^$3p | -- | `www.frolicme.com` | 3 | script | `https://images.dmca.com/Badges/DMCABadgeHelper.min.js` |
| +181 | \|\|googletagmanager.com/gtag/$3p | -- | `www.frolicme.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-39607782-1` |
| +181 |  |  | `www.frolicme.com` | 1 | script | `https://www.frolicme.com/wp-content/plugins/icegram/assets/js/main.min.js?ver=1.9.23` |
| +181 |  |  | `www.frolicme.com` | 1 | script | `https://www.frolicme.com/wp/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1` |
| +181 |  |  | `www.frolicme.com` | 1 | script | `https://www.frolicme.com/wp/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp` |
| +181 |  |  | `www.frolicme.com` | 1 | script | `https://www.frolicme.com/wp-content/themes/frolicme/assets/v2/video-player.bundle.js?ver=a3e0da27d51263ec4132` |
| +181 |  |  | `www.frolicme.com` | 1 | script | `https://www.frolicme.com/wp-content/themes/frolicme/assets/v2/front-page.bundle.js?ver=a3e0da27d51263ec4132` |
| +181 |  |  | `www.frolicme.com` | 1 | script | `https://www.frolicme.com/wp-content/themes/frolicme/assets/v2/common.bundle.js?ver=a3e0da27d51263ec4132` |
| +181 | \|\|polyfill.io^$3p | -- | `www.frolicme.com` | 3 | script | `https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch%2Cdefault&ver=v3` |
| +181 |  |  | `www.frolicme.com` | 1 | script | `https://www.frolicme.com/wp/wp-includes/js/comment-reply.min.js?ver=5.4.2` |
| +181 | /simple-share-$image | -- | `www.frolicme.com` | 1 | image | `https://www.frolicme.com/wp-content/plugins/simple-share-buttons-plus/images/simple-share-buttons-logo-white.png` |
| +181 | \|\|images.dmca.com^$3p | -- | `www.frolicme.com` | 3 | script | `https://images.dmca.com/Badges/DMCABadgeHelper.min.js` |
| +181 | \|\|googletagmanager.com/gtag/$3p | -- | `www.frolicme.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-39607782-1` |
| +181 | \|\|googleapis.com^$important | -- | `www.frolicme.com` | 3 | css | `https://fonts.googleapis.com/css?family=Lato%3A100%2C300%2C400%2C700%2C900%2C100italic%2C300italic%2C400italic%2C700italic%2C900italic&ver=1.2.0` |
| +181 | -social-sidebar/ | -- | `www.frolicme.com` | 1 | css | `https://www.frolicme.com/wp-content/plugins/FLM-Social-Sidebar/Assets/Styles/Social-Sidebar.min.css?ver=5.4.2` |
| +181 | /cdn-cgi/apps/head/*$script,1p | -- | `www.frolicme.com` | 1 | script | `https://www.frolicme.com/cdn-cgi/apps/head/JrQ7yOb2LHVvgAm3Mbw8gjzlpkE.js` |
| +180 |  |  | `www.frolicme.com` | 1 | doc | `https://www.frolicme.com/` |
| +138 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +138 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +136 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxNjk4NzU5OTc2LCJ0IjoxNjAyMzQ0NDQwfQ%3D%3D--cc619ed0574bfbb322739fb25d115f7c88ac71250b11c33acb9c7df5e286d6ae&shared=true |
| +135 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +135 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +124 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +123 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +120 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +120 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +113 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +112 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +107 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +102 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +100 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +99 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +76 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozNTE4MjEwNjM2LCJ0IjoxNjAyMzQ0MzA5fQ%3D%3D--44087d8a3c63c1c680e9b4204d75eabf922efea33ea4b35c0a8f160434057ad4&shared=true |
| +16 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozNTE4MjEwNjM2LCJ0IjoxNjAyMzQ0MzA5fQ%3D%3D--44087d8a3c63c1c680e9b4204d75eabf922efea33ea4b35c0a8f160434057ad4&shared=true |
| +4 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +3 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +1 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +0 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
</details>
