### ISSUE TITLE
lustery.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#333]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
lustery.com
www.lustery.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-232010](https://user-images.githubusercontent.com/38778536/95654928-574e4000-0b4f-11eb-85e7-315e8cacf9e1.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
Including `p7t9r6h4.ssl.hwcdn.net`

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +8 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjozMjM1OTcyODIsInQiOjE2MDIzNDA5OTB9--5ed02346eea0927a21deab05758f4b7b7f9eb92c8bf1ee26db8844130998470d&shared=true |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/cache/model_thumb/image/Kim%20%26%20Leo-squashed_5f438eae2fba7.jpg?version=1598263329` |
| +6 | \|\|inspectlet.com^$3p | -- | lustery.com | 3 | script | `https://cdn.inspectlet.com/inspectlet.js` |
| +6 | \|\|js-agent.newrelic.com^ | -- | lustery.com | 3 | script | `https://js-agent.newrelic.com/nr-1184.min.js` |
| +6 | /favicon.ico$image,3p,domain=~douban.com\|~bahn.de\|~winfuture.de\|~bt.com\|~ebay.com.au\|~ebay.com\|~ebay.co.uk\|~go.com\|~github.com\|~stackexchange.com\|~stackoverflow.com\|~askubuntu.com\|~reddit.com\|~4chan.org\|~twitter.com\|~live.com\|~espn.com\|~yahoo.com | -- | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/favicon.ico?version=1522160371` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/apple-touch-icons/apple-touch-icon.png?version=1583837405` |
| +6 | `##[href^="https://www.facebook.com"]` |  | lustery.com |  | dom | `https://lustery.com/` |
| +6 | `##[href^="https://twitter.com"]` |  | lustery.com |  | dom | `https://lustery.com/` |
| +6 | ##.twitter-timeline |  | lustery.com |  | dom | `https://lustery.com/` |
| +6 | ##.cookie-consent:not(body) |  | lustery.com |  | dom | `https://lustery.com/` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/lib/lightbox/images/close.png` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/circle-heart-loading.gif` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/lib/lightbox/images/next.png` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/lib/lightbox/images/prev.png` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/player/play.svg` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/upload/CMS/image/Homemade-Porn.jpg?version=1526312350` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/videos_header.jpg` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/icons/articles-icon.png` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/cache/images/3cc/1366x768_a_content_images_mysql_Model_Recent_Image_backup_blog62_5b4f531f9b999_jpg.jpg?version=1531925284` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/line-grey-center.png` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/line-title-right.png` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/line-title.png` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/pages/home/home_bg.jpg` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/fa-mail.png` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/fa-inst.png` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/logo.png` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/gift/icons/gift.svg?version=1544025504` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/icons/icon4.png?version=1583837405` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/icons/icon3.png?version=1583837405` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/icons/icon2.png?version=1583837405` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/icons/icon5.png?version=1583837405` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/icons/icon1.png?version=1583837405` |
| +6 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/placeholder_image.gif?version=1590650818` |
| +6 | googletagmanager.com/gtm.js | << | lustery.com |  | script | `https://www.googletagmanager.com/gtm.js?id=GTM-WV9TTR7` |
| +6 | \|\|googletagmanager.com/gtm.js$script | -- | lustery.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-WV9TTR7` |
| +6 | \|\|mxpnl.com^$3p | -- | lustery.com | 3 | script | `https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js` |
| +6 | \|\|google.com^*recaptcha/$important | -- | lustery.com | 3 | script | `https://www.google.com/recaptcha/api.js?onload=recaptchaRender&render=explicit` |
| +6 | \|\|redditstatic.com/ads/pixel.js | -- | lustery.com | 3 | script | `https://www.redditstatic.com/ads/pixel.js` |
| +6 | \|\|gstatic.com^ | -- | lustery.com | 3 | script | `https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1` |
| +6 | \|\|platform.twitter.com/widgets.js$script,important | -- | lustery.com | 3 | script | `https://platform.twitter.com/widgets.js` |
| +5 | google-analytics.com/analytics.js | << | lustery.com |  | script | `https://www.google-analytics.com/analytics.js` |
| +5 | \|\|google-analytics.com^ | -- | lustery.com | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +5 | \|\|google.com^*recaptcha/$important | -- | lustery.com | 3 | script | `https://www.google.com/recaptcha/api.js?onload=recaptchaRender&render=explicit` |
| +5 | \|\|gstatic.com^ | -- | lustery.com | 3 | script | `https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1` |
| +5 |  |  | lustery.com | 3 | script | `https://p7t9r6h4.ssl.hwcdn.net/cache/lustery.min.js?version=1602253770` |
| +5 | \|\|gstatic.com^ | -- | lustery.com | 3 | script | `https://www.gstatic.com/cv/js/sender/v1/cast_sender.js` |
| +5 |  |  | lustery.com | 3 | css | `https://p7t9r6h4.ssl.hwcdn.net/cache/lustery.min.css?version=1601362177` |
| +5 | \|\|googleapis.com^$important | -- | lustery.com | 3 | css | `https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700&subset=latin-ext` |
| +5 |  |  | lustery.com | 1 | doc | `https://lustery.com/` |
| +5 |  |  | `www.lustery.com` | 1 | doc | `http://www.lustery.com/` |
| +4 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/cache/model_thumb/image/Kim%20%26%20Leo-squashed_5f438eae2fba7.jpg?version=1598263329` |
| +4 | \|\|inspectlet.com^$3p | -- | lustery.com | 3 | script | `https://cdn.inspectlet.com/inspectlet.js` |
| +4 | \|\|js-agent.newrelic.com^ | -- | lustery.com | 3 | script | `https://js-agent.newrelic.com/nr-1184.min.js` |
| +4 | /favicon.ico$image,3p,domain=~douban.com\|~bahn.de\|~winfuture.de\|~bt.com\|~ebay.com.au\|~ebay.com\|~ebay.co.uk\|~go.com\|~github.com\|~stackexchange.com\|~stackoverflow.com\|~askubuntu.com\|~reddit.com\|~4chan.org\|~twitter.com\|~live.com\|~espn.com\|~yahoo.com | -- | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/favicon.ico?version=1522160371` |
| +4 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/apple-touch-icons/apple-touch-icon.png?version=1583837405` |
| +3 | `##[href^="https://www.facebook.com"]` |  | lustery.com |  | dom | `https://lustery.com/` |
| +3 | `##[href^="https://twitter.com"]` |  | lustery.com |  | dom | `https://lustery.com/` |
| +3 | ##.twitter-timeline |  | lustery.com |  | dom | `https://lustery.com/` |
| +3 | ##.cookie-consent:not(body) |  | lustery.com |  | dom | `https://lustery.com/` |
| +3 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/lib/lightbox/images/close.png` |
| +3 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/circle-heart-loading.gif` |
| +3 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/lib/lightbox/images/next.png` |
| +3 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/lib/lightbox/images/prev.png` |
| +2 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/player/play.svg` |
| +2 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/upload/CMS/image/Homemade-Porn.jpg?version=1526312350` |
| +2 |  |  | lustery.com | 3 | font | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/fonts/ProbaPro-Regular/ProbaPro-Regular.otf` |
| +2 |  |  | lustery.com | 3 | font | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/fonts/faithglory.otf` |
| +2 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/videos_header.jpg` |
| +2 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/icons/articles-icon.png` |
| +2 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/cache/images/3cc/1366x768_a_content_images_mysql_Model_Recent_Image_backup_blog62_5b4f531f9b999_jpg.jpg?version=1531925284` |
| +2 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/line-grey-center.png` |
| +2 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/line-title-right.png` |
| +2 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/line-title.png` |
| +2 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/pages/home/home_bg.jpg` |
| +2 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/fa-mail.png` |
| +2 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/fa-inst.png` |
| +2 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/logo.png` |
| +2 | googletagmanager.com/gtm.js | << | lustery.com |  | script | `https://www.googletagmanager.com/gtm.js?id=GTM-WV9TTR7` |
| +2 | \|\|googletagmanager.com/gtm.js$script | -- | lustery.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-WV9TTR7` |
| +2 | \|\|mxpnl.com^$3p | -- | lustery.com | 3 | script | `https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js` |
| +2 | \|\|google.com^*recaptcha/$important | -- | lustery.com | 3 | script | `https://www.google.com/recaptcha/api.js?onload=recaptchaRender&render=explicit` |
| +2 | \|\|redditstatic.com/ads/pixel.js | -- | lustery.com | 3 | script | `https://www.redditstatic.com/ads/pixel.js` |
| +2 | \|\|gstatic.com^ | -- | lustery.com | 3 | script | `https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1` |
| +2 | \|\|platform.twitter.com/widgets.js$script,important | -- | lustery.com | 3 | script | `https://platform.twitter.com/widgets.js` |
| +1 | google-analytics.com/analytics.js | << | lustery.com |  | script | `https://www.google-analytics.com/analytics.js` |
| +1 | \|\|google-analytics.com^ | -- | lustery.com | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +1 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/gift/icons/gift.svg?version=1544025504` |
| +1 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/icons/icon4.png?version=1583837405` |
| +1 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/icons/icon3.png?version=1583837405` |
| +1 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/icons/icon2.png?version=1583837405` |
| +1 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/icons/icon5.png?version=1583837405` |
| +1 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/icons/icon1.png?version=1583837405` |
| +1 |  |  | lustery.com | 3 | image | `https://p7t9r6h4.ssl.hwcdn.net/modules/Lustery/template/assets/images/placeholder_image.gif?version=1590650818` |
| +1 | \|\|google.com^*recaptcha/$important | -- | lustery.com | 3 | script | `https://www.google.com/recaptcha/api.js?onload=recaptchaRender&render=explicit` |
| +1 | \|\|gstatic.com^ | -- | lustery.com | 3 | script | `https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1` |
| +1 |  |  | lustery.com | 3 | script | `https://p7t9r6h4.ssl.hwcdn.net/cache/lustery.min.js?version=1602253770` |
| +1 | \|\|gstatic.com^ | -- | lustery.com | 3 | script | `https://www.gstatic.com/cv/js/sender/v1/cast_sender.js` |
| +1 |  |  | lustery.com | 3 | css | `https://p7t9r6h4.ssl.hwcdn.net/cache/lustery.min.css?version=1601362177` |
| +1 | \|\|googleapis.com^$important | -- | lustery.com | 3 | css | `https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700&subset=latin-ext` |
| +0 |  |  | lustery.com | 1 | doc | `https://lustery.com/` |
| +0 |  |  | lustery.com | 1 | doc | `http://lustery.com/` |
</details>
