### ISSUE TITLE
hotguysfuck.com

### ISSUE THREAD

**Issue by Rygle** [Clefspeare13/pornhosts#336]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
hotguysfuck.com
www.hotguysfuck.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![Screenshot_Firefox_Beta_20201010-233617](https://user-images.githubusercontent.com/38778536/95655332-3509f180-0b52-11eb-8c34-be6d0c073427.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
excluding www.

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +338 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxOTk3NDIyMjgwLCJ0IjoxNjAyMzQwNTMxfQ%3D%3D--586bc0939d3e4b4939a9255f39a12709832c981626552b73625e8a91feaa8473&shared=true |
| +303 | `##[href^="https://twitter.com"]` |  | hotguysfuck.com |  | dom | `https://hotguysfuck.com/` |
| +303 | ##.twitterWrapper |  | hotguysfuck.com |  | dom | `https://hotguysfuck.com/` |
| +303 |  |  | hotguysfuck.com | 1 | image | `https://hotguysfuck.com/favicon.ico` |
| +303 | /home/twitter. | -- | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/twitter.png` |
| +303 |  |  | hotguysfuck.com | 1 | frame | `https://hotguysfuck.com/sbbi/?sbbpg=sbbShell&gprid=qq` |
| +303 | \|\|alexametrics.com^$3p | -- | hotguysfuck.com | 3 | script | `https://certify-js.alexametrics.com/atrk.js` |
| +303 | googletagmanager.com/gtm.js | << | hotguysfuck.com |  | script | `https://www.googletagmanager.com/gtm.js?id=GTM-N4G3S5J` |
| +303 | \|\|googletagmanager.com/gtm.js$script | -- | hotguysfuck.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-N4G3S5J` |
| +303 |  |  | hotguysfuck.com | 1 | script | `https://cdn.hotguysfuck.com/assets/vendors/jquery-3.4.1.min.js` |
| +303 |  |  | hotguysfuck.com | 1 | script | `https://www.hotguysfuck.com/assets/js/main.js` |
| +303 | /home/twitter. | -- | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/twitter.png` |
| +303 | \|\|googleapis.com^$important | -- | hotguysfuck.com | 3 | css | `https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap` |
| +303 | \|\|googleapis.com^$important | -- | hotguysfuck.com | 3 | css | `https://fonts.googleapis.com/css?family=Barlow:400,600,800,900` |
| +302 |  |  | hotguysfuck.com | 1 | doc | `https://hotguysfuck.com/` |
| +302 |  |  | `www.hotguysfuck.com` | 1 | doc | `http://www.hotguysfuck.com/` |
| +300 |  |  | hotguysfuck.com | 1 | frame | `https://hotguysfuck.com/sbbi/?sbbpg=sbbShell&gprid=yr` |
| +300 |  |  | hotguysfuck.com | 1 | frame | `https://hotguysfuck.com/sbbi/?sbbpg=sbbShell&gprid=yr&sbbgs=h4fc07640976e7455a4be5933f6e63919240&ddl=4` |
| +299 | ##.twitterWrapper |  | hotguysfuck.com |  | dom | `https://hotguysfuck.com/` |
| +298 | `##[href^="https://twitter.com"]` |  | hotguysfuck.com |  | dom | `https://hotguysfuck.com/` |
| +298 |  |  | hotguysfuck.com | 1 | image | `https://hotguysfuck.com/favicon.ico` |
| +296 |  |  | hotguysfuck.com | 1 | font | `https://cdn.hotguysfuck.com/assets/vendors/fontawesome/webfonts/fa-brands-400.woff2` |
| +296 |  |  | hotguysfuck.com | 1 | font | `https://cdn.hotguysfuck.com/assets/vendors/fontawesome/webfonts/fa-solid-900.woff2` |
| +296 |  |  | hotguysfuck.com | 1 | font | `https://cdn.hotguysfuck.com/assets/vendors/fontawesome/webfonts/fa-regular-400.woff2` |
| +296 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/watch_now_pic.jpg` |
| +296 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/apply_now_pic.jpg` |
| +296 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/join_banner_bck_1.jpg` |
| +296 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/join_banner_bck_2.png` |
| +296 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/twitter_bck_2.png` |
| +296 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/twitter_bck.png` |
| +296 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/image_slider_bck.jpg` |
| +296 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/banner_bck.png` |
| +296 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/newVideos_pic.jpg` |
| +296 | /home/twitter. | -- | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/twitter.png` |
| +296 |  |  | hotguysfuck.com | 1 | frame | `https://hotguysfuck.com/sbbi/?sbbpg=sbbShell&gprid=yr&sbbgs=h4fc07640976e7455a4be5933f6e63919240&ddl=4` |
| +296 |  |  | hotguysfuck.com | 1 | image | `https://hotguysfuck.com/sbbi/?sbbpg=utMedia&vii=ehf44f6cd017f6a4b089f7c6aef7d4c5c55a24eb8ec5f9b3d36f864ee61339c1u9p2v4u0` |
| +296 | \|\|alexametrics.com^$3p | -- | hotguysfuck.com | 3 | script | `https://certify-js.alexametrics.com/atrk.js` |
| +295 | googletagmanager.com/gtm.js | << | hotguysfuck.com |  | script | `https://www.googletagmanager.com/gtm.js?id=GTM-N4G3S5J` |
| +295 | \|\|googletagmanager.com/gtm.js$script | -- | hotguysfuck.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-N4G3S5J` |
| +295 |  |  | hotguysfuck.com | 1 | script | `https://cdn.hotguysfuck.com/assets/vendors/jquery-3.4.1.min.js` |
| +295 |  |  | hotguysfuck.com | 1 | script | `https://www.hotguysfuck.com/assets/js/main.js` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/user_1.png` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/user_3.png` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/user_2.png` |
| +295 | /home/twitter. | -- | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/twitter.png` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/stream/2020-08-28-2020-09-07-jason-moore-clara-fargo/small_thumbs/1598637900COVER.00_22_44_30.Still020.jpg` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/stream/2020-08-30-2020-09-11-tommy-angelino-clara-fargo/small_thumbs/15988097882020-09-11-tommy-angelino-clara-fargo-023.jpg` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/stream/2020-09-01-2020-09-14-jayden-marcos-skylar-angel/small_thumbs/15999633412020-09-14-jayden-marcos-skylar-angel-003.jpg` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/stream/2020-09-01-2020-09-18-matt-mason-ivy-steele-final/small_thumbs/15990194882020-02-22-matt-mason-ivy-steele-2-COVER-3.jpg` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/stream/2020-08-30-2020-09-21-marc-wallace-jessica-nunez/small_thumbs/15988484932020-09-21-marc-wallace-jessica-nunez-003.jpg` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/stream/2020-09-16-2020-09-25-ricky-owen-destiny-mira/small_thumbs/16003694732020-09-28-ricky-owen-destiny-mira-020.jpg` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/home/orange_line.png` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/stream/2020-09-21-2020-10-02-gabriel-jaxx-kim-smiles-final/small_thumbs/16006616512020-02-07-gabriel-jaxx-kim-smiles-COVER-3.jpg` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/stream/2020-09-22-2020-10-05-kellan-hartmann-desiree-nevada/small_thumbs/16008057522020-10-05-kellan-hartmann-desiree-nevada-016.jpg` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/stream/2020-09-22-2020-10-09-raphael-leon-aliyah-jackson/small_thumbs/16008060652020-10-09-raphael-leon-aliyah-jackson-020.jpg` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://hotguysfuck.com/images/banners/1601675490dfdsfdsf.jpg` |
| +295 |  |  | hotguysfuck.com | 1 | css | `https://cdn.hotguysfuck.com/assets/css/pages/home.css` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/create/arrow_down.png` |
| +295 |  |  | hotguysfuck.com | 1 | image | `https://cdn.hotguysfuck.com/assets/images/header/logo.png` |
| +295 |  |  | hotguysfuck.com | 1 | css | `https://www.hotguysfuck.com/assets/css/general/main.css` |
| +295 |  |  | hotguysfuck.com | 1 | css | `https://cdn.hotguysfuck.com/assets/vendors/fontawesome/css/all.min.css` |
| +295 | \|\|googleapis.com^$important | -- | hotguysfuck.com | 3 | css | `https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap` |
| +295 | \|\|googleapis.com^$important | -- | hotguysfuck.com | 3 | css | `https://fonts.googleapis.com/css?family=Barlow:400,600,800,900` |
| +293 |  |  | hotguysfuck.com | 1 | doc | `https://hotguysfuck.com/` |
| +292 |  |  | hotguysfuck.com | 1 | doc | `http://hotguysfuck.com/` |
| +278 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxOTk3NDIyMjgwLCJ0IjoxNjAyMzQwNTMxfQ%3D%3D--586bc0939d3e4b4939a9255f39a12709832c981626552b73625e8a91feaa8473&shared=true |
| +269 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +269 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +266 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +266 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +218 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxNDE5MzM4NzIxLCJ0IjoxNjAyMzQwNDgwfQ%3D%3D--fcca8e7ac3cc647c8ba860e1d6de84d8b5af8565c727b90f4a53e6bec5f9c24d&shared=true |
| +218 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +218 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +178 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +145 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +128 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +119 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +116 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMDA2NDY4NzE1LCJ0IjoxNjAyMzQwMjgzfQ%3D%3D--b370d3db2b7107d633d41c1996682e6065dd1e0a2392bcfb0ecfd8e7bfeaaa11&shared=true |
| +115 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +113 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +112 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +82 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMDA2NDY4NzE1LCJ0IjoxNjAyMzQwMjgzfQ%3D%3D--b370d3db2b7107d633d41c1996682e6065dd1e0a2392bcfb0ecfd8e7bfeaaa11&shared=true |
| +58 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMDA2NDY4NzE1LCJ0IjoxNjAyMzQwMjgzfQ%3D%3D--b370d3db2b7107d633d41c1996682e6065dd1e0a2392bcfb0ecfd8e7bfeaaa11&shared=true |
| +43 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMDA2NDY4NzE1LCJ0IjoxNjAyMzQwMjgzfQ%3D%3D--b370d3db2b7107d633d41c1996682e6065dd1e0a2392bcfb0ecfd8e7bfeaaa11&shared=true |
| +33 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMDA2NDY4NzE1LCJ0IjoxNjAyMzQwMjgzfQ%3D%3D--b370d3db2b7107d633d41c1996682e6065dd1e0a2392bcfb0ecfd8e7bfeaaa11&shared=true |
| +26 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMDA2NDY4NzE1LCJ0IjoxNjAyMzQwMjgzfQ%3D%3D--b370d3db2b7107d633d41c1996682e6065dd1e0a2392bcfb0ecfd8e7bfeaaa11&shared=true |
| +21 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMDA2NDY4NzE1LCJ0IjoxNjAyMzQwMjgzfQ%3D%3D--b370d3db2b7107d633d41c1996682e6065dd1e0a2392bcfb0ecfd8e7bfeaaa11&shared=true |
| +21 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +21 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +13 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyODE0NzQ0ODY0LCJ0IjoxNjAyMzQwMjY4fQ%3D%3D--831a774a6dfdbe33df8c8f54af3ab17e43718a3dbe1dcd46fabae7d979a1211e&shared=true |
| +9 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyODE0NzQ0ODY0LCJ0IjoxNjAyMzQwMjY4fQ%3D%3D--831a774a6dfdbe33df8c8f54af3ab17e43718a3dbe1dcd46fabae7d979a1211e&shared=true |
| +7 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyODE0NzQ0ODY0LCJ0IjoxNjAyMzQwMjY4fQ%3D%3D--831a774a6dfdbe33df8c8f54af3ab17e43718a3dbe1dcd46fabae7d979a1211e&shared=true |
| +6 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyODE0NzQ0ODY0LCJ0IjoxNjAyMzQwMjY4fQ%3D%3D--831a774a6dfdbe33df8c8f54af3ab17e43718a3dbe1dcd46fabae7d979a1211e&shared=true |
| +6 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +5 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +4 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MDY2NTMzMDMwLCJ0IjoxNjAyMzQwMjYzfQ%3D%3D--f909822652b9c1d65dc31252d4cf02c73ffd80ade0a5f550328460d7883f694f&shared=true |
| +1 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MDY2NTMzMDMwLCJ0IjoxNjAyMzQwMjYzfQ%3D%3D--f909822652b9c1d65dc31252d4cf02c73ffd80ade0a5f550328460d7883f694f&shared=true |
| +0 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjo0MDY2NTMzMDMwLCJ0IjoxNjAyMzQwMjYzfQ%3D%3D--f909822652b9c1d65dc31252d4cf02c73ffd80ade0a5f550328460d7883f694f&shared=true |
| +0 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +0 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
</details>
