### ISSUE TITLE
opjav.com

### ISSUE THREAD

**Issue by dzdark** [Clefspeare13/pornhosts#345]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

I had to pixelate the screenshot, I don't want anyone to see nudity. I hope it's alright.

## Domains
Only add the needed one See also #12

```python

opjav.com
```

## Content sources

(Please see #35)

```python


```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/68017916/103859443-9eb38080-50ec-11eb-9496-3a8664bdb763.png)

</details>

## External Info
- 
- 
- 

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
Super, I'll get these on later, testing the [PyFunceble v4](https://github.com/funilrys/PyFunceble/tree/dev) right now, if everything goes right, I'll update the build and test script.

Thanks for your contribution
