### ISSUE TITLE
Base-domain only list

### ISSUE THREAD

**Issue by april-2** [Clefspeare13/pornhosts#353]
**Is your feature request related to a problem? Please describe.**

I'd like to have a base domain list, not hosts file.

**Describe the solution you'd like**

/download_here/ section have "base_domains.txt" file.
It contains base domain names, like p0rn.com, p0rn.net .

**Describe alternatives you've considered**

For now I can just wget /download_here/0.0.0.0/hosts , strip 0.0.0.0 and convert subdomains(www.xyz.com) to base domain (xyz.com)

**Additional context**

**Comment by spirillen** [comment]
May I ask what your usecase is?

**Comment by spirillen** [comment]
consider inactive, closing.

Feel free to reopen
