### ISSUE TITLE
Use Search API to find uncatched latest domains

### ISSUE THREAD

**Issue by april-2** [Clefspeare13/pornhosts#354]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

How about monitoring below JSON API to find latest porn websites?
This could be done by cronjob.

- https://yacy.searchlab.eu/yacysearch.json?query=porn
- https://yacy.searchlab.eu/yacysearch.json?query=classic+porn
- https://yacy.searchlab.eu/yacysearch.json?query=classy+porn
- (some other any evil keyword)

here's a sample (some of them are not listed on your pornlist)

```
classy.porn
freeclassyporn.com
mixxporn.com
porn555.com
pornkai.com
pornroh.com
ru.redtube.com
ru.spankbang.com
tubepornclassic.com
www.alohatube.com
www.fuq.com
www.porn.com
www.porn7.xxx
www.porzo.com
www.pussyspace.com
www.tnaflix.com
www.tube8.com
www.youporn.com
```

**Describe alternatives you've considered**

Above

**Additional context**

**Comment by spirillen** [comment]
Closing as the site only returns `502 bad gateway`
