### ISSUE TITLE
fapinstructor.com

### ISSUE THREAD

**Issue by inboxonly10** [Clefspeare13/pornhosts#355]
I believe this domain is an Adult(-related) domain

## Domains
Only add the needed one See also #12

```python
fapinstructor.com
www.fapinstructor.com
```

## Content sources

(Please see #35)

Content comes mostly form reddit and also other image hosts that are used on reddit.

```python
api.fapinstructor.com

```

## External sources (reference)

```python


```

## Screenshots

<details><Summary>Screenshot required</summary>

<img width="1372" alt="Schermafbeelding 2021-05-19 om 09 19 27" src="https://user-images.githubusercontent.com/84437912/118771903-60d91c80-b883-11eb-8483-6feffb60dc44.png">

<img width="1112" alt="Schermafbeelding 2021-05-19 om 09 37 20" src="https://user-images.githubusercontent.com/84437912/118774298-f83f6f00-b885-11eb-8148-8c30c25ce368.png">

</details>

## External Info
- It takes NSFW media from reddit and puts it into a slideshow

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
Will be added to the lists in the https://github.com/Clefspeare13/pornhosts/tree/master/download_here when I hopefully gets my internet connection next week :pray: :crossed_fingers:
