### ISSUE TITLE
hobby.porn

### ISSUE THREAD

**Issue by inboxonly10** [Clefspeare13/pornhosts#358]
I believe this domain is an Adult domain.

## Domains
Only add the needed one See also #12.

www.hobby.porn resolves to hobby.porn; thus www. subdomain not needed.

```python
hobby.porn

```

## Content sources

(Please see #35)

Only vid1**.hobby.porn in here resolve right now, but in the future is possible that their number grows as more content is added.

```python
ags.hobby.porn
vid101.hobby.porn
vid102.hobby.porn
vid103.hobby.porn
vid104.hobby.porn
vid105.hobby.porn
vid106.hobby.porn
vid107.hobby.porn
vid108.hobby.porn
vid109.hobby.porn
vid110.hobby.porn

```

## External sources (reference)

To these only go XHRs, it doesn't seem meaningful/needed to block them. These may be used for tracking but not sure about it.

```python

directpaper.name
p242.directpaper.name
prfctmney.com
sotetahe.pro
twinrdsrv.com
yomeno.xyz
vast.yomeno.xyz


```

## Screenshots

<details><Summary>Screenshot required</summary>

<img width="1112" alt="Schermafbeelding 2021-06-02 om 14 14 34" src="https://user-images.githubusercontent.com/84437912/120478968-b34f2880-c3ad-11eb-950d-05d21f2fa68b.png">

uMatrix for the external sources:
<img width="1112" alt="Schermafbeelding 2021-06-02 om 14 15 01" src="https://user-images.githubusercontent.com/84437912/120484788-b3eabd80-c3b3-11eb-9442-bee7aec79c10.png">

</details>

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
A perfect submission :100:

**Comment by spirillen** [comment]
- prfctmney.com https://www.mypdns.org/T4575
  - twinrdsrv.com => https://www.mypdns.org/T2658
  - yomeno.xyz => https://www.mypdns.org/T4268

**Comment by spirillen** [comment]
directpaper.name => https://github.com/uBlockOrigin/uAssets/commit/2b0af30521715f6fd18bddbb40597380bd6ca507#r51638018
