### ISSUE TITLE
av4.xyz

### ISSUE THREAD

**Issue by mateusfg7** [Clefspeare13/pornhosts#359]
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
av4.xyz
www.av4.xyz
```

## Content sources

(Please see #35)

```python
av.av4.xyz
1080p.av4.xyz
jp.av4.xyz
en.av4.xyz
cn.av4.xyz
de.av4.xyz
kr.av4.xyz
ru.av4.xyz
th.av4.xyz
es.av4.xyz
ab.av4.xyz
```

## External sources (reference)

```python
anime-tube.pw
www.anime-tube.pw
```

## Screenshots

<details><Summary>Screenshot required</summary>

![image](https://user-images.githubusercontent.com/40613276/122066964-8fd2a780-cdc9-11eb-90ee-f7b0383dc187.png)
![image](https://user-images.githubusercontent.com/40613276/122067010-982ae280-cdc9-11eb-8b33-178c9d157e9b.png)
![image](https://user-images.githubusercontent.com/40613276/122067046-9f51f080-cdc9-11eb-8076-c3c14ac2597e.png)

</details>

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

**Comment by spirillen** [comment]
Closing this as I've added the real domain behind this domain roulette in <https://mypdns.org/my-privacy-dns/porn-records/-/issues/13>

If you can access this domain after deployment of a new list, please don't hesitate to reopen issue
