### ISSUE TITLE
A couple more sites to be added

### ISSUE THREAD

**Issue by ghost** [Clefspeare13/pornhosts#36]
Well... I have a serious addiction to porn, and I can thank my kink for that (hypno). It messes with your head, in order to make you addicted. Disabling firewalls and stuff is to easy for me, and they never work. The hosts file requires me to move it to the desktop, edit and replace it in order to turn it on and off. More than enough effort to stop me, hopefully... I was going to have a short list, but came across many that I can't see in the lsit here, or the lists linked to https://github.com/StevenBlack/hosts/blob/master/alternates/porn/readme.md

Paid for firewalls and blockers that schools, universities and workplaces use are nowhere near good enough, I hope this list helps do at least a little ^.^ If you want me to add more, then just reply if I should continue doing it this way, or do it another way. I want to help people block these kinds of things...

The list is ~490 links long, so i won't post them HERE, but they'll rather be on a pastebin:
https://pastebin.com/TAgf9VJP
NOTE: Lines 121 - 138 are ones that might cause issues, hence I've made them really obvious here and there.

Thanks for your great work ^.^

**Comment by Clefspeare13** [comment]
I've added a large portion, been gone a while, going to work my way through the rest as quickly as I can
