### ISSUE TITLE
More hosts

### ISSUE THREAD

**Issue by XanC** [Clefspeare13/pornhosts#37]
I wrote a scraper for thehun.net and came up with the following.  Let me know if there's a better format.

18magazine.com
21naturalsfan.com
21naturals.top
2-xx.com
4adultin.com
affiliates.bizarre-mature-sex.com
affiliates.teens-love-oldmen.com
afrikakampos.com
alexlegend.com
allover30.com
allsologirls.com
alluringvixens.com
alurajensonxxx.com
aman.ml
amybrookexxx.com
analpornfan.com
angelinacastrolive.com
anilos.com
ariellaferrera.com
asiangirlfriendclub.com
asianthumbs.org
aussieass.com
aussiepov.com
aussiespeedoguy.org
avadevine.com
avidolsex.com
babedrop.net
baberotica.com
babes-club.com
babesfarm.com
babesfarm.ml
babesfirst.com
babesource.com
backroomfuckers.com
balletflatsfetish.com
beautyshemales.com
best-gay-lesbian-dating-websites.com
bestseximages.com
bestshemalesex.com
bigcock.homegrownvideo.com
bigtits.homegrownvideo.com
bikini-heat.com
bikini-pleasure.com
bisexualdave.com
blackgirlslust.com
blog.pinkworld.com
blondemilfslut.com
bondageblog.org
boysfucks.com
boys.kink6.net
breakingporn.com
britbuk.com
britishupskirtpantypervert.com
buck-angel.com
bukkakefest.com
bunchafreepics.com
bushyorhairy.com
bustyblisss.com
bustysirens.com
camwithher.com
carmenvalentina.com
cassie.karensbitches.com
castingcouchxfan.com
castmyass.com
cdgirls.com
celeb6free.com
celebarhive.com
charleechaselive.com
cheating-sluts.com
clubcharismaxxx.com
clubglamour.net
clubtug.com
collegesexpartyvideos.com
content.alurajensonxxx.com
content.amybrookexxx.com
content.ariellaferrera.com
content.avadevine.com
content.clubcharismaxxx.com
cosplayfeet.com
couplefantasies.com
cristiannlive.com
cuckoldmenow.com
cuckoldvideoclips.com
cumblastcity.com
cumonwives.com
cutegirlporn.com
deauxmalive.com
dirtyflix.ml
dream5.cf
earlmiller.com
ebonybbwatlanta.com
emily18.com
emily.karensbitches.com
enjoyvids.com
enter.privatecastings.com
erocurves.com
erome.com
eroticbeauties.net
erotic-blog.com
erotictonaughty.com
europornstar.com
exotic4kfan.com
extremeprivate.com
fantasticpornstars.com
faponix.com
fastpics.eu
fellatiojapan.com
femalehardbody.com
fetish.sexpreviews.eu
fhg.ferame.com
fhg.hairyav.com
fhg.jodiegasson.com
fhg.schoolgirlshd.com
fhg.sexjapantv.com
fhg.voyeurjapantv.com
filipinachick.com
filipinagogo.com
filipinastripper.com
finernudes.com
finishhim.com
firstanalquest.com
fistertwister.com
footfetishbeauties.com
footfetishcuties.com
fooxybabes.com
foxxedup.com
fragileslaves.com
free.breakingporn.com
free-famous-toons.com
free-girls.net
free.mypreggo.com
freepornaz.com
freepornretro.com
freesexgame.net
freeskinpics.com
ftvgirls.com
ftvgirlsfan.com
fuckedbabes.com
funwithamber.everestcash.com
gabbyquinteros.com
galleries2.ftvcash.com
galleries.allover30.com
galleries.alluringvixens.com
galleries.anilos.com
galleries.bukkakefest.com
galleries.cassie.karensbitches.com
galleries.cdgirls.com
galleries.couplefantasies.com
galleries.emily18.com
galleries.emily.karensbitches.com
galleries.femalehardbody.com
galleriesfnm.stiffia.com
galleries.gangbangdee.com
galleries.gndavery.com
galleries.gndcali.com
galleries.gndgfvids.com
galleries.gndmodels.com
galleries.gndnicole.com
galleries.gndruby.com
galleries.gndsadie.com
galleries.hairy-arms.com
galleries.hitzefrei.com
gallerieshtg.stiffia.com
gallerieshzv.stiffia.com
galleriesifg.stiffia.com
galleries.jen18.com
galleries.jennyreid.com
galleries.jessica.totalsupercuties.com
galleries.jordan.totalsupercuties.com
galleries.katiereynolds.com
galleriesmmf.stiffia.com
galleriesmmv.stiffia.com
galleries.modelmuscles.com
galleries.myallaccesspass.com
galleries.my-sex-life.com
galleries.nerdpervert.com
galleries.nicole.totalsupercuties.com
galleries.payserve.com
galleries.privatecastings.com
galleries.privateclassics.com
galleries.private.com
galleries.realtampaswingers.com
galleries.sonia.totalsupercuties.com
galleries.stephanie.totalsupercuties.com
galleries.tease-pics.com
galleries.teengirlphotos.com
galleries.thisyearsmodel.com
galleries.transsexualbarebacking.com
galleries.wackmymeat.com
galleries.xxxmemberchannels.com
gallery.jpsex-xxx.com
galleryserver.org
gangbangdee.com
gaymoviespage.com
gaypornwire.com
getfuckass.com
girlsdoxxx.com
girlsoutwest.com
gndavery.com
gndcali.com
gndgfvids.com
gndmodels.com
gndnicole.com
gndruby.com
gndsadie.com
got2pee.com
greatgirls.info
hairy-arms.com
hairybush.homegrownvideo.com
hairy.photos
hairy-pussy.pictures
handjobjapan.com
happytugs.info
hardhoneys.com
helloladyboy.com
hitzefrei.com
homegrownvideo.com
hometownnudes.com
hosted.amourangels.com
hosted.femjoy.com
hosted.jolieandfriends.com
hosted.joymii.com
hosted.simonscans.com
hot18tube.com
hotgirlies4u.com
hotgirlsboard.com
hungshemales.net
i2px.com
icebergsex.com
ideal-babe.com
indiangfvideos.us
interracialgfvideos.gfslist.com
inthecrack.in
itscleolive.com
iwantmature.com
japanesegirls.tv
jelenajensen.com
jen18.com
jennyreid.com
jessica.totalsupercuties.com
jizzedonface.com
jodiegasson.com
join2.homegrownvideo.com
join.afrikakampos.com
join.baberotica.com
join.backroomfuckers.com
join.buck-angel.com
join.bukkakefest.com
join.clubtug.com
join.finishhim.com
join.hairy-arms.com
join.helloladyboy.com
join.hungshemales.net
join.jodiegasson.com
join.jolieandfriends.com
join.katiereynolds.com
join.landofvenus.com
join.lucy-v.com
join.modelmuscles.com
join.myallaccesspass.com
join.my-sex-life.com
join.nerdpervert.com
join.realtampaswingers.com
join.seemomsuck.com
join.sexjapantv.com
join.sweetcumgirl.com
join.teengirlphotos.com
join.transsexualbarebacking.com
join.tsvivian.com
join.voyeurjapantv.com
join.wackmymeat.com
jolieandfriends.com
jordan.totalsupercuties.com
joymii.com
joymiifan.com
juicygf.com
juliaannlive.com
justporn.link
kabukicho-girls.com
karupsgalleries.com
katiereynolds.com
kimberleelive.com
kinkygate.com
koregoddess.net
ladyboyroad.com
ladyboyweb.com
landofvenus.com
lateenie.com
latinafacesitting.com
lbfmaddiction.com
legalteenlust.net
legsjapan.com
lemmecheck.com
lemmecheck.xxx
lesarchive.com
lesbianfacesitters.com
lexidona.com
lineporn.com
lubedfan.com
lucy-v.com
lucyzara.com
lustymaturemoms.com
maggiegreenlive.com
magic-erotica.com
mainbabes.com
massagesexgirls.com
masturbears.net
masturmonkey.com
matureanilos.cf
maturesally.com
maxinex.com
milfslikecock.com
modeldb.net
modelmuscles.com
movies.sicflics.com
myallaccesspass.com
myamateurwebsite.com
mypantyhoseblog.com
mypreggo.com
myrealcams.com
my-sex-life.com
myveryfirsttimefan.com
nakedwench.com
nannyspys.com
nastypornonline.com
nataliastarr.com
naturalhairywomen.net
nerdpervert.com
nicole.totalsupercuties.com
nikkibenz.com
ninakayy.com
nitrovideo.com
nnteens.com
nothingbutpanties.com
nsfwtgp.com
nubilefilms.org
nudeandhairy.com
nude-in-public.cc
nudephotolinks.com
nudepmates.com
nudesfortroops.com
nudexxx.pics
nylonfeetlove.com
nylonup.com
ohmob.com
oilyhandjobs.com
omacash.com
onlythumb.net
osexxx.com
partydorm.net
passionhdfan.com
payserve.com
peeonher.com
pennypaxlive.com
petrafeet.com
picsporner.com
pics.tube4.me
pinkvelvetvault.com
pinupfiles.gq
pissblog.com
porn40.com
pornforwomen.org.uk
pornnerdnetwork.com
pornositesearch.com
pornoxxbox.com
porn-service.us
pornsexerotica.com
pornstar-photos.com
pornstarsnaked.com
porntubered.com
povcuckold.com
povdfan.com
prettypetites.com
preview.ftvgirls.com
previews.danielleftv.com
previews.ftvmilfs.com
privatecastings.com
privateclassics.com
private.com
promo.homegrownvideo.com
promo.spunkyangels.com
puffynetwork.com
pumaswede.com
purematurefan.com
purenudegirls.com
puretaboo.top
pussyxxxporn.com
qualitypage.com
realfloridaamateurs.com
realsubmitted.com
realtampaswingers.com
register.join-hitzefrei.com
richporn.com
romanvideo.com
romemajor.com
royaldressedladies.com
rubberdoll.net
rummp.com
sarajay.com
secure.alurajensonxxx.com
secure.amybrookexxx.com
secure.ariellaferrera.com
secure.avadevine.com
secure.clubcharismaxxx.com
seemomsuck.com
sex-files.net
sexjapantv.com
sexjohn.com
sexyandweknow.it
sexydirtygirl.net
sexyoutdoor.fun
sexytokyo.org
shandafay.com
sharkys.at
shedevils.com
shemaleblue.com
shemalesguide.com
silkengirl.net
simplenu.com
simplyanal.com
siripornstar.com
skrog.net
sluts-asia.com
snbabes.com
snrcash.com
sonia.totalsupercuties.com
sophiedeelive.com
spankthisgay.com
speedofetish.com
spermmania.com
spicybabe.net
spunkyangels.com
stars-celebrity.com
starsinporn.com
stephanie.totalsupercuties.com
stockingsvr.com
stockingvideos.com
streaming.mature-money.com
streaptease.net
sunnylanelive.com
sweetcumgirl.com
sweet-sin.com
tacamateurs.com
teamskeetfans.com
tease-pics.com
teenamites.com
teengirlphotos.com
teenporn.today
teenscoreclub.com
teenslikecocks.com
tgp.eroticstories.com
the-bikini.com
thebikinihut.com
thehairylady.com
thehun.net
thematurelady.com
thesandfly.com
thisyearsmodel.com
thumbuster.com
timdir.com
tiny4kfan.com
tokyofacefuck.com
tokyopussycinema.com
tools.zbuckz.com
touchmylips.com
tour.bikini-pleasure.com
tour.girlsoutwest.com
transexjapan.com
transfeet.com
transsexualbarebacking.com
tribute-to.com
trueamateurmodels.com
truthordarepics.com
tsvivian.com
uhmature.com
uralesbian.com
vickyathome.com
vidsguide.com
vipissy.com
virtualpornfan.com
voyeurjapantv.com
wackmymeat.com
weareshemale.com
webmasters.wetandpuffy.com
weknowporn.com
weliketosuck.com
wetandpissy.com
wetchicks.info
whoore.com
wifebucket.com
wifecrazy.com
wildbdsmart.com
wildhotbabes.com
www.18magazine.com
www.21naturalsfan.com
www.21naturals.top
www2.3wisp.com
www.2-xx.com
www.4adultin.com
www.affiliates.bizarre-mature-sex.com
www.affiliates.teens-love-oldmen.com
www.afrikakampos.com
www.alexlegend.com
www.allsologirls.com
www.aman.ml
www.analpornfan.com
www.angelinacastrolive.com
www.asiangirlfriendclub.com
www.asianthumbs.org
www.aussieass.com
www.aussiepov.com
www.aussiespeedoguy.org
www.avidolsex.com
www.babedrop.net
www.babes-club.com
www.babesfarm.com
www.babesfarm.ml
www.babesfirst.com
www.babesource.com
www.balletflatsfetish.com
www.beautyshemales.com
www.best-gay-lesbian-dating-websites.com
www.bestseximages.com
www.bestshemalesex.com
www.bigcock.homegrownvideo.com
www.bigtits.homegrownvideo.com
www.bikini-heat.com
www.bisexualdave.com
www.blackgirlslust.com
www.blog.pinkworld.com
www.blondemilfslut.com
www.bondageblog.org
www.boysfucks.com
www.boys.kink6.net
www.britbuk.com
www.britishupskirtpantypervert.com
www.bunchafreepics.com
www.bushyorhairy.com
www.bustyblisss.com
www.bustysirens.com
www.camwithher.com
www.carmenvalentina.com
www.castingcouchxfan.com
www.castmyass.com
www.celeb6free.com
www.celebarhive.com
www.charleechaselive.com
www.cheating-sluts.com
www.clubglamour.net
www.clubtug.com
www.collegesexpartyvideos.com
www.content.alurajensonxxx.com
www.content.amybrookexxx.com
www.content.ariellaferrera.com
www.content.avadevine.com
www.content.clubcharismaxxx.com
www.cosplayfeet.com
www.cristiannlive.com
www.cuckoldmenow.com
www.cuckoldvideoclips.com
www.cumblastcity.com
www.cumonwives.com
www.cutegirlporn.com
www.deauxmalive.com
www.dirtyflix.ml
www.dream5.cf
www.earlmiller.com
www.ebonybbwatlanta.com
www.enjoyvids.com
www.erocurves.com
www.erome.com
www.erotic-blog.com
www.erotictonaughty.com
www.exotic4kfan.com
www.extremeprivate.com
www.fantasticpornstars.com
www.faponix.com
www.fastpics.eu
www.fellatiojapan.com
www.fetish.sexpreviews.eu
www.fhg.ferame.com
www.fhg.hairyav.com
www.fhg.jodiegasson.com
www.fhg.schoolgirlshd.com
www.fhg.sexjapantv.com
www.fhg.voyeurjapantv.com
www.filipinachick.com
www.filipinagogo.com
www.filipinastripper.com
www.finernudes.com
www.finishhim.com
www.firstanalquest.com
www.fistertwister.com
www.footfetishbeauties.com
www.footfetishcuties.com
www.fooxybabes.com
www.foxxedup.com
www.fragileslaves.com
www.free-girls.net
www.freepornaz.com
www.freepornretro.com
www.freesexgame.net
www.freeskinpics.com
www.ftvgirlsfan.com
www.fuckedbabes.com
www.funwithamber.everestcash.com
www.gabbyquinteros.com
www.galleriesfnm.stiffia.com
www.gallerieshtg.stiffia.com
www.gallerieshzv.stiffia.com
www.galleriesifg.stiffia.com
www.galleriesmmf.stiffia.com
www.galleriesmmv.stiffia.com
www.gallery.jpsex-xxx.com
www.galleryserver.org
www.gaymoviespage.com
www.gaypornwire.com
www.getfuckass.com
www.girlsdoxxx.com
www.got2pee.com
www.greatgirls.info
www.hairybush.homegrownvideo.com
www.hairy.photos
www.hairy-pussy.pictures
www.handjobjapan.com
www.happytugs.info
www.hardhoneys.com
www.helloladyboy.com
www.hometownnudes.com
www.hosted.amourangels.com
www.hosted.femjoy.com
www.hosted.jolieandfriends.com
www.hosted.joymii.com
www.hosted.simonscans.com
www.hot18tube.com
www.hotgirlies4u.com
www.hotgirlsboard.com
www.hungshemales.net
www.i2px.com
www.icebergsex.com
www.ideal-babe.com
www.indiangfvideos.us
www.interracialgfvideos.gfslist.com
www.inthecrack.in
www.itscleolive.com
www.iwantmature.com
www.japanesegirls.tv
www.jelenajensen.com
www.jizzedonface.com
www.join2.homegrownvideo.com
www.joymii.com
www.joymiifan.com
www.juicygf.com
www.juliaannlive.com
www.justporn.link
www.kabukicho-girls.com
www.karupsgalleries.com
www.kimberleelive.com
www.kinkygate.com
www.koregoddess.net
www.ladyboyroad.com
www.ladyboyweb.com
www.landofvenus.com
www.lateenie.com
www.latinafacesitting.com
www.lbfmaddiction.com
www.legalteenlust.net
www.legsjapan.com
www.lemmecheck.com
www.lemmecheck.xxx
www.lesarchive.com
www.lesbianfacesitters.com
www.lexidona.com
www.lineporn.com
www.lubedfan.com
www.lucyzara.com
www.lustymaturemoms.com
www.maggiegreenlive.com
www.magic-erotica.com
www.mainbabes.com
www.massagesexgirls.com
www.masturbears.net
www.masturmonkey.com
www.matureanilos.cf
www.maturesally.com
www.maxinex.com
www.milfslikecock.com
www.modeldb.net
www.movies.sicflics.com
www.myamateurwebsite.com
www.mypantyhoseblog.com
www.myrealcams.com
www.myveryfirsttimefan.com
www.nakedwench.com
www.nannyspys.com
www.nastypornonline.com
www.nataliastarr.com
www.naturalhairywomen.net
www.nikkibenz.com
www.ninakayy.com
www.nitrovideo.com
www.nnteens.com
www.nothingbutpanties.com
www.nsfwtgp.com
www.nubilefilms.org
www.nudeandhairy.com
www.nude-in-public.cc
www.nudephotolinks.com
www.nudepmates.com
www.nudesfortroops.com
www.nudexxx.pics
www.nylonfeetlove.com
www.nylonup.com
www.ohmob.com
www.oilyhandjobs.com
www.omacash.com
www.onlythumb.net
www.osexxx.com
www.partydorm.net
www.passionhdfan.com
www.peeonher.com
www.pennypaxlive.com
www.petrafeet.com
www.picsporner.com
www.pics.tube4.me
www.pinkvelvetvault.com
www.pinupfiles.gq
www.pissblog.com
www.porn40.com
www.pornforwomen.org.uk
www.pornnerdnetwork.com
www.pornositesearch.com
www.pornoxxbox.com
www.porn-service.us
www.pornsexerotica.com
www.pornstar-photos.com
www.pornstarsnaked.com
www.porntubered.com
www.povcuckold.com
www.povdfan.com
www.prettypetites.com
www.previews.danielleftv.com
www.previews.ftvmilfs.com
www.puffynetwork.com
www.pumaswede.com
www.purematurefan.com
www.purenudegirls.com
www.puretaboo.top
www.pussyxxxporn.com
www.qualitypage.com
www.realfloridaamateurs.com
www.realsubmitted.com
www.register.join-hitzefrei.com
www.richporn.com
www.romanvideo.com
www.romemajor.com
www.royaldressedladies.com
www.rubberdoll.net
www.rummp.com
www.sarajay.com
www.seemomsuck.com
www.sex-files.net
www.sexjohn.com
www.sexyandweknow.it
www.sexydirtygirl.net
www.sexyoutdoor.fun
www.sexytokyo.org
www.shandafay.com
www.sharkys.at
www.shedevils.com
www.shemaleblue.com
www.shemalesguide.com
www.silkengirl.net
www.simplyanal.com
www.siripornstar.com
www.skrog.net
www.sluts-asia.com
www.snbabes.com
www.snrcash.com
www.sophiedeelive.com
www.spankthisgay.com
www.speedofetish.com
www.spermmania.com
www.spicybabe.net
www.stars-celebrity.com
www.starsinporn.com
www.stockingsvr.com
www.stockingvideos.com
www.streaming.mature-money.com
www.streaptease.net
www.sunnylanelive.com
www.sweet-sin.com
www.tacamateurs.com
www.teamskeetfans.com
www.teenamites.com
www.teenporn.today
www.teenslikecocks.com
www.tgp.eroticstories.com
www.the-bikini.com
www.thebikinihut.com
www.thehairylady.com
www.thematurelady.com
www.thesandfly.com
www.thumbuster.com
www.timdir.com
www.tiny4kfan.com
www.tokyofacefuck.com
www.tokyopussycinema.com
www.tools.zbuckz.com
www.touchmylips.com
www.transexjapan.com
www.transfeet.com
www.tribute-to.com
www.trueamateurmodels.com
www.tsvivian.com
www.uhmature.com
www.uralesbian.com
www.vickyathome.com
www.vidsguide.com
www.virtualpornfan.com
www.weareshemale.com
www.webmasters.wetandpuffy.com
www.weknowporn.com
www.weliketosuck.com
www.wetchicks.info
www.whoore.com
www.wifebucket.com
www.wifecrazy.com
www.wildbdsmart.com
www.wildhotbabes.com
www.www2.3wisp.com
www.xartfan.com
www.xgirlsporn.com
www.xmilfporn.com
www.xnsfw.com
www.xxtgp.com
www.xxxsoup.com
xartfan.com
xgirlsporn.com
xmilfporn.com
xnsfw.com
xxtgp.com
xxxmemberchannels.com
xxxsoup.com

**Comment by anti-warrior** [comment]
I created a pull request with these domains in them. Hopefully this issue gets closed soon.

**Comment by Clefspeare13** [comment]
> 
> 
> I created a pull request with these domains in them. Hopefully this issue gets closed soon.

I've merged the pull request.

Sorry, I've been traveling and hadn't been able to attend to this.
