### ISSUE TITLE
Add these domains

### ISSUE THREAD

**Issue by invinciblevenom** [Clefspeare13/pornhosts#370]
I believe this domain is an Adult(-related) domain:

## Domains
lustflix.in
desi.lustflix.in

### All Submissions:
- [ x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?

**Comment by spirillen** [comment]
Did also add the www.$domain See https://mypdns.org/my-privacy-dns/porn-records/-/issues/566 for details
