### ISSUE TITLE
Remove the RARBG domains

### ISSUE THREAD

**Issue by 07416** [Clefspeare13/pornhosts#42]
RARBG is not an adult site, but a public torrent tracker.

```
rarbg.com
rarbg.to
```

**Comment by anti-warrior** [comment]
I made a pull request, this issue should be closed soon.

**Comment by 07416** [comment]
> 
> 
> I made a pull request, this issue should be closed soon.

@anti-warrior Thank you, I always that I should generally submit a pull request instead of creating an issue, when I'm capable.

**Comment by 07416** [comment]
@ Clefspeare13 How the RARBG and IPT domains ended up on the list in the first place?
