### ISSUE TITLE
More Hosts to Add

### ISSUE THREAD

**Issue by shaddowwz** [Clefspeare13/pornhosts#44]
The following hosts are not yet blocked by your list and allow videos to play or pictures to be shown in full detail. It is possible that others may have submitted these sites too, sorry about them not being listed alphabetically. Please consider adding them to your list.

elitebabes.com
erofus.com
xerotica.com
babehub.com
metarthunter.com
xarthunter.com
jperotica.com
femjoyhunter.com
joymiihub.com
eroticahunter.com
rylskyhunter.com
pmatehunter.com
gravurehunter.com
ftvhunter.com
hegrehunter.com
mplhunter.com
zemanihunter.com
metheaven.com
femangels.com
w4bhub.com
alshunter.com
digitalsweeties.com
drommhub.com
jpbeauties.com
xarthub.com
penthousehub.com
tlehunter.com
eroticandbeauty.com
domerotica.com
centerfoldhunter.com
erosmatch.com
glamourwebcams.com
pornq.com
javout.net
jav.watch
javcl.com
javfull.net
exquisiteslave.com
javstream.us
freeporno.xxx
digporn.pro
fineporn.pro
javsin.com
pornj.com
redwap.me
asiantube.porn
jav-porn.me
avsoeasy.com
javplay.me
sexvon.com
myxxxbase.mobi
anyxxx.mobi
vintage-erotica-forum.com
thewhoresofyore.com
my18pussy.com
taxi69.com
bigfuck.tv
morehardporn.com
hdpornpictures.net
teensexxxtube.com
selvaporno.com
petiteballerinasfucked.xxx
seks4.com
m.perfectgirls.net
porno365.sex

**Comment by w8Pk1y** [comment]
Please add these sites also.

desipapa.xxx
dirtypornphotos.com
indiansexphotos.com
indiankinkygirls.com
unseenmms.com
indiangirlsclub.com
hotnakedgirls.net
ooodesi.com
provocationstudio.ru
xbombo.com
the-urbn.com
indiansexvideos.porn
