### ISSUE TITLE
not working with email.domain

### ISSUE THREAD

**Issue by jensfreudenau** [Clefspeare13/pornhosts#49]
When I got a download link, e.g. email.strava.com or email.mapbox.com, the host file block the site on MacOs.

**Comment by Clefspeare13** [comment]
As in, a download link that came through the mail was blocked or a download from the domain email.strava.com was blocked? I have no mail providers in this hosts file, so I'm not sure what's happening.

**Comment by spirillen** [comment]
@jensfreudenau You'll have to provide more information so we can investigate an eventual error 

1. Is the the domains above parts of tracking domains for inline links?
1. Post full links from e-mail source
1. Or better post full source of e-mail

**Comment by jensfreudenau** [comment]
https://email.strava.com/wf/click?upn=FLdFplb9Rd0LY-2BmLy3OryqSMt4SGjjVQYVA0yyIjz9-2ByxXtxZPNqIVHWp1zkJFaA_ylTa-2F3MkdurmLwXoqAstk5PI7qt3HOSM2Zkgtsn6xzDlExgTwr3LBnYfpWQelUsVShD1WZPL96tA94mquUU39upBewimyLtDXoep1XS1bf-2Fyt0vx3PtGU8eZIMyjST5NNj0HWQpXLwrFcvpLRxwzu-2FhdCoysBpP0XvjT7L1IR4jbKPeE-2Bh8EUt1elDPpCSw50-2FTlnB6I356dTI5IlHBqMsgsiBKei7QAmMAE8rp-2FYxHEyWjsdHu1-2FSn3XpavhEyoBqsHrOEwNwOh2bSJgglzRD3-2B2siUM-2Bbu183zYnunTsD7HNjXKvPyrAkCgCeWWME327Yf04esQGYNAnGxv-2BZlH-2B3aZUXWmr1OLjuVWplJQ8g-3D

It is a mix of valet(https://laravel.com/docs/5.8/valet) and hosts. 

When I shutdown valet I get this:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/473937/72202434-cb907180-345f-11ea-86f0-850e78a27f8d.png">
Safari cannot create a connection to this server.
When I  "sudo mv /etc/hosts /etc/hosts_1"
it works.

**Comment by spirillen** [comment]
Hi @jensfreudenau try to have a look at this CNAME

```
dig email.strava.com

;email.strava.com.              IN      A

;; ANSWER SECTION:
email.strava.com.       21465   IN      CNAME   thirdparty.bnc.lt
```

When I looks through different hosts sources I finds the `bnc.it` domain

External hosts-file sources:
```
data/notrack/blocklists/domain.list:bnc.lt
data/mitchellkrogza/phishing.database/domain.list:bnc.lt
data/xorcan/domain.list:bnc.lt
```

So My first guess is you need to have a look at your hosts file, looking for `bnc.lt` But doing so will get you very exposed for the Cyber Criminals at that domain. It is blocked for a reason 

But I got the link to resolve, after removing `bnc.lt` from my local [Unbound](https://nlnetlabs.nl/projects/unbound/about/)

```
curl -I 'https://email.strava.com/wf/click?upn=FLdFplb9Rd0LY-2BmLy3OryqSMt4SGjjVQYVA0yyIjz9-2ByxXtxZPNqIVHWp1zkJFaA_ylTa-2F3MkdurmLwXoqAstk5PI7qt3HOSM2Zkgtsn6xzDlExgTwr3LBnYfpWQelUsVShD1WZPL96tA94mquUU39upBewimyLtDXoep1XS1bf-2Fyt0vx3PtGU8eZIMyjST5NNj0HWQpXLwrFcvpLRxwzu-2FhdCoysBpP0XvjT7L1IR4jbKPeE-2Bh8EUt1elDPpCSw50-2FTlnB6I356dTI5IlHBqMsgsiBKei7QAmMAE8rp-2FYxHEyWjsdHu1-2FSn3XpavhEyoBqsHrOEwNwOh2bSJgglzRD3-2B2siUM-2Bbu183zYnunTsD7HNjXKvPyrAkCgCeWWME327Yf04esQGYNAnGxv-2BZlH-2B3aZUXWmr1OLjuVWplJQ8g-3D'
HTTP/1.1 302 Found
Server: openresty/1.11.2.1
Date: Sat, 11 Jan 2020 18:01:20 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Location: http://www.strava.com/clubs/291487
X-Robots-Tag: noindex, nofollow
```

My best personal advise for these links would be to move the mails to the spam folder :closed_lock_with_key:
