### ISSUE TITLE
Commit about "dead pages" from 23. June is wrong

### ISSUE THREAD

**Issue by primeapple** [Clefspeare13/pornhosts#52]
Hey everyone, especially @Clefspeare13 .

I realised some of my previously blocked pages were not blocked anymore. So I started to look into it and found out, the were removed in Commit ef07f9e4f188e19f5051eda5f84a517ba841b2fb .

There you say you removed dead domains. However this is not true, since for example fr.pornhub.com is very much alive.

I also tried pinging some of the pages and get a whole variety from none/200/301/... HTTP Codes. 

I would suggest you readd the files or at least go through them again, for example with the command `
curl -Is $url | grep HTTP | cut -d ' ' -f2
`

Will also have a look into this.

**Comment by Clefspeare13** [comment]
I'll double check the domains. To check for dead domains I placed all domains from the hosts file into a separate .txt as links and then ran a .ps1 file with:

```
Foreach($Uri in $URLList) {
    try{
        #For proxy systems
        [System.Net.WebRequest]::DefaultWebProxy = [System.Net.WebRequest]::GetSystemWebProxy()
        [System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials

        #Web request
        $req = [system.Net.WebRequest]::Create($uri)
        $res = $req.GetResponse()
    }catch {
        #Err handling
        $res = $_.Exception.Response
    }
    $req = $null

    #Getting HTTP status code
    $int = [int]$res.StatusCode

    #Writing on the screen
    Write-Host "$int - $uri"

    #Disposing response if available
    if($res){
        $res.Dispose()
    }
}
```

Any urls which returned HTTP code 0 were removed. Because of the sheer number I didn't double check each one manually, but rather conducted a few spot checks.

**Comment by primeapple** [comment]
There is no HTTP code 0. See https://docs.microsoft.com/de-de/dotnet/api/system.net.httpstatuscode?view=netframework-4.8

My favorite approach to this problem:
Do `git diff 273d318f8cbaa05803db8a59cd25a4b897535125 ef07f9e4f188e19f5051eda5f84a517ba841b2fb` to see all the lines, that were removed in this commit.

However I have some troubles finding non existing pages. For example `curl pornhub.com` gives me an error (could not connect). `curl hot-dances.com` gives me an error, that the host could not be resolved. The first site exists, the second doesn't.

**Comment by primeapple** [comment]
Ok, so I did the following:

1. Find all the removed pages in the problematic commit. You removed the same urls in 3 different files, so we only need one list.
I created it using `git diff 273d318f8cbaa05803db8a59cd25a4b897535125 ef07f9e4f188e19f5051eda5f84a517ba841b2fb 0.0.0.0/hosts | grep -- -0.0.0.0 | sed 's/^.........//'`
Find here: https://cryptpad.fr/pad/#/2/pad/view/hhBSAFR9pDYBpZUJndtqPoaVDCNRwfjexY8D0CcvkEI/

2. Wrote a script to identify the result of trying to reach the site:
```bash
#!/bin/bash

TIMEOUT=$1
INPUTFILE=$2
OUTPUTFILE=$3

rm -f OUTPUTFILE

appendToOutputFile () {
    echo "$1 ; $2" >> $OUTPUTFILE
}

while read url; do
    # echo "$url"
    httpcode=`curl -s -o /dev/null --max-time $TIMEOUT --head -w "%{http_code}" $url`
    errorcode=$?
    case "$errorcode" in
        6)
            appendToOutputFile "$url" "Host could not be resolved"
            ;;
        28)
            appendToOutputFile "$url" "Connection timed out after ${TIMEOUT} seconds"
            ;;
        0)
            appendToOutputFile "$url" "Curl succeeded, HTTP-Code: ${httpcode}"
            ;;
        *)
            appendToOutputFile "$url" "Unknown Curl Error Code: ${errorcode}"
            ;;
    esac
    # echo $?
done < $INPUTFILE
```
You can run this with `bash $programname $timeoutinseconds $filewithurlsinlines $outputfile`. `$programname` is how you name the program, `$timeoutinseconds` is the time until we do a timeout, `$fiewithurlsinlines` is the file created in step 1, `$outputfile` is the name of the created outputfile (this file is created at start, if it exists it is deleted and newly created).
I did only test run this file (I don't have a vpn and don't want my ISP do get nervous about me fetching 3600 pornsites). Also my bash is not the best, but at least it works.

3.
I don't know which urls to readd. I would honestly suggest readding all of them that except the ones which domain could not be resolved.

**Comment by primeapple** [comment]
The pastebin link was dead, so I reuploaded it. How is it going on this one?

**Comment by spirillen** [comment]
All url will now be tasted with Travis-ci before being released via PyFunceble https://github.com/Clefspeare13/pornhosts/issues/53

**Comment by Clefspeare13** [comment]
> 
> 
> Ok, so I did the following:
> 
>     1. Find all the removed pages in the problematic commit. You removed the same urls in 3 different files, so we only need one list.
>        I created it using `git diff 273d318f8cbaa05803db8a59cd25a4b897535125 ef07f9e4f188e19f5051eda5f84a517ba841b2fb 0.0.0.0/hosts | grep -- -0.0.0.0 | sed 's/^.........//'`
>        Find here: https://pastebin.com/pEEGjg7i
> 
>     2. Wrote a script to identify the result of trying to reach the site:
> 
> 
> ```shell
> #!/bin/bash
> 
> TIMEOUT=$1
> INPUTFILE=$2
> OUTPUTFILE=$3
> 
> rm -f OUTPUTFILE
> 
> appendToOutputFile () {
>     echo "$1 ; $2" >> $OUTPUTFILE
> }
> 
> while read url; do
>     # echo "$url"
>     httpcode=`curl -s -o /dev/null --max-time $TIMEOUT --head -w "%{http_code}" $url`
>     errorcode=$?
>     case "$errorcode" in
>         6)
>             appendToOutputFile "$url" "Host could not be resolved"
>             ;;
>         28)
>             appendToOutputFile "$url" "Connection timed out after ${TIMEOUT} seconds"
>             ;;
>         0)
>             appendToOutputFile "$url" "Curl succeeded, HTTP-Code: ${httpcode}"
>             ;;
>         *)
>             appendToOutputFile "$url" "Unknown Curl Error Code: ${errorcode}"
>             ;;
>     esac
>     # echo $?
> done < $INPUTFILE
> ```
> 
> You can run this with `bash $programname $timeoutinseconds $filewithurlsinlines $outputfile`. `$programname` is how you name the program, `$timeoutinseconds` is the time until we do a timeout, `$fiewithurlsinlines` is the file created in step 1, `$outputfile` is the name of the created outputfile (this file is created at start, if it exists it is deleted and newly created).
> I did only test run this file (I don't have a vpn and don't want my ISP do get nervous about me fetching 3600 pornsites). Also my bash is not the best, but at least it works.
> 
>     1. I don't know which urls to readd. I would honestly suggest readding all of them that except the ones which domain could not be resolved.
> 
> 
> EDIT: Fixed link to removed url files

Thank you for this, I'll be checking all sites again with this script and update the hosts file by the end of the week.

**Comment by Clefspeare13** [comment]
I've readded a number of domains in e22faa0 as well as a file with domains which appear to be dead that I need to double check.

**Comment by spirillen** [comment]
Is this thread still relevant? or should it be closed?
