### ISSUE TITLE
wrong host ?

### ISSUE THREAD

**Issue by universalbyte** [Clefspeare13/pornhosts#54]
if its wrong, please remove "openload.co". its def. not a porn site. and what are "snuff" hosts doing in your "pornhostsfile" ?

**Comment by spirillen** [comment]
`openload.co` contains a lot of porn and should defiantly stay

**Comment by Clefspeare13** [comment]
> 
> 
> if its wrong, please remove "openload.co". its def. not a porn site. and what are "snuff" hosts doing in your "pornhostsfile" ?

Openload is so commonly used for hosting porn that I believe not including it in this file would do more harm than good. 

While this is first and foremost a porn hosts file, I see snuff sites as also worth blocking. If you disagree, they are in their own section at the end for easy identification and removal.

**Comment by spirillen** [comment]
Hi there @Clefspeare13 :wave: We thought you had left the building :unamused: 

Are you back to and fresh to continue the good work? Either way could you post a note about the submissions I'm working on in my fork of this project and whether you continue to maintain this nice repo?

I'm asking as there I no reasons to spent a lot of time if you don't like my contributions :question:

**Comment by Clefspeare13** [comment]
Hey spirillen, thank you for making sure this doesn't die. I've not been able to dedicate as much time to this as I would have liked, but I should be more active again going forward. 

I'm not sure what you're working on to be honest, can you link me what you mean and I'll take a look?

**Comment by spirillen** [comment]
aahh damned, just deleted the repo 1 min ago on Github, as you got back :unamused: 

But the concept was 
1. Splitting Porn and snuff into two sources
1. Use https://github.com/funilrys/PyFunceble to validate active vs inactive domains
1. After https://github.com/funilrys/PyFunceble have finished it's validation, it would combine the two sources into one hosts file

If you are interested, i would relatively fast (a couple of nights) be able to set this up again, and then you could see it alive. But only if you thinks this could be useful to you

But the drafted version survived on https://gitlab.com/my-privacy-dns/external-sources/pornhosts, take a peak, and let talk onward :smiley:

**Comment by Clefspeare13** [comment]
This does look quite interesting, I'll have to take a deeper dive when I have time, but it seems like it would make checking for dead domains much simpler.

**Comment by spirillen** [comment]
It would make it way more simpler as it runs on autopilot :man_pilot:  though ex. Travis-CI :smile: and this way it wouldn't mess with the original list before a manual interaction from a developer of your repo, but at the same time only feeds the hosts file with choose domains that is found active.
