### ISSUE TITLE
take a look

### ISSUE THREAD

**Issue by Danilopereira82** [Clefspeare13/pornhosts#61]
https://8kun.top

this site is not for porn at all
but just like 4chan
some boards are full of lewd stuff
would be better to decide what boards would be good to block

**Comment by spirillen** [comment]
Hi @Danilopereira82 

just from a random pic `https://8kun.top/vichan/index.html` shows your suggestion is impossible to oblige as these boards are sub-folders and not subdomains.

Do to the nature of hosts-file/DNS you can only block or not on a domain level

<details><summary>Screenshot of random board</summary>

![image](https://user-images.githubusercontent.com/44526987/71646940-ee4bb900-2cee-11ea-86cc-361a4223e5a6.png)

</details>

But if you could provide more details on how you think this could be obliged please advice :smile:

**Comment by Clefspeare13** [comment]
Since this is a board prominently full of porn and the boards are not subdomains I would prefer to keep the whole domain blocked.

**Comment by Danilopereira82** [comment]
> Since this is a board prominently full of porn and the boards are not subdomains I would prefer to keep the whole domain blocked.

same
the site is not about porn
but i don't think anything good will come from there
