### ISSUE TITLE
Non existant domain names?

### ISSUE THREAD

**Issue by pqarmitage** [Clefspeare13/pornhosts#7]
spankbang, sexdating, and collectionofbestporn are listed as domains, but do not appear to be valid.

**Comment by spirillen** [comment]
which TLD are we talking about? <https://en.wikipedia.org/wiki/Tld>

**Comment by pqarmitage** [comment]
The entries in 0.0.0.0/hosts and 127.0.0.1/hosts were just:
```
0.0.0.0 spankbang
0.0.0.0 sexdating
0.0.0.0 collectionofbestporn 
```
and likewise for 127.0.0.1

Commit 63201bc removed them from 0.0.0.0/hosts, and commit 24137f4 removed them from 127.0.0.1/hosts

**Comment by spirillen** [comment]
Super :+1: Is it OK to close this issue as solved now?

PS: What do you think of the list today? Is it still a relevance to you? And if you still using it, may I ask why you use it, and if you then would like to contribute to it?

See ex these to questions: https://github.com/Clefspeare13/pornhosts/issues/90 and https://github.com/Clefspeare13/pornhosts/issues/114
