### ISSUE TITLE
bing.com is Listed

### ISSUE THREAD

**Issue by peterstory** [Clefspeare13/pornhosts#8]
I noticed that `bing.com` is listed as a porn domain. I'm assuming this is a mistake! 
https://github.com/Clefspeare13/pornhosts/blob/e0b7f43fce36b6dcc9e42083c9740379a579464a/0.0.0.0/hosts#L1023

**Comment by peterstory** [comment]
I also notice that `4chan.org` is listed. Is that also a mistake?

**Comment by Clefspeare13** [comment]
These two snuck in somehow, thank you!

**Comment by Exper1mental** [comment]
Technically speaking bing.com is a porn domain. Using Bing images anyone can easily view porn unless you force all traffic to Bing.com to go to 204.79.197.220 instead (Bing SafeSearch)

Example from my HOSTS file:
> `# Force Bing SafeSearch`
> `204.79.197.220 www.bing.com`

The same applies to Google and Yahoo, except for yahoo you can't reroute image searches, you can only block them.

**Comment by Clefspeare13** [comment]
Of course, there are many methods to access porn in spite of this hosts file, it is meant to make it too difficult for you to bother trying rather than making porn exhaustively inaccessible, as that is unfeasible. I will consider forcing safesearch though
