### ISSUE TITLE
FP: adrevservice.com

### ISSUE THREAD

**Issue by spirillen** [Clefspeare13/pornhosts#83]
Not porn

![image](https://user-images.githubusercontent.com/44526987/73124075-2f09bb80-3f97-11ea-82f4-526f3459412f.png)

**Comment by Clefspeare13** [comment]
In this hosts file `adult.adrevservice.com` is blocked, which, as far as I can tell, is responsible for porn ads.

**Comment by spirillen** [comment]
That's the reason :smile: Then it should stay. 

My thought was it did not have any reason to be on a anti porn list as it is an ads-serving domain.
