### ISSUE TITLE
Video breakage because of rule p.jwpcdn.com

### ISSUE THREAD

**Issue by crssi** [Clefspeare13/pornhosts#85]
Open `https://siol.net/novice/slovenija/mocan-potres-stresel-zagreb-cutili-smo-ga-tudi-v-sloveniji-521448`
See video which is not playing because of rule `p.jwpcdn.com`.

Its not the only page with this problem.

Please, remove `p.jwpcdn.com` as soon as possible.

Thank you for this action and your work in general
Cheers

**Comment by spirillen** [comment]
Well it is whitelisted here <https://github.com/Ultimate-Hosts-Blacklist/whitelist/pull/39/files#diff-be20dd2ed6fde61bd80bbf717fa3d73dR557>

And it looks like it would be better to block `p.jwpcdn.com`

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +12 |  |  | video.siol.net | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.13.4/provider.hlsjs.js` |
| +12 |  |  | video.siol.net | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.13.4/jwplayer.core.controls.js` |
| +12 |  |  | video.siol.net | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.13.4/jwpsrv.js` |
| +12 | \|\|p.jwpcdn.com/player/plugins/vast/ | -- | video.siol.net | 3 | script | `https://ssl.p.jwpcdn.com/player/plugins/vast/v/8.7.13/vast.js` |
| +12 |  |  | video.siol.net | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.13.4/provider.hlsjs.js` |
| +12 |  |  | video.siol.net | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.13.4/jwplayer.core.controls.js` |
| +12 |  |  | video.siol.net | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.13.4/jwpsrv.js` |
| +12 | \|\|p.jwpcdn.com/player/plugins/vast/ | -- | video.siol.net | 3 | script | `https://ssl.p.jwpcdn.com/player/plugins/vast/v/8.7.13/vast.js` |
</details>

**Comment by crssi** [comment]
You haven't understand well.
This site/player provider has nothing to do with a porn.

The site in question is also just a normal news page and your classification does the breakage.

`jwpcdn.com` and `p.jwpcdn.com` should be removed from this list.

Cheers

**Comment by spirillen** [comment]
@crssi if you are looking at this commit https://github.com/Clefspeare13/pornhosts/commit/d5b67f5911f730e3391b348cac2bac61ee78940b you'll notice the entire `jwpcdn.com` actually is removed from the hosts files
