### ISSUE TITLE
Hentai domains to block

### ISSUE THREAD

**Issue by Silent-Marco** [Clefspeare13/pornhosts#86]
Please add these hentai porn domains to the blocklist:

> hentai-for.net
> hentai-for.me

**Comment by spirillen** [comment]
`hentai-for.net` redirects to `www.hentai-for.net`

![image](https://user-images.githubusercontent.com/44526987/79076809-2bb3df80-7cfd-11ea-9b1c-79f4033d18ac.png)

**Comment by spirillen** [comment]
`hentai-for.me` redirects to `hentai-for.net`
