### ISSUE TITLE
Invalid hosts in the latest update

### ISSUE THREAD

**Issue by StevenBlack** [Clefspeare13/pornhosts#87]
Hi Niclas @Clefspeare13 the new lines at the bottom, [in the latest update](https://github.com/Clefspeare13/pornhosts/blob/3d904e19dd831f81cabfd604242973702a3de798/0.0.0.0/hosts#L8940-L8955) are invalid hosts entries.

**Comment by Clefspeare13** [comment]
My bad, this has been fixed in 3554d81

**Comment by Clefspeare13** [comment]
@spirillen please remember to add domains with  `0.0.0.0`  preceding them

**Comment by spirillen** [comment]
Hmm that's my bad... taking it on my should.

Bug found... it is in my bash script.... as I copy pasted the code lines, from the lines I'm using to add to my own lists, I forgot to prepend the lines with `0.0.0.0`
