### ISSUE TITLE
Here are all the subdomains for TeddyGirls

### ISSUE THREAD

**Issue by pornblocking** [Clefspeare13/pornhosts#93]
Here are all the subdomains for TeddyGirls:
```
teddygirls.cc
www.teddygirls.cc
```

I know that a screenshot should be given, but I wont do that for this site as it contains child abuse material.

**Comment by spirillen** [comment]
> I know that a screenshot should be given, but I wont do that for this site as it contains child abuse material.

That sounds like a fair reason :+1:

**Comment by spirillen** [comment]
I have a Q about `webmail.teddygirls.cc` where is that relevant to this list?

`webdisk.teddygirls.cc`
![image](https://user-images.githubusercontent.com/44526987/80984147-c5b70580-8e2d-11ea-879e-6da08c6909b1.png)

cpcalendars.teddygirls.cc
![image](https://user-images.githubusercontent.com/44526987/80984208-d798a880-8e2d-11ea-8ac8-68aff3492915.png)

**Comment by pornblocking** [comment]
@spirillen Sure, I will remove them

**Comment by spirillen** [comment]
super thanks
